import type { InterviewQuestion } from '@/types';

export const reactInterviewQuestions: InterviewQuestion[] = [
  {
    question: 'What is React and why was it created?',
    answer: 'React is a JavaScript library for building user interfaces through declarative, component-based code. It was created by Facebook in 2013 to solve the problem of building complex, data-driven UIs that needed to update efficiently. Before React, developers manually manipulated the DOM, which was error-prone at scale. React introduced the Virtual DOM and reconciliation to minimize actual DOM operations, making UI updates fast and predictable.',
    difficulty: 'beginner',
    tip: 'Always mention: declarative, component-based, and the Virtual DOM — these are the three core ideas interviewers expect.',
  },
  {
    question: 'What is the Virtual DOM and how does React use it?',
    answer: 'The Virtual DOM is a lightweight, in-memory JavaScript representation of the real DOM. When state changes, React: (1) creates a new Virtual DOM tree, (2) diffs it against the previous tree (reconciliation), (3) calculates the minimal set of real DOM changes, (4) applies only those changes. This is efficient because real DOM operations are expensive — React batches and minimizes them. Important: the Virtual DOM itself is not faster; the advantage is that React can batch and minimize real DOM operations.',
    difficulty: 'beginner',
    followUp: ['What is reconciliation?', 'What is React Fiber?'],
    tip: 'A common mistake is saying "Virtual DOM is faster than the real DOM." It is not — it is overhead. The gain is from minimizing and batching real DOM updates.',
  },
  {
    question: 'What is the difference between state and props?',
    answer: 'Props are passed from parent to child — they define a component\'s interface and are read-only inside the receiving component. State is owned and managed inside the component — it is mutable via useState and causes re-renders when changed. Rule: if data comes from outside, it is a prop; if data is created inside the component, it is state. If a value can be derived from props or state, derive it — do not store it as extra state.',
    difficulty: 'beginner',
    tip: 'Interviewers follow up with: "What if two sibling components need the same state?" Answer: lift state to the nearest common ancestor.',
  },
  {
    question: 'What are the Rules of Hooks?',
    answer: 'Two rules: (1) Only call hooks at the top level — never inside if/else, loops, or nested functions. React identifies hooks by call order, not by name, so the order must be the same on every render. (2) Only call hooks from React function components or custom hooks. Not from regular JavaScript functions or class components.',
    difficulty: 'beginner',
    followUp: ['Why does call order matter for hooks?', 'What happens if you break the Rules of Hooks?'],
    tip: 'Explain WHY the rules exist, not just what they are. The answer is: React uses call order to associate state with the correct hook.',
  },
  {
    question: 'Explain the useEffect hook and its dependency array.',
    answer: 'useEffect runs side effects after rendering. The dependency array controls when it runs: no array = runs after every render; empty array [] = runs once after mount; [dep1, dep2] = runs when any dependency changes (using Object.is comparison). The returned cleanup function runs before the next effect and on unmount. The mental model: useEffect synchronizes your component with an external system (API, subscription, timer, DOM).',
    difficulty: 'intermediate',
    followUp: ['What is a stale closure in useEffect?', 'When does cleanup run?'],
    tip: 'Do not frame useEffect as a lifecycle hook. Frame it as synchronization: "I want this external thing to stay in sync with this state."',
  },
  {
    question: 'What is a stale closure in useEffect and how do you fix it?',
    answer: 'A stale closure happens when an effect captures a variable from its render, but the variable changes in later renders and the effect never sees the update. Classic example: setInterval inside useEffect with empty deps captures the initial count value and never increments correctly. Fix: use functional updates — setState(prev => prev + 1) receives the latest value as an argument, bypassing the closure. Or add the variable to the dependency array.',
    difficulty: 'intermediate',
    tip: 'This question tests whether you understand React\'s snapshot model. State is a snapshot per render — effects see the state from the render they were created in.',
  },
  {
    question: 'When would you use useMemo vs useCallback?',
    answer: 'Both stabilize references across renders. useMemo memoizes a computed value: const result = useMemo(() => expensiveCalc(a, b), [a, b]). useCallback memoizes a function reference: const fn = useCallback(() => doThing(id), [id]). Use useMemo for: expensive computations, reference-stable objects passed to React.memo children. Use useCallback for: functions passed as props to React.memo children, functions in useEffect dependencies that would cause loops. Neither should be used by default — only when you have a measured problem or need reference stability.',
    difficulty: 'intermediate',
    followUp: ['What is reference stability and why does it matter?', 'When would you NOT use useMemo?'],
    tip: 'Always add: "I measure first with the React Profiler before adding memoization." This shows production experience.',
  },
  {
    question: 'What is React.memo and when does it help?',
    answer: 'React.memo is a higher-order component that memoizes a functional component — it skips re-rendering if props have not changed (shallow comparison). It helps when: a component re-renders often due to parent re-renders, the render is expensive, and props are stable. It does NOT help when: props contain new object/function references created inline on every render, the component re-renders from its own state, or the render itself is cheap.',
    difficulty: 'intermediate',
    followUp: ['How do you make sure props passed to a React.memo component are stable?'],
  },
  {
    question: 'What is the Context API and when should you use it?',
    answer: 'Context provides a way to pass data through the component tree without prop drilling. Create with createContext, provide with Provider, consume with useContext. Use it for: auth state, theme, locale, anything needed by many components at different nesting levels. Avoid it for: high-frequency updates (every consumer re-renders on value change), data that only a few components need (just use props). It is dependency injection, not state management.',
    difficulty: 'intermediate',
    followUp: ['What is the Context performance problem?', 'How do you fix it?'],
    tip: '"Context is not a state management solution" is a key distinction. useState or Zustand manages the state — Context distributes it.',
  },
  {
    question: 'How does React reconciliation work?',
    answer: 'Reconciliation is how React updates the DOM efficiently. When state changes, React creates a new virtual DOM and diffs it against the previous one. Two rules: (1) Different element types — React unmounts the old and mounts new (no reuse). (2) Same type at same position — React updates attributes in-place. For lists: the key prop tells React which element is which across renders. Without keys, React uses position and may incorrectly reuse elements when items are reordered.',
    difficulty: 'advanced',
    followUp: ['Why must keys be stable and unique?', 'What happens if you use array index as a key?'],
    tip: 'Using array index as a key is a common bug — if items reorder, React maps keys wrong and may reuse the wrong DOM nodes.',
  },
  {
    question: 'What is React Fiber?',
    answer: 'Fiber is React\'s reconciliation engine introduced in React 16. Before Fiber, reconciliation was synchronous and recursive — a large update blocked the main thread, causing jank. Fiber represents each component as a "fiber node" (unit of work), making the work interruptible. React can pause, resume, and prioritize renders. This enables Concurrent Mode features: Suspense, startTransition, useDeferredValue, and time-slicing (high-priority updates like typing run ahead of lower-priority renders).',
    difficulty: 'advanced',
    tip: 'You do not need to know Fiber internals deeply — just know: it makes rendering interruptible, which enables concurrent features.',
  },
  {
    question: 'What is the difference between client state and server state?',
    answer: 'Client state is UI state that only exists in the browser: modal open/closed, active tab, theme. Server state is data from the server cached locally: users, posts, products. Server state has unique challenges: it can go stale, needs refetching, can be modified by other clients. Wrong approach: put server data in Redux or Zustand. Right approach: TanStack Query manages server state — it handles caching, refetching, loading/error states, and invalidation. Use useState/Zustand only for genuine client (UI) state.',
    difficulty: 'advanced',
    followUp: ['What is TanStack Query?', 'When would you still use Zustand for server data?'],
    tip: 'This is a senior-level question. The key insight: server state and client state have fundamentally different requirements and belong in different tools.',
  },
  {
    question: 'How do you implement protected routes in React Router?',
    answer: 'Create a RequireAuth component that reads auth state and renders Navigate to="/login" if not authenticated, passing the current location in state. Wrap protected route groups with RequireAuth. In the login handler, read location.state?.from?.pathname to redirect back to the intended page. Use replace on the Navigate and after login to avoid adding extra history entries.',
    difficulty: 'intermediate',
    tip: 'Always mention saving the intended destination (location.state.from) so users are redirected back after login.',
  },
  {
    question: 'What are Error Boundaries in React?',
    answer: 'Error Boundaries are class components that catch JavaScript errors in their child component tree during render, lifecycle methods, and constructors — preventing a single component error from crashing the entire app. Required methods: getDerivedStateFromError (update state to show fallback UI) and componentDidCatch (log to monitoring). They do NOT catch: event handler errors (use try/catch), async errors (use try/catch + error state), or SSR errors.',
    difficulty: 'intermediate',
    followUp: ['Why must Error Boundaries be class components?', 'How do you catch async errors in an Error Boundary?'],
  },
  {
    question: 'How would you optimize a React app that is rendering slowly?',
    answer: 'Step 1: Measure with React DevTools Profiler — find which components render unexpectedly often or take long. Step 2: Fix unnecessary re-renders — wrap expensive components with React.memo and stabilize their props with useCallback/useMemo. Step 3: Memoize expensive computations with useMemo. Step 4: Code split with React.lazy + Suspense. Step 5: Virtualize long lists with @tanstack/react-virtual. Step 6: Move state down — if state only affects a subtree, put it there. Never add optimization blindly.',
    difficulty: 'advanced',
    tip: '"Measure first" is the most important part of this answer. Interviewers want to know you do not prematurely optimize.',
  },
  {
    question: 'What is automatic batching in React 18?',
    answer: 'Batching means React groups multiple setState calls into a single re-render. Before React 18, batching only happened inside React event handlers — setState in setTimeout, fetch callbacks, or async functions would each trigger a separate render. React 18 introduced automatic batching everywhere: all state updates, regardless of where they originate, are batched into one render. This reduces unnecessary renders. Use flushSync from react-dom when you need to force a synchronous update.',
    difficulty: 'advanced',
    tip: 'Mention the before/after: React 17 only batched in event handlers; React 18 batches everywhere including async code.',
  },
];
