import type { Track } from '@/types';

export const tracks: Track[] = [
  // ── Roadmap ──────────────────────────────────────────────────────────
  {
    id: 'javascript',
    name: 'JavaScript',
    description: 'Master JavaScript from fundamentals to advanced patterns. Closures, async/await, prototypes, and more.',
    icon: 'JS',
    available: true,
    color: 'from-yellow-500 to-amber-500',
    lessonCount: 30,
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    description: 'Level up with static typing, generics, decorators, and enterprise-grade TypeScript patterns.',
    icon: 'TS',
    available: true,
    color: 'from-blue-500 to-blue-600',
    lessonCount: 18,
  },
  {
    id: 'react',
    name: 'React',
    description: 'Build modern UIs with hooks, context, performance patterns, and React 19 features.',
    icon: 'RE',
    available: true,
    color: 'from-cyan-500 to-sky-500',
    lessonCount: 30,
  },
  {
    id: 'databases',
    name: 'Databases',
    description: 'SQL, NoSQL, PostgreSQL, MongoDB, Redis, ORMs, database design, indexing, transactions — everything a software engineer needs.',
    icon: 'DB',
    available: true,
    color: 'from-sky-500 to-blue-600',
    lessonCount: 21,
  },
  {
    id: 'nodejs',
    name: 'Node.js',
    description: 'Node.js internals, Express, REST APIs, authentication, real-time, queues, caching, security, and production deployment.',
    icon: 'ND',
    available: true,
    color: 'from-green-600 to-emerald-600',
    lessonCount: 27,
  },
  {
    id: 'nextjs',
    name: 'Next.js',
    description: 'Full-stack React with App Router, Server Components, streaming, and deployment.',
    icon: 'NX',
    available: true,
    color: 'from-gray-600 to-gray-700',
    lessonCount: 27,
  },
  {
    id: 'webdev',
    name: 'Full Stack Engineering',
    description: 'Full stack development, real-world architecture, authentication, deployment, team workflows, and industry practices — the bridge from learning to building products.',
    icon: 'WD',
    available: true,
    color: 'from-orange-500 to-rose-500',
    lessonCount: 21,
  },
  {
    id: 'devops',
    name: 'DevOps',
    description: 'Linux, Docker, Dockerfiles, Docker Compose, GitHub Actions, CI/CD, cloud fundamentals, and Kubernetes — everything a developer needs to build, deploy, and ship.',
    icon: 'DO',
    available: true,
    color: 'from-orange-500 to-amber-600',
    lessonCount: 19,
  },
  {
    id: 'system-design',
    name: 'System Design',
    description: 'HLD, LLD, distributed systems, scalability, caching, databases, microservices, design patterns, and real-world case studies — everything to design systems and crack interviews.',
    icon: 'SD',
    available: true,
    color: 'from-teal-500 to-cyan-600',
    lessonCount: 22,
  },
  {
    id: 'dsa',
    name: 'DSA',
    description: 'Data structures and algorithms: arrays, trees, graphs, sorting, dynamic programming — Striver A2Z Sheet.',
    icon: 'DS',
    available: true,
    color: 'from-violet-500 to-purple-600',
    lessonCount: 400,
  },
  {
    id: 'placement',
    name: 'Engineering Interview Prep',
    description: 'Complete placement preparation: Aptitude, Logical Reasoning, Verbal Ability, CS Fundamentals, and Interview Preparation — everything in one unified track for engineering students.',
    icon: 'PL',
    available: true,
    color: 'from-indigo-500 to-violet-600',
    lessonCount: 35,
  },
  {
    id: 'behavioral',
    name: 'Behavioral Interviews',
    description: 'STAR method, HR and behavioral rounds, leadership, conflict, failure, self-intro, mock interviews, and 100+ question bank — everything to communicate authentically and confidently.',
    icon: 'BEH',
    available: true,
    color: 'from-cyan-500 to-blue-500',
    lessonCount: 17,
  },
  {
    id: 'ai-engineering',
    name: 'AI Engineering Fundamentals',
    description: 'Build real AI products: LLMs, prompt engineering, RAG, embeddings, agents, AI architecture, security, and evaluation — everything a software engineer needs to build and ship with AI.',
    icon: 'AI',
    available: true,
    color: 'from-purple-500 to-pink-500',
    lessonCount: 23,
  },
  // ── Supplementary ─────────────────────────────────────────────────────
  {
    id: 'aws',
    name: 'AWS Notes',
    description: 'AWS cloud services: EC2, S3, RDS, Lambda, IAM, VPC, CloudFront, and more — notes + interview prep.',
    icon: 'AW',
    available: true,
    color: 'from-orange-400 to-amber-500',
    lessonCount: 18,
  },
];
