import type { DSASection, DSATopic } from '@/types/dsa';

const patternTopics: DSATopic[] = [
  {
    id: 'patterns-theory', slug: 'patterns-theory', title: 'Pattern Printing — Theory (Read This First)',
    type: 'lesson', difficulty: 'easy',
    introduction: `A "pattern" problem asks you to print a shape made of characters (usually \`*\` or digits) using **nested loops**. They look decorative, but they exist to build the single most important muscle in programming: thinking in terms of **rows and columns with nested loops**. Every 2D grid algorithm you will ever write — matrix traversal, DP tables, image processing, board games, graphics — is built on this exact same skill.\n\nWhy it exists: a computer has no concept of a "shape" — it only knows how to repeat an instruction a fixed number of times. A pattern is really an exercise in translating "what do I see" into "how many times do I repeat, and what do I print each time."\n\nReal-world usage: this is the literal skill behind rendering a grid UI cell-by-cell, drawing a calendar, generating a multiplication table, laying out a spreadsheet, or iterating pixel-by-pixel in image processing — anywhere data is naturally 2D.`,
    theory: `**The one rule that solves every pattern:**\n\n> Outer loop = rows. Inner loop = columns.\n\n\`\`\`cpp\nfor (int row = 1; row <= n; row++) {       // walks every row, top to bottom\n    for (int col = 1; col <= /* depends on row */; col++) {\n        cout << "*";\n    }\n    cout << endl;   // ONE newline per row, after the inner loop finishes\n}\n\`\`\`\n\nThe entire "art" of a pattern problem is just figuring out the **inner loop's bound** — how many columns to print for *this particular row* — as a function of \`row\` and \`n\`.\n\n**Syntax explained token by token:**\n- \`for (int row = 1; row <= n; row++)\` — \`row\` starts at 1 and stops right after \`row == n\`. Patterns are usually numbered from row 1 because "row 3" is easier to reason about than "row 2" (0-indexed).\n- \`cout << "*";\` — prints a literal \`*\` **without** moving to a new line; repeated calls print characters right next to each other.\n- \`cout << endl;\` — moves the cursor to the next line. This must be called exactly **once per row**, after the inner loop — never inside it (putting it inside prints every star on its own line, breaking the shape — the single most common beginner bug).\n- \`cout << i << " ";\` — prints the numeric *value* of \`i\` (not a literal character), used for number patterns like \`1 2 3 4\`.\n\n**The 4 building-block shapes — master these and you can combine them into almost anything:**\n\n1. **Square** (constant width): inner loop runs \`col <= n\` every row.\n2. **Increasing triangle** (width grows with row): inner loop runs \`col <= row\`.\n\`\`\`\n*\n**\n***\n****\n\`\`\`\n3. **Decreasing triangle** (width shrinks with row): inner loop runs \`col <= n - row + 1\`. Check the edges: row=1 → n-1+1=n (full width) ✓; row=n → n-n+1=1 (single char) ✓.\n4. **Pyramid with spaces** (centered): two inner loops per row — leading spaces \`sp <= n - row\`, then stars \`col <= 2*row - 1\` (the odd sequence 1,3,5,7...).\n\`\`\`\n   *\n  ***\n *****\n*******\n\`\`\`\n\n**General recipe for any new pattern:**\n1. Count the rows → that's your outer loop bound.\n2. For each row, write out the first few rows by hand and find the formula for "how many characters" as a function of \`row\` and \`n\`.\n3. If a row has multiple sections (spaces, then stars, then maybe stars-then-spaces for a diamond), each section becomes its own inner loop run one after another, before the final \`endl\`.\n4. Trace the formula with \`row = 1\` and \`row = n\` by hand before running the code.`,
    codeExamples: [
      { title: 'Simple: Square of stars', language: 'cpp', code: `for (int row = 1; row <= n; row++) {\n    for (int col = 1; col <= n; col++) {\n        cout << "*";\n    }\n    cout << endl;\n}`, explanation: 'Constant-width inner loop — every row prints exactly n stars.' },
      { title: 'Practical: Increasing triangle', language: 'cpp', code: `for (int row = 1; row <= n; row++) {\n    for (int col = 1; col <= row; col++) {   // bound depends on the CURRENT row\n        cout << "*";\n    }\n    cout << endl;\n}`, explanation: 'The inner bound "col <= row" is what makes each row one star wider than the last.', dryRun: 'n=4 → row1 prints 1 star, row2 prints 2, row3 prints 3, row4 prints 4.' },
      { title: 'Industry-style: building a text-based grid/table', language: 'cpp', code: `// Same nested-loop skeleton renders any 2D grid, e.g. a multiplication table\nfor (int row = 1; row <= n; row++) {\n    for (int col = 1; col <= n; col++) {\n        cout << row * col << "\\t";   // print the "cell" value instead of a star\n    }\n    cout << endl;\n}`, explanation: 'The exact same outer=row/inner=column skeleton used for stars is used to render any 2D table of data — this is the pattern-printing skill applied directly.' },
    ],
    commonMistakes: [
      'Putting cout << endl inside the inner loop — every character gets its own line instead of forming a row.',
      'Off-by-one in the inner loop bound (< vs <=) — always trace row=1 and row=n by hand.',
      'Assuming a variable from main() is visible inside another function — it must be passed as a parameter (e.g. void printPattern(int n)).',
      'Mismatched braces in nested loops — write the closing brace immediately after the opening one, then fill in the body.',
    ],
    revisionNotes: [
      'Outer loop = rows, inner loop = columns. Always.',
      'endl goes once per row, after the inner loop.',
      'Find the inner-loop bound as a formula in terms of row and n; verify at row=1 and row=n.',
      'Decreasing width: n - row + 1. Pyramid width: 2*row - 1.',
    ],
    interviewQuestions: [
      { question: 'Why does the inner loop print columns and not the outer loop?', answer: 'Because you need to fully finish one row (all its columns) before moving to the next — the outer loop tracks "which row am I on", and for every single row you must run a complete inner loop over its columns. Swapping them would interleave characters from different rows.', difficulty: 'easy' },
      { question: 'How would you print a pattern where the width first increases then decreases (a diamond)?', answer: 'Print an increasing triangle for rows 1..n, then a decreasing triangle for rows n-1..1 (or n..1 depending on symmetry) — i.e., run the increasing-triangle loop, then run a mirrored decreasing-triangle loop directly after it.', difficulty: 'medium' },
    ],
    keyTakeaways: ['Outer loop = rows, inner loop = columns — this single rule solves every pattern problem.', 'The only real work is deriving the inner loop bound as a function of the row number.'],
  },
  {
    id: 'pattern-1', slug: 'pattern-1', title: 'Pattern 1: Square of Stars',
    type: 'problem', difficulty: 'easy',
    problemStatement: 'For N=4, print:\n* * * *\n* * * *\n* * * *\n* * * *',
    approaches: [{
      name: 'Nested Loops',
      intuition: 'Outer loop for rows (N rows), inner loop for columns (N stars per row).',
      steps: ['Run outer loop i from 1 to N (rows)', 'Run inner loop j from 1 to N (stars)', 'Print star and space after inner, newline after outer'],
      complexity: { time: 'O(N²)', space: 'O(1)' },
      code: `for (int i = 1; i <= n; i++) {\n    for (int j = 1; j <= n; j++) {\n        cout << "* ";\n    }\n    cout << "\\n";\n}`,
    }],
    hints: ['Use 2 nested loops', 'Outer loop = rows, inner loop = columns', 'Print newline after each row'],
    keyTakeaways: ['Every pattern uses nested loops: outer for rows, inner for columns.'],
  },
  {
    id: 'pattern-2', slug: 'pattern-2', title: 'Pattern 2: Right Triangle (Stars)',
    type: 'problem', difficulty: 'easy',
    problemStatement: 'For N=4, print:\n*\n* *\n* * *\n* * * *',
    approaches: [{
      name: 'Nested Loops',
      intuition: 'Row i has exactly i stars.',
      steps: ['Outer loop i from 1 to N', 'Inner loop j from 1 to i (stars = row number)'],
      complexity: { time: 'O(N²)', space: 'O(1)' },
      code: `for (int i = 1; i <= n; i++) {\n    for (int j = 1; j <= i; j++) cout << "* ";\n    cout << "\\n";\n}`,
    }],
    hints: ['Row number = number of stars on that row', 'Inner loop runs j from 1 to i'],
    keyTakeaways: ['When count depends on row, inner loop goes up to i.'],
  },
  {
    id: 'pattern-3', slug: 'pattern-3', title: 'Pattern 3: Right Triangle (Numbers)',
    type: 'problem', difficulty: 'easy',
    problemStatement: 'For N=4, print:\n1\n1 2\n1 2 3\n1 2 3 4',
    approaches: [{
      name: 'Nested Loops',
      intuition: 'Row i has numbers 1 to i.',
      steps: ['Outer loop i from 1 to N', 'Inner loop j from 1 to i, print j'],
      complexity: { time: 'O(N²)', space: 'O(1)' },
      code: `for (int i = 1; i <= n; i++) {\n    for (int j = 1; j <= i; j++) cout << j << " ";\n    cout << "\\n";\n}`,
    }],
    hints: ['Print j (column index), not i (row index)', 'Inner loop: j from 1 to i'],
    keyTakeaways: [],
  },
  {
    id: 'pattern-4', slug: 'pattern-4', title: 'Pattern 4: Repeated Row Number',
    type: 'problem', difficulty: 'easy',
    problemStatement: 'For N=4, print:\n1\n2 2\n3 3 3\n4 4 4 4',
    approaches: [{
      name: 'Nested Loops',
      intuition: 'Row i has the number i repeated i times.',
      steps: ['Outer loop i from 1 to N', 'Inner loop j from 1 to i, print i'],
      complexity: { time: 'O(N²)', space: 'O(1)' },
      code: `for (int i = 1; i <= n; i++) {\n    for (int j = 1; j <= i; j++) cout << i << " ";\n    cout << "\\n";\n}`,
    }],
    hints: ['Print i (row number), not j', 'Row i has i repetitions'],
    keyTakeaways: [],
  },
  {
    id: 'pattern-5', slug: 'pattern-5', title: 'Pattern 5: Inverted Right Triangle',
    type: 'problem', difficulty: 'easy',
    problemStatement: 'For N=4, print:\n* * * *\n* * *\n* *\n*',
    approaches: [{
      name: 'Nested Loops',
      intuition: 'Row i has N-i+1 stars (decreasing).',
      steps: ['Outer loop i from 1 to N', 'Inner loop j from 1 to N-i+1'],
      complexity: { time: 'O(N²)', space: 'O(1)' },
      code: `for (int i = 1; i <= n; i++) {\n    for (int j = 1; j <= n - i + 1; j++) cout << "* ";\n    cout << "\\n";\n}`,
    }],
    hints: ['Count decreases: row 1 → N stars, row 2 → N-1, ...', 'Inner loop: j from 1 to (N - i + 1)'],
    keyTakeaways: ['Inverted patterns use N-i+1 as the inner loop bound.'],
  },
  {
    id: 'pattern-6', slug: 'pattern-6', title: 'Pattern 6: Inverted Number Triangle',
    type: 'problem', difficulty: 'easy',
    problemStatement: 'For N=4, print:\n1 2 3 4\n1 2 3\n1 2\n1',
    approaches: [{
      name: 'Nested Loops',
      intuition: 'Row i has numbers 1 to N-i+1.',
      steps: ['Outer loop i from 1 to N', 'Inner loop j from 1 to N-i+1, print j'],
      complexity: { time: 'O(N²)', space: 'O(1)' },
      code: `for (int i = 1; i <= n; i++) {\n    for (int j = 1; j <= n - i + 1; j++) cout << j << " ";\n    cout << "\\n";\n}`,
    }],
    hints: ['Combine pattern 5 (bounds) with pattern 3 (printing j)'],
    keyTakeaways: [],
  },
  {
    id: 'pattern-7', slug: 'pattern-7', title: 'Pattern 7: Pyramid',
    type: 'problem', difficulty: 'easy',
    problemStatement: 'For N=4, print a centered pyramid:\n   *\n  * *\n * * *\n* * * *',
    approaches: [{
      name: 'Spaces + Stars',
      intuition: 'Row i has (N-i) spaces then (2i-1) stars... for a proper pyramid with single chars it is (N-i) spaces then i stars.',
      steps: ['For each row i (1 to N)', 'Print N-i spaces', 'Print i stars'],
      complexity: { time: 'O(N²)', space: 'O(1)' },
      code: `for (int i = 1; i <= n; i++) {\n    for (int j = 1; j <= n - i; j++) cout << " ";\n    for (int j = 1; j <= i; j++) cout << "* ";\n    cout << "\\n";\n}`,
    }],
    hints: ['Row i: print (N-i) spaces, then i stars', 'Spaces are needed for alignment'],
    keyTakeaways: ['Pyramid patterns need spaces. Count spaces = N - (row number).'],
  },
  {
    id: 'pattern-8', slug: 'pattern-8', title: 'Pattern 8: Inverted Pyramid',
    type: 'problem', difficulty: 'easy',
    problemStatement: 'For N=4, print inverted centered pyramid:\n* * * *\n * * *\n  * *\n   *',
    approaches: [{
      name: 'Spaces + Stars (Inverted)',
      intuition: 'Row i has (i-1) spaces then (N-i+1) stars.',
      steps: ['For each row i (1 to N)', 'Print i-1 spaces', 'Print N-i+1 stars'],
      complexity: { time: 'O(N²)', space: 'O(1)' },
      code: `for (int i = 1; i <= n; i++) {\n    for (int j = 1; j <= i - 1; j++) cout << " ";\n    for (int j = 1; j <= n - i + 1; j++) cout << "* ";\n    cout << "\\n";\n}`,
    }],
    hints: ['Spaces increase as rows go down', 'Stars decrease as rows go down'],
    keyTakeaways: [],
  },
  {
    id: 'pattern-9', slug: 'pattern-9', title: 'Pattern 9: Diamond',
    type: 'problem', difficulty: 'easy',
    problemStatement: 'For N=4, print a full diamond.',
    approaches: [{
      name: 'Two Pyramids',
      intuition: 'Top half = pyramid (patterns 7), Bottom half = inverted pyramid (pattern 8).',
      steps: ['Print rows 1 to N (top pyramid)', 'Print rows N-1 to 1 (bottom inverted pyramid)'],
      complexity: { time: 'O(N²)', space: 'O(1)' },
      code: `// Top half\nfor (int i = 1; i <= n; i++) {\n    for (int j = 1; j <= n - i; j++) cout << " ";\n    for (int j = 1; j <= 2 * i - 1; j++) cout << "*";\n    cout << "\\n";\n}\n// Bottom half\nfor (int i = n - 1; i >= 1; i--) {\n    for (int j = 1; j <= n - i; j++) cout << " ";\n    for (int j = 1; j <= 2 * i - 1; j++) cout << "*";\n    cout << "\\n";\n}`,
    }],
    hints: ['Diamond = top pyramid + bottom inverted pyramid', 'Middle row has 2*N-1 stars'],
    keyTakeaways: ['Complex patterns are combinations of simpler patterns.'],
  },
  {
    id: 'pattern-10', slug: 'pattern-10', title: 'Pattern 10: Butterfly',
    type: 'problem', difficulty: 'easy',
    problemStatement: 'Print a butterfly pattern for N=4.',
    approaches: [{
      name: 'Mirrored Triangles',
      intuition: 'Each row has stars on both sides with spaces in the middle. Left stars = i, right stars = i, spaces = 2*(N-i).',
      steps: ['Top half: row i → i stars, 2*(N-i) spaces, i stars', 'Bottom half: reverse'],
      complexity: { time: 'O(N²)', space: 'O(1)' },
      code: `// Top half\nfor (int i = 1; i <= n; i++) {\n    for (int j = 1; j <= i; j++) cout << "*";\n    for (int j = 1; j <= 2*(n-i); j++) cout << " ";\n    for (int j = 1; j <= i; j++) cout << "*";\n    cout << "\\n";\n}\n// Bottom half\nfor (int i = n; i >= 1; i--) {\n    for (int j = 1; j <= i; j++) cout << "*";\n    for (int j = 1; j <= 2*(n-i); j++) cout << " ";\n    for (int j = 1; j <= i; j++) cout << "*";\n    cout << "\\n";\n}`,
    }],
    hints: ['Each row has 3 parts: left stars, middle spaces, right stars', 'Left and right stars = row number'],
    keyTakeaways: [],
  },
  {
    id: 'pattern-11', slug: 'pattern-11', title: 'Pattern 11: Binary Triangle',
    type: 'problem', difficulty: 'easy',
    problemStatement: 'For N=5, print:\n1\n0 1\n1 0 1\n0 1 0 1\n1 0 1 0 1',
    approaches: [{
      name: 'Track start value',
      intuition: 'The starting value of each row alternates. Within a row, values alternate.',
      steps: ['For row i, starting value = 1 if i is odd, 0 if i is even', 'Alternate within the row'],
      complexity: { time: 'O(N²)', space: 'O(1)' },
      code: `for (int i = 1; i <= n; i++) {\n    int start = (i % 2 == 0) ? 0 : 1;\n    for (int j = 1; j <= i; j++) {\n        cout << start;\n        if (j < i) cout << " ";\n        start = 1 - start;  // toggle 0↔1\n    }\n    cout << "\\n";\n}`,
    }],
    hints: ['Use 1-start to toggle between 0 and 1', 'Row starting value depends on row parity'],
    keyTakeaways: ['1 - x toggles between 0 and 1 — a clean alternating technique.'],
  },
  {
    id: 'pattern-12', slug: 'pattern-12', title: 'Pattern 12: Number Crown',
    type: 'problem', difficulty: 'easy',
    problemStatement: 'For N=3, print:\n1        1\n1 2    2 1\n1 2 3 3 2 1',
    approaches: [{
      name: 'Mirror pattern',
      intuition: 'Row i has numbers 1 to i, then spaces, then i down to 1.',
      steps: ['Print 1 to i', 'Print 2*(N-i) spaces', 'Print i down to 1'],
      complexity: { time: 'O(N²)', space: 'O(1)' },
      code: `for (int i = 1; i <= n; i++) {\n    for (int j = 1; j <= i; j++) cout << j << " ";\n    for (int j = 1; j <= 2*(n-i); j++) cout << "  ";\n    for (int j = i; j >= 1; j--) cout << j << " ";\n    cout << "\\n";\n}`,
    }],
    hints: ['Three sections: increasing, spaces, decreasing', 'Mirror the numbers around the center'],
    keyTakeaways: [],
  },
  {
    id: 'pattern-13', slug: 'pattern-13', title: 'Pattern 13: Increasing Number Triangle',
    type: 'problem', difficulty: 'easy',
    problemStatement: 'For N=4:\n1\n2 3\n4 5 6\n7 8 9 10',
    approaches: [{
      name: 'Continuous counter',
      intuition: 'Numbers increase continuously. Maintain a counter that starts at 1 and increments.',
      steps: ['Keep a counter starting at 1', 'Each row i has i numbers', 'Print counter and increment'],
      complexity: { time: 'O(N²)', space: 'O(1)' },
      code: `int num = 1;\nfor (int i = 1; i <= n; i++) {\n    for (int j = 1; j <= i; j++) {\n        cout << num++ << " ";\n    }\n    cout << "\\n";\n}`,
    }],
    hints: ['Use a separate counter variable', 'Increment counter after printing'],
    keyTakeaways: [],
  },
  {
    id: 'pattern-14', slug: 'pattern-14', title: 'Pattern 14: Letter Triangle',
    type: 'problem', difficulty: 'easy',
    problemStatement: 'For N=4:\nA\nA B\nA B C\nA B C D',
    approaches: [{
      name: 'ASCII math',
      intuition: "Characters in C++ are stored as ASCII numbers. 'A' = 65, 'B' = 66... Adding j-1 to 'A' gives the j-th letter.",
      steps: ['Outer loop i from 1 to N', "Inner loop j from 1 to i, print char('A' + j - 1)"],
      complexity: { time: 'O(N²)', space: 'O(1)' },
      code: `for (int i = 1; i <= n; i++) {\n    for (int j = 1; j <= i; j++) {\n        cout << char('A' + j - 1) << " ";\n    }\n    cout << "\\n";\n}`,
    }],
    hints: ["char('A' + k) gives the (k+1)-th letter of the alphabet", 'A=0, B=1, C=2 offset from A'],
    keyTakeaways: ["char('A' + k) is the key to letter patterns. A=65 in ASCII."],
  },
  {
    id: 'pattern-15', slug: 'pattern-15', title: 'Pattern 15: Reversed Letter Triangle',
    type: 'problem', difficulty: 'easy',
    problemStatement: 'For N=4:\nA B C D\nA B C\nA B\nA',
    approaches: [{
      name: 'Inverted bounds',
      intuition: 'Row i has N-i+1 letters starting from A.',
      steps: ['Outer loop i from 1 to N', "Inner loop j from 1 to N-i+1, print char('A' + j - 1)"],
      complexity: { time: 'O(N²)', space: 'O(1)' },
      code: `for (int i = 1; i <= n; i++) {\n    for (int j = 1; j <= n - i + 1; j++) {\n        cout << char('A' + j - 1) << " ";\n    }\n    cout << "\\n";\n}`,
    }],
    hints: ['Combine inverted bounds (pattern 5) with letter printing (pattern 14)'],
    keyTakeaways: [],
  },
  {
    id: 'pattern-16', slug: 'pattern-16', title: 'Pattern 16: Alpha Triangle',
    type: 'problem', difficulty: 'easy',
    problemStatement: 'For N=4:\nA\nB B\nC C C\nD D D D',
    approaches: [{
      name: 'Row-based letter',
      intuition: "Row i uses the i-th letter (char('A' + i - 1)) repeated i times.",
      steps: ['Outer loop i from 1 to N', "Print char('A' + i - 1) exactly i times"],
      complexity: { time: 'O(N²)', space: 'O(1)' },
      code: `for (int i = 1; i <= n; i++) {\n    for (int j = 1; j <= i; j++) {\n        cout << char('A' + i - 1) << " ";\n    }\n    cout << "\\n";\n}`,
    }],
    hints: ["Letter for row i = char('A' + i - 1)", 'Print it i times'],
    keyTakeaways: [],
  },
  {
    id: 'pattern-17', slug: 'pattern-17', title: 'Pattern 17: Alpha Hill',
    type: 'problem', difficulty: 'easy',
    problemStatement: 'For N=4: centered alphabet pyramid (A at top center, increasing outward).',
    approaches: [{
      name: 'Spaces + Letters',
      intuition: "Row i has N-i spaces then letters A to i-th letter and back. Middle row has the most letters.",
      steps: ['Print N-i spaces', 'Print letters A, B, C...(i-th letter)', 'Print letters back ..., B, A'],
      complexity: { time: 'O(N²)', space: 'O(1)' },
      code: `for (int i = 1; i <= n; i++) {\n    for (int j = 1; j <= n - i; j++) cout << " ";\n    for (int j = 1; j <= i; j++) cout << char('A' + j - 1);\n    for (int j = i - 1; j >= 1; j--) cout << char('A' + j - 1);\n    cout << "\\n";\n}`,
    }],
    hints: ['Print forward letters, then reverse (excluding middle)', 'Each row is a palindrome of letters'],
    keyTakeaways: [],
  },
  {
    id: 'pattern-18', slug: 'pattern-18', title: 'Pattern 18: Alpha Triangle (from N)',
    type: 'problem', difficulty: 'easy',
    problemStatement: 'For N=4:\nE\nD E\nC D E\nB C D E',
    approaches: [{
      name: 'Count from row',
      intuition: "Row i starts at char('A' + N - i) and goes to char('A' + N - 1).",
      steps: ['Outer loop i from 1 to N', "Inner: j from N-i to N-1, print char('A' + j)"],
      complexity: { time: 'O(N²)', space: 'O(1)' },
      code: `for (int i = 1; i <= n; i++) {\n    for (int j = n - i; j <= n - 1; j++) {\n        cout << char('A' + j) << " ";\n    }\n    cout << "\\n";\n}`,
    }],
    hints: ['Last letter is always N-th letter', 'Start letter shifts left as row number increases'],
    keyTakeaways: [],
  },
  {
    id: 'pattern-19', slug: 'pattern-19', title: 'Pattern 19: Symmetric Butterfly (Stars)',
    type: 'problem', difficulty: 'easy',
    problemStatement: 'For N=4: symmetric void/hollow diamond pattern.',
    approaches: [{
      name: 'Hollow Shape',
      intuition: 'Print stars only at the border positions of each row.',
      steps: ['Determine border positions for each row', 'Print star at border, space elsewhere'],
      complexity: { time: 'O(N²)', space: 'O(1)' },
      code: `// Top half\nfor (int i = 1; i <= n; i++) {\n    for (int j = 1; j <= n; j++) {\n        if (j <= i) cout << "*";\n        else cout << " ";\n    }\n    for (int j = n; j >= 1; j--) {\n        if (j <= i) cout << "*";\n        else cout << " ";\n    }\n    cout << "\\n";\n}`,
    }],
    hints: ['For each row, determine which columns are stars vs spaces'],
    keyTakeaways: [],
  },
  {
    id: 'pattern-20', slug: 'pattern-20', title: 'Pattern 20: Hollow Rectangle',
    type: 'problem', difficulty: 'medium',
    problemStatement: 'For N=4, print a hollow N×N rectangle of stars.',
    approaches: [{
      name: 'Border Check',
      intuition: 'A cell is a star if it is on the first row, last row, first column, or last column. Otherwise it is a space.',
      steps: ['For row i and column j', 'Print * if i==1 or i==N or j==1 or j==N', 'Otherwise print space'],
      complexity: { time: 'O(N²)', space: 'O(1)' },
      code: `for (int i = 1; i <= n; i++) {\n    for (int j = 1; j <= n; j++) {\n        if (i == 1 || i == n || j == 1 || j == n)\n            cout << "*";\n        else\n            cout << " ";\n    }\n    cout << "\\n";\n}`,
    }],
    hints: ['Border condition: first/last row or first/last column', 'if (i==1 || i==n || j==1 || j==n) → star'],
    keyTakeaways: ['Hollow shapes: print border elements as star, interior as space.'],
  },
  {
    id: 'pattern-21', slug: 'pattern-21', title: 'Pattern 21: Hollow Pyramid',
    type: 'problem', difficulty: 'medium',
    problemStatement: 'For N=4: print a hollow centered pyramid.',
    approaches: [{
      name: 'Border-only Stars',
      intuition: 'In a pyramid, the border is the first column of the triangle, the last column, and the bottom row.',
      steps: ['For row i, print N-i leading spaces', 'Print stars only at leftmost, rightmost of the row, spaces in between', 'Last row is all stars'],
      complexity: { time: 'O(N²)', space: 'O(1)' },
      code: `for (int i = 1; i <= n; i++) {\n    for (int j = 1; j <= n - i; j++) cout << " ";\n    for (int j = 1; j <= 2 * i - 1; j++) {\n        if (j == 1 || j == 2 * i - 1 || i == n)\n            cout << "*";\n        else\n            cout << " ";\n    }\n    cout << "\\n";\n}`,
    }],
    hints: ['Border = first column (j==1), last column (j==2i-1), or last row (i==n)', 'Only last row is fully filled'],
    keyTakeaways: [],
  },
  {
    id: 'pattern-22', slug: 'pattern-22', title: 'Pattern 22: Number Pattern Diamond',
    type: 'problem', difficulty: 'medium',
    problemStatement: 'For N=4, print:\n4444444\n4333334\n4322234\n4321234\n4322234\n4333334\n4444444',
    approaches: [{
      name: 'Distance from center',
      intuition: 'Each cell value = min distance from any border. The outermost ring is N, next is N-1, etc.',
      steps: ['For cell (i, j) in a 2N-1 × 2N-1 grid', 'Value = N - min(i, j, 2N-1-i, 2N-1-j)'],
      complexity: { time: 'O(N²)', space: 'O(1)' },
      code: `int size = 2 * n - 1;\nfor (int i = 0; i < size; i++) {\n    for (int j = 0; j < size; j++) {\n        int top = i, left = j;\n        int bottom = size - 1 - i, right = size - 1 - j;\n        cout << n - min({top, left, bottom, right});\n    }\n    cout << "\\n";\n}`,
    }],
    hints: ['This is a (2N-1) × (2N-1) grid', 'Value at (i,j) = N - minimum distance from any edge', 'min(i, j, 2N-1-i, 2N-1-j) gives distance from nearest edge'],
    solution: `int size = 2 * n - 1;\nfor (int i = 0; i < size; i++) {\n    for (int j = 0; j < size; j++) {\n        int top = i, left = j;\n        int bottom = size - 1 - i, right = size - 1 - j;\n        cout << n - min({top, left, bottom, right});\n    }\n    cout << "\\n";\n}`,
    keyTakeaways: ['Distance from border = min(row_from_top, row_from_bottom, col_from_left, col_from_right). Very useful technique.'],
  },
];

export const patternsSection: DSASection = {
  id: 'patterns',
  slug: 'patterns',
  title: 'Patterns',
  description: '22 printing patterns to build nested loop mastery and spatial thinking for DSA.',
  icon: '◼',
  color: 'from-emerald-500 to-teal-600',
  topics: patternTopics,
};
