import type { DSASection } from '@/types/dsa';

export const mathsSection: DSASection = {
  id: 'basic-maths',
  slug: 'basic-maths',
  title: 'Know Basic Maths',
  description: 'Mathematical operations on numbers: digits, GCD, prime checking, Armstrong numbers, and divisors.',
  icon: '🔢',
  color: 'from-yellow-400 to-orange-500',
  topics: [
    {
      id: 'basic-maths-theory',
      slug: 'basic-maths-theory',
      title: 'Basic Maths for DSA — Theory (Read This First)',
      type: 'lesson',
      difficulty: 'easy',
      introduction: `Almost every "maths" DSA problem (digit extraction, GCD, primality, divisors, Armstrong/palindrome numbers) boils down to two operations you will use over and over: **isolating the last digit of a number** with \`% 10\`, and **removing the last digit** with \`/ 10\`. Why it exists as its own topic: these two operations, chained in a loop, let you process a number digit-by-digit without ever converting it to a string — which is faster and is what interviewers expect. Real-world usage: checksum validation (credit card Luhn algorithm), hashing, cryptography (GCD/modular arithmetic in RSA), and any problem involving number theory.`,
      theory: `**The modulo/divide loop — the single most reused pattern in this section:**\n\`\`\`cpp\nint n = 1234;\nwhile (n > 0) {\n    int lastDigit = n % 10;   // % (modulo) gives the REMAINDER after division — for a base-10 number, that remainder is always its last digit\n    n = n / 10;               // integer division DISCARDS the last digit (1234 / 10 == 123, not 123.4)\n    // do something with lastDigit\n}\n\`\`\`\n- \`%\` (modulo) — returns the remainder of a division. \`17 % 5 == 2\` because \`17 = 3*5 + 2\`. For extracting digits, \`n % 10\` always isolates the ones-place digit because 10 is the base we count in.\n- \`/\` (integer division) — when both operands are \`int\`, C++ truncates toward zero and drops any fractional part. \`1234 / 10 == 123\`.\n- The loop terminates when \`n\` becomes \`0\`, meaning every digit has been peeled off.\n\n**GCD (Greatest Common Divisor) — Euclidean algorithm:**\n\`\`\`cpp\nint gcd(int a, int b) {\n    while (b != 0) {\n        int temp = b;\n        b = a % b;   // key insight: gcd(a,b) == gcd(b, a % b)\n        a = temp;\n    }\n    return a;\n}\n\`\`\`\nWhy this works: any common divisor of \`a\` and \`b\` also divides \`a % b\`, so the pair \`(a, b)\` and \`(b, a % b)\` always share the same GCD, but the numbers shrink fast (roughly halving every two steps), giving **O(log(min(a,b)))** time — far better than checking every number up to \`min(a,b)\`.\n\n**Primality check:**\n\`\`\`cpp\nbool isPrime(int n) {\n    if (n < 2) return false;\n    for (int i = 2; i * i <= n; i++) {   // only need to check up to sqrt(n)\n        if (n % i == 0) return false;\n    }\n    return true;\n}\n\`\`\`\nWhy only up to \`sqrt(n)\`? If \`n = a * b\` with \`a <= b\`, then \`a\` cannot be bigger than \`sqrt(n)\` (otherwise \`a*b\` would exceed \`n\`). So if no divisor exists up to \`sqrt(n)\`, none exists at all. This turns an O(n) check into **O(sqrt(n))**.\n\n**Finding all divisors:** loop \`i\` from 1 to \`sqrt(n)\`; whenever \`n % i == 0\`, both \`i\` and \`n/i\` are divisors — this halves the work compared to checking every number up to \`n\`.`,
      codeExamples: [
        { title: 'Simple: count digits', language: 'cpp', code: `int countDigits(int n) {\n    int count = 0;\n    while (n > 0) {\n        n = n / 10;\n        count++;\n    }\n    return count;\n}`, explanation: 'Peel off one digit per loop iteration using / 10; count how many peels it takes to reach 0.' },
        { title: 'Practical: reverse a number', language: 'cpp', code: `int reverseNumber(int n) {\n    int reversed = 0;\n    while (n > 0) {\n        int lastDigit = n % 10;\n        reversed = reversed * 10 + lastDigit;   // shift existing digits left, append the new one\n        n = n / 10;\n    }\n    return reversed;\n}`, explanation: 'reversed*10 shifts all previously placed digits one position to the left, making room to append lastDigit at the ones place.', dryRun: 'n=123 -> extract 3, reversed=3, n=12 -> extract 2, reversed=32, n=1 -> extract 1, reversed=321, n=0 -> stop.' },
        { title: 'Industry-style: Luhn checksum digit-sum idea', language: 'cpp', code: `// Credit-card validation (Luhn algorithm) reuses the exact same digit-extraction loop\nbool luhnCheck(long long number) {\n    int sum = 0; bool doubleDigit = false;\n    while (number > 0) {\n        int digit = number % 10;\n        if (doubleDigit) { digit *= 2; if (digit > 9) digit -= 9; }\n        sum += digit;\n        doubleDigit = !doubleDigit;\n        number /= 10;\n    }\n    return sum % 10 == 0;\n}`, explanation: 'Real payment systems validate card numbers with exactly this % 10 / 10 digit loop, just with extra arithmetic per digit.' },
      ],
      commonMistakes: [
        'Using n % 10 on a negative number and forgetting C++ modulo can return a negative remainder (e.g. -7 % 3 == -1, not 2 like in Python) — take abs(n) first if sign matters.',
        'Checking primality by looping all the way to n instead of sqrt(n) — technically correct but far slower than necessary.',
        'Off-by-one in the divisor loop: use i * i <= n, not i <= n, and remember to check i*i for overflow on large n (use long long).',
        'Forgetting that 0 and 1 are not prime — always special-case n < 2.',
      ],
      revisionNotes: [
        '% 10 extracts the last digit; / 10 removes it. Loop until n == 0.',
        'GCD(a,b) = GCD(b, a % b) — Euclidean algorithm, O(log(min(a,b))).',
        'Primality / divisor search only needs to go up to sqrt(n).',
        'Watch for integer overflow — use long long for anything that might exceed ~2.1 billion.',
      ],
      interviewQuestions: [
        { question: 'Why do we only check divisibility up to sqrt(n) for primality testing?', answer: 'If n has a factor larger than sqrt(n), it must pair with a factor smaller than sqrt(n) (since their product is n). So if no factor exists up to sqrt(n), none exists anywhere, making sqrt(n) a safe and complete cutoff — reducing the check from O(n) to O(sqrt(n)).', difficulty: 'easy' },
        { question: 'Why does the Euclidean GCD algorithm terminate, and how fast is it?', answer: 'Each step replaces (a,b) with (b, a % b), and a % b is always strictly smaller than b, so the pair shrinks every iteration until b reaches 0. It provably takes O(log(min(a,b))) steps because the smaller number shrinks by at least half every two iterations (a Fibonacci-related bound).', difficulty: 'medium' },
      ],
      keyTakeaways: ['% and / together let you process any number digit-by-digit without strings.', 'sqrt(n) is the recurring bound for primality/divisor problems — memorize why.'],
    },
    {
      id: 'count-digits',
      slug: 'count-digits',
      title: 'Count All Digits of a Number',
      type: 'problem',
      difficulty: 'easy',
      pattern: 'Number Manipulation',
      conceptsRequired: ['While loop', 'Integer division', 'Modulo'],
      problemStatement: 'Given an integer N, count the number of digits in N.',
      examples: [
        { input: 'N = 12345', output: '5', explanation: '12345 has 5 digits.' },
        { input: 'N = 0', output: '1', explanation: '0 has 1 digit.' },
        { input: 'N = 100', output: '3' },
      ],
      constraints: ['N >= 0', 'N <= 10^18'],
      approaches: [
        {
          name: 'Brute Force',
          intuition: 'Convert to string and count length.',
          steps: ['Convert N to string', 'Return string length'],
          complexity: { time: 'O(log N)', space: 'O(log N)' },
          code: `int countDigits(long long n) {\n    if (n == 0) return 1;\n    return to_string(n).length();\n}`,
        },
        {
          name: 'Optimal — Digit extraction loop',
          intuition: 'Divide by 10 repeatedly until N becomes 0. Count iterations.',
          steps: ['Handle edge case: n == 0 → return 1', 'While n > 0: increment count, divide n by 10', 'Return count'],
          complexity: { time: 'O(log N)', space: 'O(1)' },
          code: `int countDigits(long long n) {\n    if (n == 0) return 1;\n    int count = 0;\n    while (n > 0) {\n        count++;\n        n /= 10;\n    }\n    return count;\n}`,
          dryRun: 'n=12345: 12345→1234 (1), 1234→123 (2), 123→12 (3), 12→1 (4), 1→0 (5). Return 5.',
        },
        {
          name: 'Mathematical — log₁₀',
          intuition: 'Number of digits = floor(log₁₀(N)) + 1',
          steps: ['Use floor(log10(n)) + 1'],
          complexity: { time: 'O(1)', space: 'O(1)' },
          code: `int countDigits(long long n) {\n    if (n == 0) return 1;\n    return (int)log10(n) + 1;\n}`,
        },
      ],
      hints: [
        'n % 10 gives the last digit. n / 10 removes the last digit.',
        'Keep dividing by 10 until n becomes 0. Count the iterations.',
        'Edge case: n = 0 should return 1.',
      ],
      solution: `int countDigits(long long n) {\n    if (n == 0) return 1;\n    int count = 0;\n    while (n > 0) { count++; n /= 10; }\n    return count;\n}`,
      keyTakeaways: ['while (n > 0) { n /= 10; } is the fundamental digit-processing loop.'],
    },
    {
      id: 'reverse-number',
      slug: 'reverse-number',
      title: 'Reverse a Number',
      type: 'problem',
      difficulty: 'easy',
      pattern: 'Number Manipulation',
      conceptsRequired: ['While loop', 'Modulo', 'Integer division'],
      problemStatement: 'Given an integer N, return the reverse of N. If N is negative, reverse the digits and keep the negative sign.',
      examples: [
        { input: 'N = 12345', output: '54321' },
        { input: 'N = 100', output: '1', explanation: 'Leading zeros are dropped.' },
        { input: 'N = -123', output: '-321' },
      ],
      approaches: [
        {
          name: 'Digit extraction',
          intuition: 'Extract last digit with %10, add to reversed number after shifting left (*10), remove last digit with /10.',
          steps: ['Handle negative: work with abs(n)', 'While n > 0: extract last digit (n%10), add to rev (rev=rev*10+digit), remove digit (n/10)', 'Restore sign'],
          complexity: { time: 'O(log N)', space: 'O(1)' },
          code: `long long reverseNumber(long long n) {\n    bool neg = (n < 0);\n    n = abs(n);\n    long long rev = 0;\n    while (n > 0) {\n        int digit = n % 10;\n        rev = rev * 10 + digit;\n        n /= 10;\n    }\n    return neg ? -rev : rev;\n}`,
          dryRun: 'n=123: rev=0. digit=3, rev=3, n=12. digit=2, rev=32, n=1. digit=1, rev=321, n=0. Return 321.',
        },
      ],
      hints: [
        'Last digit = n % 10. Remove last digit = n / 10.',
        'Build reversed number: rev = rev * 10 + last_digit',
        'Handle overflow: if reversed > INT_MAX, return 0 (LeetCode constraint).',
      ],
      solution: `long long reverseNumber(long long n) {\n    bool neg = (n < 0); n = abs(n);\n    long long rev = 0;\n    while (n > 0) {\n        rev = rev * 10 + n % 10;\n        n /= 10;\n    }\n    return neg ? -rev : rev;\n}`,
      leetcodeUrl: 'https://leetcode.com/problems/reverse-integer/',
      keyTakeaways: ['rev = rev*10 + digit — the fundamental pattern for building a number from digits.'],
    },
    {
      id: 'palindrome-number',
      slug: 'palindrome-number',
      title: 'Palindrome Number',
      type: 'problem',
      difficulty: 'easy',
      pattern: 'Number Manipulation',
      conceptsRequired: ['Reverse number', 'Modulo'],
      problemStatement: 'Given an integer N, return true if it is a palindrome, false otherwise. A number is a palindrome if it reads the same forwards and backwards.',
      examples: [
        { input: 'N = 121', output: 'true' },
        { input: 'N = -121', output: 'false', explanation: 'Negative numbers are not palindromes.' },
        { input: 'N = 1221', output: 'true' },
      ],
      approaches: [
        {
          name: 'Reverse and compare',
          intuition: 'Reverse the number and check if it equals the original.',
          steps: ['Negative numbers → false', 'Compute reversed number', 'Compare reversed with original'],
          complexity: { time: 'O(log N)', space: 'O(1)' },
          code: `bool isPalindrome(int n) {\n    if (n < 0) return false;\n    long long orig = n, rev = 0;\n    while (n > 0) {\n        rev = rev * 10 + n % 10;\n        n /= 10;\n    }\n    return orig == rev;\n}`,
        },
      ],
      hints: [
        'A negative number cannot be a palindrome.',
        'Reverse the number using the digit extraction technique.',
        'Compare the reversed number with the original.',
      ],
      solution: `bool isPalindrome(int n) {\n    if (n < 0) return false;\n    long long orig = n, rev = 0, temp = n;\n    while (temp > 0) { rev = rev * 10 + temp % 10; temp /= 10; }\n    return orig == rev;\n}`,
      leetcodeUrl: 'https://leetcode.com/problems/palindrome-number/',
      keyTakeaways: ['Combine reverse number technique with equality check.'],
    },
    {
      id: 'gcd-two-numbers',
      slug: 'gcd-two-numbers',
      title: 'GCD of Two Numbers',
      type: 'problem',
      difficulty: 'easy',
      pattern: 'Mathematical Algorithm',
      conceptsRequired: ['Euclidean algorithm', 'Modulo'],
      problemStatement: 'Find the Greatest Common Divisor (GCD) of two positive integers a and b.',
      examples: [
        { input: 'a=12, b=8', output: '4', explanation: 'GCD(12,8) = GCD(8,4) = GCD(4,0) = 4.' },
        { input: 'a=100, b=75', output: '25' },
      ],
      theory: `The **Euclidean Algorithm** is one of the oldest and most elegant algorithms:\n\nGCD(a, b) = GCD(b, a % b) until b = 0.\n\n**Why it works:** GCD(a, b) = GCD(b, a mod b). Any divisor of a and b also divides a mod b.\n\n**Time complexity:** O(log(min(a,b))) — extremely fast.\n\n**LCM:** LCM(a, b) = a × b / GCD(a, b)\nUse (long long)a / gcd(a,b) * b to avoid overflow.`,
      approaches: [
        {
          name: 'Brute Force',
          intuition: 'Check all numbers from 1 to min(a,b) for divisibility.',
          steps: ['Iterate from 1 to min(a,b)', 'Track largest number that divides both'],
          complexity: { time: 'O(min(a,b))', space: 'O(1)' },
          code: `int gcd(int a, int b) {\n    int ans = 1;\n    for (int i = 1; i <= min(a, b); i++) {\n        if (a % i == 0 && b % i == 0) ans = i;\n    }\n    return ans;\n}`,
        },
        {
          name: 'Euclidean Algorithm',
          intuition: 'GCD(a, b) = GCD(b, a%b). Each step reduces the problem significantly.',
          steps: ['While b ≠ 0: a = b, b = a%b', 'Return a'],
          complexity: { time: 'O(log(min(a,b)))', space: 'O(1)' },
          code: `int gcd(int a, int b) {\n    while (b != 0) {\n        int temp = b;\n        b = a % b;\n        a = temp;\n    }\n    return a;\n}\n\n// Recursive version (elegant)\nint gcd(int a, int b) {\n    return b == 0 ? a : gcd(b, a % b);\n}\n\n// C++17 has built-in: __gcd(a, b) or gcd(a, b) from <numeric>`,
          dryRun: 'GCD(48, 18): gcd(18, 48%18=12) → gcd(12, 18%12=6) → gcd(6, 12%6=0) → return 6.',
        },
      ],
      hints: [
        'GCD(a, b) = GCD(b, a%b) — this is the Euclidean algorithm.',
        'Base case: GCD(a, 0) = a.',
        'For LCM: LCM(a,b) = a/GCD(a,b) * b (compute GCD first to avoid overflow).',
      ],
      solution: `int gcd(int a, int b) {\n    return b == 0 ? a : gcd(b, a % b);\n}`,
      keyTakeaways: [
        'Euclidean GCD is O(log n) — always use it over brute force.',
        'LCM(a,b) = a * b / GCD(a,b). Compute as (a/gcd)*b to avoid overflow.',
        'C++17: use std::gcd(a, b) from <numeric>.',
      ],
    },
    {
      id: 'armstrong-number',
      slug: 'armstrong-number',
      title: 'Check if Number is Armstrong',
      type: 'problem',
      difficulty: 'easy',
      pattern: 'Number Manipulation',
      conceptsRequired: ['Digit extraction', 'Power function'],
      problemStatement: 'An Armstrong number (narcissistic number) of n digits is one where the sum of each digit raised to the power n equals the number itself. Example: 153 = 1³ + 5³ + 3³.',
      examples: [
        { input: '153', output: 'true', explanation: '1³+5³+3³ = 1+125+27 = 153.' },
        { input: '9474', output: 'true', explanation: '9⁴+4⁴+7⁴+4⁴ = 6561+256+2401+256 = 9474.' },
        { input: '123', output: 'false' },
      ],
      approaches: [
        {
          name: 'Digit extraction + power',
          intuition: 'Count digits, then check if sum of (each digit ^ count) equals original.',
          steps: ['Count number of digits (n)', 'For each digit d: sum += d^n (use pow() or custom power)', 'Check sum == original'],
          complexity: { time: 'O(log N)', space: 'O(1)' },
          code: `bool isArmstrong(int num) {\n    int n = to_string(num).length(); // digit count\n    int sum = 0, temp = num;\n    while (temp > 0) {\n        int digit = temp % 10;\n        sum += pow(digit, n);  // digit^n\n        temp /= 10;\n    }\n    return sum == num;\n}`,
        },
      ],
      hints: [
        'First, count the number of digits (use log10 or digit loop).',
        'Extract each digit and raise to power = number of digits.',
        'Sum all powered digits and compare with original.',
      ],
      solution: `bool isArmstrong(int num) {\n    int n = to_string(num).length();\n    int sum = 0, temp = num;\n    while (temp > 0) {\n        int d = temp % 10;\n        sum += (int)pow(d, n);\n        temp /= 10;\n    }\n    return sum == num;\n}`,
      keyTakeaways: ['Armstrong = sum of (digit ^ number_of_digits) == number.'],
    },
    {
      id: 'print-all-divisors',
      slug: 'print-all-divisors',
      title: 'Print All Divisors',
      type: 'problem',
      difficulty: 'easy',
      pattern: 'Mathematical',
      conceptsRequired: ['Loops', 'Square root optimization'],
      problemStatement: 'Given a positive integer N, print all its divisors in sorted order.',
      examples: [
        { input: '36', output: '1 2 3 4 6 9 12 18 36', explanation: 'All numbers that divide 36 evenly.' },
        { input: '12', output: '1 2 3 4 6 12' },
      ],
      theory: `**Key insight:** Divisors come in pairs. If i divides n, then n/i also divides n. All pairs have one number ≤ √n and one ≥ √n. So only check up to √n.\n\nExample: Divisors of 36: (1,36), (2,18), (3,12), (4,9), (6,6). Check up to 6=√36.`,
      approaches: [
        {
          name: 'Brute Force O(N)',
          intuition: 'Check all numbers from 1 to N.',
          steps: ['For i from 1 to n: if n%i==0, add i to result'],
          complexity: { time: 'O(N)', space: 'O(number of divisors)' },
          code: `void printDivisors(int n) {\n    for (int i = 1; i <= n; i++) {\n        if (n % i == 0) cout << i << " ";\n    }\n}`,
        },
        {
          name: 'Optimal O(√N)',
          intuition: 'For each i up to √n, if i divides n, both i and n/i are divisors.',
          steps: ['For i from 1 to √n:', 'If n%i==0: add i. If i != n/i: add n/i.', 'Sort the result for sorted output.'],
          complexity: { time: 'O(√N)', space: 'O(number of divisors)' },
          code: `void printDivisors(int n) {\n    vector<int> divisors;\n    for (int i = 1; i * i <= n; i++) {\n        if (n % i == 0) {\n            divisors.push_back(i);\n            if (i != n / i) divisors.push_back(n / i);\n        }\n    }\n    sort(divisors.begin(), divisors.end());\n    for (int d : divisors) cout << d << " ";\n}`,
          dryRun: 'n=36: i=1 → {1,36}. i=2 → {2,18}. i=3 → {3,12}. i=4 → {4,9}. i=6 → {6} (6=36/6). Sort: 1 2 3 4 6 9 12 18 36.',
        },
      ],
      hints: [
        'Check only up to √n — divisors come in pairs (i, n/i).',
        'If i divides n, both i and n/i are divisors.',
        'Sort at the end for sorted output.',
      ],
      solution: `void printDivisors(int n) {\n    vector<int> divs;\n    for (int i = 1; i * i <= n; i++) {\n        if (n % i == 0) {\n            divs.push_back(i);\n            if (i != n / i) divs.push_back(n / i);\n        }\n    }\n    sort(divs.begin(), divs.end());\n    for (int d : divs) cout << d << " ";\n}`,
      keyTakeaways: ['Always iterate up to √n for divisor problems. O(√n) vs O(n) makes a huge difference for large inputs.'],
    },
    {
      id: 'check-prime',
      slug: 'check-prime',
      title: 'Check for Prime Number',
      type: 'problem',
      difficulty: 'easy',
      pattern: 'Mathematical',
      conceptsRequired: ['Square root optimization', 'Divisors'],
      problemStatement: 'Given a positive integer N, determine whether it is prime (divisible only by 1 and itself).',
      examples: [
        { input: '7', output: 'true' },
        { input: '12', output: 'false', explanation: '12 = 2×6 = 3×4.' },
        { input: '2', output: 'true', explanation: '2 is the only even prime.' },
        { input: '1', output: 'false', explanation: '1 is not prime by definition.' },
      ],
      theory: `**Why check only up to √n?** If n has a factor > √n, it must also have a corresponding factor < √n. So if we find no factors up to √n, there are none at all.\n\n**Additional optimization:** After checking 2, check only odd numbers (i += 2). All even numbers > 2 are composite.`,
      approaches: [
        {
          name: 'Brute Force O(N)',
          intuition: 'Check all numbers from 2 to N-1.',
          steps: ['For i from 2 to n-1: if n%i==0, not prime'],
          complexity: { time: 'O(N)', space: 'O(1)' },
          code: `bool isPrime(int n) {\n    if (n <= 1) return false;\n    for (int i = 2; i < n; i++) {\n        if (n % i == 0) return false;\n    }\n    return true;\n}`,
        },
        {
          name: 'Optimal O(√N)',
          intuition: 'Only check up to √n since divisors come in pairs.',
          steps: ['Handle n <= 1 (false), n == 2 (true)', 'If n even and n > 2 (false)', 'Check odd i from 3 to √n'],
          complexity: { time: 'O(√N)', space: 'O(1)' },
          code: `bool isPrime(int n) {\n    if (n <= 1) return false;\n    if (n == 2) return true;\n    if (n % 2 == 0) return false;       // even, not 2\n    for (int i = 3; i * i <= n; i += 2) { // odd only\n        if (n % i == 0) return false;\n    }\n    return true;\n}`,
          dryRun: 'n=29: not even. i=3: 29%3≠0. i=5: 29%5≠0. i=7: 7²=49>29. Stop. Return true.',
        },
      ],
      hints: [
        'No need to check beyond √n — if no factor found by then, n is prime.',
        'Handle edge cases: 1 is not prime, 2 is prime, even numbers > 2 are not prime.',
        'Optimize: check only odd numbers after 2 (i += 2).',
      ],
      solution: `bool isPrime(int n) {\n    if (n <= 1) return false;\n    if (n == 2) return true;\n    if (n % 2 == 0) return false;\n    for (int i = 3; i * i <= n; i += 2) {\n        if (n % i == 0) return false;\n    }\n    return true;\n}`,
      keyTakeaways: [
        'Check only up to √n: O(√n) is much better than O(n) for large primes.',
        '1 is NOT prime. 2 is the only even prime.',
        'After checking 2, only check odd numbers (i += 2).',
      ],
    },
  ],
};
