import type { DSASection } from '@/types/dsa';

export const sortingSection: DSASection = {
  id: 'sorting',
  slug: 'sorting',
  title: 'Learn Important Sorting Techniques',
  description: 'Master all major sorting algorithms: selection, bubble, insertion, merge, and quicksort. Understand their time/space complexities.',
  icon: '↕️',
  color: 'from-violet-500 to-purple-600',
  subsections: [
    {
      id: 'sorting-1',
      title: 'Sorting I — Basic Sorts',
      topics: [
        {
          id: 'selection-sort',
          slug: 'selection-sort',
          title: 'Selection Sort',
          type: 'lesson',
          difficulty: 'easy',
          introduction: `Selection sort repeatedly finds the minimum element from the unsorted portion and places it at the beginning. It is intuitive but inefficient for large datasets.`,
          theory: `**Idea:** Divide the array into sorted (left) and unsorted (right) portions. In each pass, find the minimum of the unsorted portion and swap it to the beginning of the unsorted portion.\n\n**When to use:** Only when memory writes are expensive (selection sort does at most N swaps). Never in practice.`,
          complexity: { time: 'O(N²)', space: 'O(1)', best: 'O(N²)', average: 'O(N²)', worst: 'O(N²)', note: 'Always O(N²) — no early exit. Not stable.' },
          codeExamples: [
            {
              title: 'Selection Sort',
              language: 'cpp',
              code: `void selectionSort(vector<int>& arr) {\n    int n = arr.size();\n    for (int i = 0; i < n - 1; i++) {\n        int minIdx = i;  // assume current is min\n        for (int j = i + 1; j < n; j++) {\n            if (arr[j] < arr[minIdx]) minIdx = j;\n        }\n        swap(arr[i], arr[minIdx]);\n    }\n}`,
              explanation: 'Each outer iteration finds the minimum of arr[i..n-1] and swaps it to position i.',
            },
          ],
          revisionNotes: ['Always O(N²). At most N swaps (good if write is expensive). Not stable.'],
          keyTakeaways: ['Selection sort: find min, swap to front. O(N²) always.'],
        },
        {
          id: 'bubble-sort',
          slug: 'bubble-sort',
          title: 'Bubble Sort',
          type: 'lesson',
          difficulty: 'easy',
          introduction: `Bubble sort repeatedly steps through the list, compares adjacent elements and swaps them if they are in the wrong order. Larger elements "bubble up" to the end.`,
          theory: `**Idea:** In each pass, compare adjacent pairs. The largest unsorted element reaches its correct position at the end.\n\n**Optimization:** If no swaps occur in a pass, the array is sorted — break early. This makes best case O(N) for already sorted arrays.`,
          complexity: { time: 'O(N²)', space: 'O(1)', best: 'O(N) — already sorted with optimization', average: 'O(N²)', worst: 'O(N²)', note: 'Stable sort.' },
          codeExamples: [
            {
              title: 'Bubble Sort with early exit',
              language: 'cpp',
              code: `void bubbleSort(vector<int>& arr) {\n    int n = arr.size();\n    for (int i = 0; i < n - 1; i++) {\n        bool swapped = false;\n        for (int j = 0; j < n - i - 1; j++) {\n            if (arr[j] > arr[j + 1]) {\n                swap(arr[j], arr[j + 1]);\n                swapped = true;\n            }\n        }\n        if (!swapped) break;  // sorted early\n    }\n}`,
            },
          ],
          revisionNotes: ['Best O(N) if already sorted. Add swapped flag for optimization. Stable.'],
          keyTakeaways: ['Bubble sort: adjacent swaps. Add "swapped" flag for O(N) best case.'],
        },
        {
          id: 'insertion-sort',
          slug: 'insertion-sort',
          title: 'Insertion Sort',
          type: 'lesson',
          difficulty: 'easy',
          introduction: `Insertion sort builds the sorted array one element at a time by inserting each element into its correct position. Like sorting playing cards in hand.`,
          theory: `**Idea:** Maintain a sorted subarray on the left. For each new element, shift elements in the sorted portion to make room, then insert.\n\n**Used in practice:** For small arrays (n < 20), insertion sort beats quicksort because of lower overhead. Many library sorts use insertion sort for small subarrays.`,
          complexity: { time: 'O(N²)', space: 'O(1)', best: 'O(N) — already sorted', average: 'O(N²)', worst: 'O(N²)', note: 'Stable. Excellent for nearly sorted arrays and small n.' },
          codeExamples: [
            {
              title: 'Insertion Sort',
              language: 'cpp',
              code: `void insertionSort(vector<int>& arr) {\n    int n = arr.size();\n    for (int i = 1; i < n; i++) {\n        int key = arr[i];  // element to insert\n        int j = i - 1;\n        // shift elements greater than key to the right\n        while (j >= 0 && arr[j] > key) {\n            arr[j + 1] = arr[j];\n            j--;\n        }\n        arr[j + 1] = key;  // place key in correct position\n    }\n}`,
            },
          ],
          revisionNotes: ['Best O(N) for nearly sorted. Stable. Used for small sub-arrays in practice.'],
          keyTakeaways: ['Insertion sort: pick element, shift larger ones right, insert. Great for small/nearly-sorted arrays.'],
        },
      ],
    },
    {
      id: 'sorting-2',
      title: 'Sorting II — Efficient Sorts',
      topics: [
        {
          id: 'merge-sort',
          slug: 'merge-sort',
          title: 'Merge Sort',
          type: 'lesson',
          difficulty: 'medium',
          introduction: `Merge sort is a divide-and-conquer algorithm that divides the array in half, sorts each half recursively, and merges the sorted halves. It guarantees O(N log N) in all cases and is stable.`,
          theory: `**Divide:** Split array into two halves.\n**Conquer:** Recursively sort each half.\n**Merge:** Combine the two sorted halves into one sorted array.\n\n**Merge step:** Use two pointers on the two halves. At each step, pick the smaller element.\n\n**Why O(N log N)?** log N levels of recursion, each level does O(N) work in the merge step.\n\n**Key applications:**\n- Counting inversions (modified merge sort)\n- External sorting (when data doesn't fit in memory)\n- Sorting linked lists (preferred over quicksort for LL)`,
          complexity: { time: 'O(N log N)', space: 'O(N) — temporary array for merge', best: 'O(N log N)', average: 'O(N log N)', worst: 'O(N log N)', note: 'Stable. Preferred for linked lists.' },
          codeExamples: [
            {
              title: 'Merge Sort — Full Implementation',
              language: 'cpp',
              code: `void merge(vector<int>& arr, int left, int mid, int right) {\n    vector<int> temp;\n    int i = left, j = mid + 1;\n\n    while (i <= mid && j <= right) {\n        if (arr[i] <= arr[j]) temp.push_back(arr[i++]);\n        else temp.push_back(arr[j++]);\n    }\n    while (i <= mid) temp.push_back(arr[i++]);\n    while (j <= right) temp.push_back(arr[j++]);\n\n    for (int k = left; k <= right; k++) {\n        arr[k] = temp[k - left];\n    }\n}\n\nvoid mergeSort(vector<int>& arr, int left, int right) {\n    if (left >= right) return;  // base case: 0 or 1 element\n\n    int mid = left + (right - left) / 2;  // avoid overflow\n    mergeSort(arr, left, mid);    // sort left half\n    mergeSort(arr, mid + 1, right); // sort right half\n    merge(arr, left, mid, right); // merge sorted halves\n}\n\n// Call: mergeSort(arr, 0, arr.size()-1);`,
              dryRun: '[3,1,4,1,5,9]: divide to [3,1,4] and [1,5,9]. [3,1,4]→[1,3,4]. [1,5,9]→[1,5,9]. Merge: [1,1,3,4,5,9].',
            },
          ],
          revisionNotes: ['Always O(N log N). Stable. Extra O(N) space. Good for LL and counting inversions.'],
          keyTakeaways: ['Merge sort: divide in half, sort recursively, merge. Always O(N log N), requires O(N) extra space.'],
          interviewQuestions: [
            {
              question: 'Why is merge sort preferred for linked lists over quicksort?',
              answer: 'For linked lists, merge sort requires no random access — it can split the list by traversal and merge by pointer manipulation. Quicksort requires random access for efficient pivot selection and swapping, making it poorly suited for linked lists. Also, merge sort is stable.',
              difficulty: 'medium',
            },
          ],
        },
        {
          id: 'recursive-bubble-sort',
          slug: 'recursive-bubble-sort',
          title: 'Recursive Bubble Sort',
          type: 'problem',
          difficulty: 'easy',
          pattern: 'Recursion',
          problemStatement: 'Implement bubble sort recursively without using any loop.',
          approaches: [
            {
              name: 'Recursive',
              intuition: 'One pass of bubble sort = one call. After a pass, largest is at end. Recurse on n-1 elements.',
              steps: ['Base: n=1, return', 'One pass: bubble largest to end', 'Recurse on first n-1 elements'],
              complexity: { time: 'O(N²)', space: 'O(N)' },
              code: `void bubbleSortRec(vector<int>& arr, int n) {\n    if (n == 1) return;\n    for (int i = 0; i < n - 1; i++) {\n        if (arr[i] > arr[i+1]) swap(arr[i], arr[i+1]);\n    }\n    bubbleSortRec(arr, n - 1);\n}`,
            },
          ],
          hints: ['After one pass, the largest element is at position n-1.', 'Recurse with n-1 to sort the remaining elements.'],
          solution: `void bubbleSortRec(vector<int>& arr, int n) {\n    if (n == 1) return;\n    for (int i = 0; i < n-1; i++) if(arr[i]>arr[i+1]) swap(arr[i],arr[i+1]);\n    bubbleSortRec(arr, n-1);\n}`,
          keyTakeaways: ['Recursive sorts demonstrate how iterative algorithms can be expressed recursively.'],
        },
        {
          id: 'recursive-insertion-sort',
          slug: 'recursive-insertion-sort',
          title: 'Recursive Insertion Sort',
          type: 'problem',
          difficulty: 'easy',
          pattern: 'Recursion',
          problemStatement: 'Implement insertion sort recursively.',
          approaches: [
            {
              name: 'Recursive',
              intuition: 'Sort first n-1 elements, then insert element at position n-1 into its correct place.',
              steps: ['Base: n=1, return', 'Sort first n-1 elements recursively', 'Insert arr[n-1] into sorted arr[0..n-2]'],
              complexity: { time: 'O(N²)', space: 'O(N)' },
              code: `void insertionSortRec(vector<int>& arr, int n) {\n    if (n <= 1) return;\n    insertionSortRec(arr, n - 1);  // sort first n-1\n    // Insert last element into sorted portion\n    int last = arr[n-1], j = n-2;\n    while (j >= 0 && arr[j] > last) {\n        arr[j+1] = arr[j]; j--;\n    }\n    arr[j+1] = last;\n}`,
            },
          ],
          hints: ['Sort first n-1 elements, then insert the n-th into its correct position.'],
          solution: `void insertionSortRec(vector<int>& arr, int n) {\n    if (n <= 1) return;\n    insertionSortRec(arr, n-1);\n    int last = arr[n-1], j = n-2;\n    while (j >= 0 && arr[j] > last) { arr[j+1] = arr[j]; j--; }\n    arr[j+1] = last;\n}`,
          keyTakeaways: [],
        },
        {
          id: 'quick-sort',
          slug: 'quick-sort',
          title: 'Quick Sort',
          type: 'lesson',
          difficulty: 'easy',
          introduction: `Quick sort is the fastest practical sorting algorithm in most real-world scenarios. It divides the array around a pivot element and sorts the sub-arrays recursively. Average O(N log N), but worst case O(N²) — which is rare with good pivot selection.`,
          theory: `**Idea:** Pick a pivot. Partition the array so all elements < pivot are to its left and all > pivot are to its right. Recursively sort both sides.\n\n**Partition (Lomuto scheme):** Use the last element as pivot. Maintain a boundary j — elements before j+1 are ≤ pivot.\n\n**Partition (Hoare scheme):** Use two pointers from both ends. Generally performs fewer swaps.\n\n**Pivot selection strategies:**\n- Last element: simple but O(N²) on sorted arrays\n- Random pivot: expected O(N log N) always (recommended)\n- Median of three: good in practice`,
          complexity: { time: 'O(N log N) average', space: 'O(log N) — recursion stack', best: 'O(N log N)', average: 'O(N log N)', worst: 'O(N²) — already sorted with bad pivot', note: 'NOT stable. Use random pivot to avoid worst case.' },
          codeExamples: [
            {
              title: 'Quick Sort (Lomuto partition)',
              language: 'cpp',
              code: `int partition(vector<int>& arr, int low, int high) {\n    int pivot = arr[high];  // last element as pivot\n    int i = low - 1;       // boundary of smaller elements\n\n    for (int j = low; j < high; j++) {\n        if (arr[j] <= pivot) {\n            i++;\n            swap(arr[i], arr[j]);\n        }\n    }\n    swap(arr[i + 1], arr[high]);  // place pivot correctly\n    return i + 1;                  // pivot's final position\n}\n\nvoid quickSort(vector<int>& arr, int low, int high) {\n    if (low < high) {\n        int pi = partition(arr, low, high);  // pivot index\n        quickSort(arr, low, pi - 1);         // sort left\n        quickSort(arr, pi + 1, high);        // sort right\n    }\n}\n\n// Randomized pivot (recommended)\nint partitionRandom(vector<int>& arr, int low, int high) {\n    int randIdx = low + rand() % (high - low + 1);\n    swap(arr[randIdx], arr[high]);  // move random to end\n    return partition(arr, low, high);\n}`,
              dryRun: '[3,1,4,1,5]: pivot=5, no swaps, pivot stays at end. Left=[3,1,4,1]. Recurse. Eventually sorted.',
            },
          ],
          revisionNotes: ['Quick sort is fastest in practice (cache-friendly). Use random pivot for worst-case avoidance.', 'Not stable. O(log N) stack space average.'],
          interviewQuestions: [
            {
              question: 'Why is quicksort generally faster than merge sort even though both are O(N log N)?',
              answer: 'Quicksort is cache-friendly — it operates in-place without extra arrays, so data stays in CPU cache. Merge sort requires an O(N) temp array, causing cache misses. The constant factor in quicksort is much lower. However, quicksort has O(N²) worst case and is not stable.',
              difficulty: 'medium',
            },
          ],
          keyTakeaways: ['Quick sort is fastest in practice. Always use random pivot to avoid O(N²) worst case. Not stable.'],
        },
      ],
    },
  ],
};
