import type { DSASection } from '@/types/dsa';

export const bitManipulationSection: DSASection = {
  id: 'bit-manipulation',
  slug: 'bit-manipulation',
  title: 'Bit Manipulation [Concepts & Problems]',
  description: 'Master bitwise operations — AND, OR, XOR, shifts — and solve classic problems in O(1) using bit tricks.',
  icon: '⊕',
  color: 'from-amber-500 to-yellow-600',
  subsections: [
    {
      id: 'bit-learn',
      title: 'Learn Bit Manipulation',
      topics: [
        { id: 'bits-intro', slug: 'bits-intro', title: 'Introduction to Bits and Tricks', type: 'lesson', difficulty: 'easy',
          introduction: 'Bit manipulation uses binary representation and bitwise operators to solve problems in O(1) time and O(1) space — impossible with arithmetic operations alone.',
          theory: `**Bitwise Operators:**\n- AND (&): 1&1=1, else 0\n- OR (|): 0|0=0, else 1\n- XOR (^): same=0, different=1\n- NOT (~): flips all bits\n- Left shift (<<): x<<k = x * 2^k\n- Right shift (>>): x>>k = x / 2^k\n\n**Key Bit Tricks:**\n- Get ith bit: (n >> i) & 1\n- Set ith bit: n | (1 << i)\n- Clear ith bit: n & ~(1 << i)\n- Toggle ith bit: n ^ (1 << i)\n- Check odd: n & 1\n- Check power of 2: n & (n-1) == 0\n- Remove rightmost set bit: n & (n-1)\n- Get rightmost set bit: n & (-n)\n- XOR same values cancel: a ^ a = 0\n- XOR with 0 is identity: a ^ 0 = a`,
          codeExamples: [{ title: 'Bit tricks cheatsheet', language: 'cpp', code: `int n = 13; // 1101 in binary\n\n// Get 2nd bit (0-indexed)\ncout << ((n >> 2) & 1) << "\\n";  // 1\n\n// Set 1st bit\ncout << (n | (1 << 1)) << "\\n"; // 15 (1111)\n\n// Clear 3rd bit\ncout << (n & ~(1 << 3)) << "\\n"; // 5 (0101)\n\n// Toggle 2nd bit\ncout << (n ^ (1 << 2)) << "\\n"; // 9 (1001)\n\n// Count set bits (built-in)\ncout << __builtin_popcount(n) << "\\n"; // 3\n\n// Remove rightmost set bit\ncout << (n & (n-1)) << "\\n"; // 12 (1100)` }],
          revisionNotes: ['n&1: odd check. n&(n-1): remove rightmost 1. n&(-n): isolate rightmost 1.', '__builtin_popcount(n): count set bits in O(1).'],
          keyTakeaways: ['Bit tricks: O(1) operations. Must know for interviews.'] },
        { id: 'check-ith-bit', slug: 'check-ith-bit', title: 'Check if the i-th bit is Set', type: 'problem', difficulty: 'easy', pattern: 'Bit Manipulation',
          problemStatement: 'Given N and i, check if the i-th bit (0-indexed from right) is set in N.',
          examples: [{ input: 'N=13 (1101), i=2', output: 'true', explanation: '3rd bit (index 2) is 1.' }],
          approaches: [{ name: 'Right shift + AND', intuition: 'Shift N right by i positions, check if LSB is 1.', steps: ['(N >> i) & 1'], complexity: { time: 'O(1)', space: 'O(1)' }, code: `bool isSet(int n, int i) { return (n >> i) & 1; }` }],
          hints: ['Shift right by i to bring ith bit to position 0.', 'AND with 1 to check if LSB is set.', 'Returns 1 if set, 0 if not.'],
          solution: `bool isSet(int n, int i) { return (n >> i) & 1; }`, keyTakeaways: ['(n >> i) & 1 — get the ith bit.'] },
        { id: 'check-odd', slug: 'check-odd', title: 'Check if a Number is Odd', type: 'problem', difficulty: 'easy', pattern: 'Bit Manipulation',
          problemStatement: 'Check if a number is odd using bitwise operations.',
          examples: [{ input: 'N=7', output: 'odd' }, { input: 'N=4', output: 'even' }],
          approaches: [{ name: 'AND with 1', intuition: 'LSB is 1 for odd, 0 for even.', steps: ['n & 1 == 1 → odd'], complexity: { time: 'O(1)', space: 'O(1)' }, code: `bool isOdd(int n) { return n & 1; }` }],
          hints: ['LSB (last bit) = 1 means odd.', 'n & 1 checks the last bit.', 'Equivalent to n % 2 but faster.'],
          solution: `bool isOdd(int n) { return n & 1; }`, keyTakeaways: ['n & 1 is faster than n % 2 for odd/even check.'] },
        { id: 'check-power-of-2', slug: 'check-power-of-2', title: 'Check if a Number is Power of 2', type: 'problem', difficulty: 'easy', pattern: 'Bit Manipulation',
          problemStatement: 'Check if N is a power of 2 using O(1) bit trick.',
          examples: [{ input: 'N=16', output: 'true' }, { input: 'N=18', output: 'false' }],
          approaches: [{ name: 'n & (n-1)', intuition: 'Powers of 2 have exactly one bit set. n-1 flips all bits from that point. n & (n-1) == 0 only for powers of 2.', steps: ['n > 0 AND n & (n-1) == 0'], complexity: { time: 'O(1)', space: 'O(1)' }, code: `bool isPow2(int n) { return n > 0 && (n & (n-1)) == 0; }` }],
          hints: ['Powers of 2 have exactly 1 set bit.', 'n & (n-1) removes the rightmost set bit.', 'If result is 0, only one bit was set.'],
          solution: `bool isPow2(int n) { return n > 0 && (n & (n-1)) == 0; }`, leetcodeUrl: 'https://leetcode.com/problems/power-of-two/', keyTakeaways: ['n & (n-1) == 0: power of 2 check. Must know.'] },
        { id: 'count-set-bits', slug: 'count-set-bits', title: 'Count the Number of Set Bits', type: 'problem', difficulty: 'easy', pattern: 'Bit Manipulation',
          problemStatement: 'Count the number of 1-bits in the binary representation of N (Brian Kernighan\'s algorithm).',
          examples: [{ input: 'N=13 (1101)', output: '3' }],
          approaches: [{ name: 'Brian Kernighan', intuition: 'n & (n-1) removes the lowest set bit. Count iterations until n becomes 0.', steps: ['While n > 0: increment count, n = n & (n-1)'], complexity: { time: 'O(number of set bits)', space: 'O(1)' }, code: `int countBits(int n) {\n    int count = 0;\n    while (n) { n &= n - 1; count++; }\n    return count;\n}\n// Or use built-in: __builtin_popcount(n)` }],
          hints: ['n & (n-1) removes the rightmost set bit.', 'Count how many times you can do this before n becomes 0.', 'Built-in: __builtin_popcount(n).'],
          solution: `int countBits(int n){int c=0;while(n){n&=n-1;c++;}return c;}`, leetcodeUrl: 'https://leetcode.com/problems/number-of-1-bits/', keyTakeaways: ['Brian Kernighan: n &= n-1 removes lowest set bit. O(set bits) per call.'] },
        { id: 'set-unset-rightmost', slug: 'set-unset-rightmost', title: 'Set/Unset the Rightmost Unset Bit', type: 'lesson', difficulty: 'easy',
          introduction: 'Common bit manipulation operations on the rightmost unset (0) bit.',
          theory: `**Set rightmost 0-bit:** n | (n+1)\n**Unset rightmost 1-bit:** n & (n-1)\n**Get rightmost 1-bit:** n & (-n) = n & (~n+1)\n**Toggle rightmost 0-bit:** n ^ (n+1)`,
          codeExamples: [{ title: 'Rightmost bit operations', language: 'cpp', code: `int n = 10; // 1010\ncout << (n | (n+1)) << "\\n";  // 11 (1011) - set rightmost 0\ncout << (n & (n-1)) << "\\n"; // 8 (1000) - clear rightmost 1\ncout << (n & (-n)) << "\\n";  // 2 (0010) - isolate rightmost 1` }],
          keyTakeaways: ['n & (n-1): clear rightmost 1. n | (n+1): set rightmost 0. n & (-n): isolate rightmost 1.'] },
        { id: 'swap-two-numbers', slug: 'swap-two-numbers', title: 'Swap Two Numbers without Temp', type: 'problem', difficulty: 'easy', pattern: 'Bit Manipulation',
          problemStatement: 'Swap two integers without using a temporary variable, using XOR.',
          examples: [{ input: 'a=5, b=3', output: 'a=3, b=5' }],
          approaches: [{ name: 'XOR swap', intuition: 'a^b^b = a and a^a^b = b. XOR with both values exchanges them.', steps: ['a = a ^ b', 'b = a ^ b (now b = original a)', 'a = a ^ b (now a = original b)'], complexity: { time: 'O(1)', space: 'O(1)' }, code: `void swap(int& a, int& b) {\n    a ^= b;\n    b ^= a; // b = original a\n    a ^= b; // a = original b\n}` }],
          hints: ['XOR property: a^a=0 and a^0=a.', 'a^b^b=a, so XOR with same value twice cancels out.', 'Does not work if a and b point to the same memory.'],
          solution: `void swap(int&a,int&b){a^=b;b^=a;a^=b;}`, keyTakeaways: ['XOR swap: a^=b; b^=a; a^=b. Caution: fails if a and b are same variable.'] },
        { id: 'divide-without-multiplication', slug: 'divide-without-multiplication', title: 'Divide Two Numbers without * and /', type: 'problem', difficulty: 'medium', pattern: 'Bit Manipulation',
          problemStatement: 'Divide two integers dividend/divisor without using * or /. Return the quotient truncated toward zero.',
          examples: [{ input: 'dividend=10, divisor=3', output: '3' }],
          approaches: [{ name: 'Bit shift subtraction', intuition: 'Double the divisor using left shift until it exceeds dividend. Subtract and record power of 2.', steps: ['While dividend >= divisor', 'Find largest k: divisor * 2^k <= dividend', 'Subtract divisor * 2^k, add 2^k to quotient'], complexity: { time: 'O(log N)', space: 'O(1)' }, code: `int divide(int dividend, int divisor) {\n    if (dividend == INT_MIN && divisor == -1) return INT_MAX;\n    long long a = abs((long long)dividend), b = abs((long long)divisor);\n    int sign = (dividend > 0) == (divisor > 0) ? 1 : -1;\n    long long quotient = 0;\n    while (a >= b) {\n        long long temp = b, mult = 1;\n        while (a >= (temp << 1)) { temp <<= 1; mult <<= 1; }\n        a -= temp; quotient += mult;\n    }\n    return sign * quotient;\n}` }],
          hints: ['Use left shifts to double the divisor repeatedly.', 'Find the largest power of 2 such that divisor * 2^k <= dividend.', 'Handle overflow: dividend=INT_MIN, divisor=-1.'],
          solution: `// See above`, leetcodeUrl: 'https://leetcode.com/problems/divide-two-integers/', keyTakeaways: ['Division using bit shifts: subtract the largest multiple of divisor (power of 2) at each step.'] },
      ],
    },
    {
      id: 'bit-interview',
      title: 'Interview Problems',
      topics: [
        { id: 'min-bit-flips', slug: 'min-bit-flips', title: 'Minimum Bit Flips to Convert Number', type: 'problem', difficulty: 'medium', pattern: 'Bit Manipulation',
          problemStatement: 'Return the minimum number of bit flips to convert start to goal.',
          examples: [{ input: 'start=10 (1010), goal=7 (0111)', output: '3' }],
          approaches: [{ name: 'XOR + count bits', intuition: 'XOR of start and goal has 1s at positions where bits differ. Count those 1s.', steps: ['Compute xor = start ^ goal', 'Count set bits in xor'], complexity: { time: 'O(1)', space: 'O(1)' }, code: `int minBitFlips(int start, int goal) {\n    return __builtin_popcount(start ^ goal);\n}` }],
          hints: ['XOR gives 1 where bits differ.', 'Count set bits of (start XOR goal).', '__builtin_popcount counts set bits.'],
          solution: `int minBitFlips(int s, int g){return __builtin_popcount(s^g);}`, leetcodeUrl: 'https://leetcode.com/problems/minimum-bit-flips-to-convert-number/', keyTakeaways: ['XOR then count set bits — elegant O(1) solution.'] },
        { id: 'single-number-1', slug: 'single-number-1', title: 'Single Number I', type: 'problem', difficulty: 'medium', pattern: 'XOR',
          problemStatement: 'Every element appears twice except one. Find that element in O(N) time, O(1) space.',
          examples: [{ input: '[4,1,2,1,2]', output: '4' }],
          approaches: [{ name: 'XOR all elements', intuition: 'XOR of same values = 0. XOR of all pairs cancels. Remaining is the single number.', steps: ['XOR all elements together', 'Pairs cancel (a^a=0), single survives (x^0=x)'], complexity: { time: 'O(N)', space: 'O(1)' }, code: `int singleNumber(vector<int>& nums) {\n    int result = 0;\n    for (int n : nums) result ^= n;\n    return result;\n}` }],
          hints: ['XOR of two equal numbers is 0.', 'XOR all elements — pairs cancel out.', 'The remaining value is the single number.'],
          solution: `int singleNumber(vector<int>&n){int r=0;for(int x:n)r^=x;return r;}`, leetcodeUrl: 'https://leetcode.com/problems/single-number/', keyTakeaways: ['XOR trick: a^a=0, a^0=a. XOR all → pairs cancel, single survives.'] },
        { id: 'power-set-bits', slug: 'power-set-bits', title: 'Power Set using Bit Manipulation', type: 'problem', difficulty: 'medium', pattern: 'Bit Manipulation',
          problemStatement: 'Generate all subsets of an array using bit masking.',
          examples: [{ input: '[1,2,3]', output: '[[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]' }],
          approaches: [{ name: 'Bitmask iteration', intuition: 'For n elements, iterate from 0 to 2^n-1. Each bit in mask represents inclusion of an element.', steps: ['For mask 0 to 2^n-1', 'Bit i set → include element i'], complexity: { time: 'O(N * 2^N)', space: 'O(N * 2^N)' }, code: `for (int mask = 0; mask < (1 << n); mask++) {\n    vector<int> subset;\n    for (int i = 0; i < n; i++)\n        if (mask & (1 << i)) subset.push_back(arr[i]);\n    result.push_back(subset);\n}` }],
          hints: ['2^n subsets for n elements.', 'Mask from 0 to 2^n - 1.', 'Bit i set in mask → include element i.'],
          solution: `for(int m=0;m<(1<<n);m++){vector<int>s;for(int i=0;i<n;i++)if(m&(1<<i))s.push_back(a[i]);r.push_back(s);}`, keyTakeaways: ['Bitmask = compact representation of subset. 2^n masks = 2^n subsets.'] },
        { id: 'xor-range', slug: 'xor-range', title: 'XOR of Numbers in Given Range', type: 'problem', difficulty: 'medium', pattern: 'Bit Manipulation',
          problemStatement: 'Find XOR of all numbers from L to R efficiently.',
          examples: [{ input: 'L=2, R=5', output: '2^3^4^5 = 0 ^ 4 = 1', explanation: '2^3=1, 1^4=5, 5^5=0... actually 2^3^4^5 = 0' }],
          approaches: [{ name: 'XOR 1..n formula', intuition: 'XOR(1 to n) has a pattern: n%4=0→n, n%4=1→1, n%4=2→n+1, n%4=3→0. XOR(L..R) = XOR(1..R) ^ XOR(1..L-1).', steps: ['Compute xorN(n) using the pattern', 'Return xorN(R) ^ xorN(L-1)'], complexity: { time: 'O(1)', space: 'O(1)' }, code: `int xorN(int n) {\n    switch (n % 4) {\n        case 0: return n;\n        case 1: return 1;\n        case 2: return n + 1;\n        case 3: return 0;\n    }\n    return 0;\n}\nint xorRange(int L, int R) {\n    return xorN(R) ^ xorN(L - 1);\n}` }],
          hints: ['XOR(1..n) has a 4-cycle pattern based on n%4.', 'XOR(L..R) = XOR(1..R) XOR XOR(1..L-1).', 'The pattern: n%4==0→n, 1→1, 2→n+1, 3→0.'],
          solution: `int xorN(int n){switch(n%4){case 0:return n;case 1:return 1;case 2:return n+1;case 3:return 0;}return 0;}\nint xorRange(int L,int R){return xorN(R)^xorN(L-1);}`, keyTakeaways: ['XOR(1..n) has O(1) formula using n%4 pattern.'] },
        { id: 'single-number-3', slug: 'single-number-3', title: 'Single Number III', type: 'problem', difficulty: 'medium', pattern: 'Bit Manipulation',
          problemStatement: 'Two elements appear once, all others twice. Find both unique elements in O(N) time, O(1) space.',
          examples: [{ input: '[1,2,1,3,2,5]', output: '[3,5]' }],
          approaches: [{ name: 'XOR + bit split', intuition: 'XOR all to get x^y. Find any set bit (they differ there). Use that bit to split into two groups — each containing exactly one unique number.', steps: ['XOR all → result = x ^ y', 'Find rightmost set bit of result', 'Split array by that bit, XOR each group separately', 'Each group gives one unique number'], complexity: { time: 'O(N)', space: 'O(1)' }, code: `vector<int> singleNumberIII(vector<int>& nums) {\n    int xorAll = 0;\n    for (int n : nums) xorAll ^= n; // x ^ y\n    int diffBit = xorAll & (-xorAll); // rightmost set bit\n    int a = 0, b = 0;\n    for (int n : nums) {\n        if (n & diffBit) a ^= n; // group 1\n        else b ^= n;              // group 2\n    }\n    return {a, b};\n}` }],
          hints: ['XOR all → x^y (the two unique numbers).', 'Find a bit where x and y differ (rightmost set bit of x^y).', 'Split by that bit — each group has exactly one unique number.'],
          solution: `vector<int> f(vector<int>&n){int x=0;for(int v:n)x^=v;int b=x&(-x);int a=0,c=0;for(int v:n){if(v&b)a^=v;else c^=v;}return{a,c};}`, leetcodeUrl: 'https://leetcode.com/problems/single-number-iii/', keyTakeaways: ['Two unique numbers: XOR all, find differing bit, split and XOR each group.'] },
      ],
    },
    {
      id: 'bit-advanced-maths',
      title: 'Advanced Maths',
      topics: [
        { id: 'print-prime-factors', slug: 'print-prime-factors', title: 'Print Prime Factors of a Number', type: 'problem', difficulty: 'hard', pattern: 'Mathematical',
          problemStatement: 'Print all prime factors of N (with repetition).',
          examples: [{ input: 'N=12', output: '2 2 3', explanation: '12 = 2*2*3' }],
          approaches: [{ name: 'Trial division', intuition: 'Divide by 2, then odd numbers up to √n. Any remaining factor > √n is prime.', steps: ['Divide by 2 while possible', 'Divide by odd i from 3 to √n', 'If n > 1, n itself is prime'], complexity: { time: 'O(√N)', space: 'O(1)' }, code: `void primeFactors(int n) {\n    while (n % 2 == 0) { cout << 2 << " "; n /= 2; }\n    for (int i = 3; i * i <= n; i += 2) {\n        while (n % i == 0) { cout << i << " "; n /= i; }\n    }\n    if (n > 1) cout << n; // remaining prime factor\n}` }],
          hints: ['Divide by 2 first (handles all even factors).', 'Then try odd divisors 3, 5, 7... up to √n.', 'If n > 1 after the loop, it\'s a prime factor.'],
          solution: `void pf(int n){while(n%2==0){cout<<2<<" ";n/=2;}for(int i=3;i*i<=n;i+=2)while(n%i==0){cout<<i<<" ";n/=i;}if(n>1)cout<<n;}`, keyTakeaways: ['Prime factorization in O(√N): divide by 2, then odd numbers.'] },
        { id: 'count-primes-range', slug: 'count-primes-range', title: 'Count Primes in Range L to R (Sieve)', type: 'problem', difficulty: 'hard', pattern: 'Sieve of Eratosthenes',
          problemStatement: 'Count prime numbers in range [L, R]. Use Sieve of Eratosthenes for efficient precomputation.',
          examples: [{ input: 'L=1, R=20', output: '8', explanation: '2,3,5,7,11,13,17,19 are prime.' }],
          approaches: [{ name: 'Sieve of Eratosthenes', intuition: 'Mark all composites. Start with 2, mark all multiples as composite. Remaining unmarked are prime.', steps: ['Create boolean array size R+1, all true', 'Mark 0 and 1 as not prime', 'For i from 2 to √R: if prime, mark all multiples of i', 'Count primes from L to R'], complexity: { time: 'O(R log log R)', space: 'O(R)' }, code: `vector<bool> sieve(int R) {\n    vector<bool> isPrime(R + 1, true);\n    isPrime[0] = isPrime[1] = false;\n    for (int i = 2; i * i <= R; i++) {\n        if (isPrime[i]) {\n            for (int j = i * i; j <= R; j += i) {\n                isPrime[j] = false;\n            }\n        }\n    }\n    return isPrime;\n}` }],
          hints: ['Sieve: mark all multiples of primes as composite.', 'Start marking from i*i (smaller multiples already marked).', 'O(N log log N) — extremely efficient.'],
          solution: `vector<bool> sieve(int R){vector<bool>p(R+1,true);p[0]=p[1]=false;for(int i=2;i*i<=R;i++)if(p[i])for(int j=i*i;j<=R;j+=i)p[j]=false;return p;}`, keyTakeaways: ['Sieve of Eratosthenes: O(N log log N) — best way to find all primes up to N.'] },
        { id: 'prime-factorisation-sieve', slug: 'prime-factorisation-sieve', title: 'Prime Factorisation using Smallest Prime Factor', type: 'problem', difficulty: 'hard', pattern: 'Sieve',
          problemStatement: 'Precompute smallest prime factor (SPF) for all numbers up to N, then factorize any number in O(log N).',
          examples: [{ input: 'N=12', output: '2^2 * 3^1' }],
          approaches: [{ name: 'SPF Sieve + factorization', intuition: 'Build SPF[i] = smallest prime factor of i. Then factorize n by dividing by SPF[n] repeatedly.', steps: ['Build SPF sieve: for each prime p, set SPF[multiples] = p', 'Factorize: while n>1, print SPF[n], divide n by SPF[n]'], complexity: { time: 'O(N log log N) precompute, O(log N) query', space: 'O(N)' }, code: `vector<int> spf(int N) {\n    vector<int> SPF(N + 1);\n    iota(SPF.begin(), SPF.end(), 0); // SPF[i] = i\n    for (int i = 2; i * i <= N; i++) {\n        if (SPF[i] == i) { // i is prime\n            for (int j = i * i; j <= N; j += i)\n                if (SPF[j] == j) SPF[j] = i;\n        }\n    }\n    return SPF;\n}\nvoid factorize(int n, vector<int>& SPF) {\n    while (n > 1) {\n        cout << SPF[n] << " ";\n        n /= SPF[n];\n    }\n}` }],
          hints: ['Build SPF[i] = smallest prime factor of i using sieve.', 'To factorize n: repeatedly divide by SPF[n].', 'Precomputation is O(N log log N), each query is O(log N).'],
          solution: `// SPF sieve + factorize as above`, keyTakeaways: ['SPF sieve enables O(log N) factorization after O(N log log N) precomputation.'] },
        { id: 'divisors-number', slug: 'divisors-number', title: 'All Divisors of a Number', type: 'problem', difficulty: 'easy', pattern: 'Mathematical',
          problemStatement: 'Find all divisors of N in sorted order efficiently.',
          examples: [{ input: 'N=12', output: '1 2 3 4 6 12' }],
          approaches: [{ name: 'O(√N) with sorting', intuition: 'Divisors come in pairs (i, n/i). Iterate to √n, collect both.', steps: ['For i from 1 to √n: if n%i==0, add i and n/i', 'Sort and print'], complexity: { time: 'O(√N + D log D) where D=divisor count', space: 'O(D)' }, code: `void divisors(int n) {\n    vector<int> d;\n    for (int i = 1; i * i <= n; i++)\n        if (n % i == 0) { d.push_back(i); if (i != n/i) d.push_back(n/i); }\n    sort(d.begin(), d.end());\n    for (int x : d) cout << x << " ";\n}` }],
          hints: ['Check up to √n only.', 'Each divisor i has a paired divisor n/i.', 'Sort for ordered output.'],
          solution: `void div(int n){vector<int>d;for(int i=1;i*i<=n;i++)if(n%i==0){d.push_back(i);if(i!=n/i)d.push_back(n/i);}sort(d.begin(),d.end());for(int x:d)cout<<x<<" ";}`, keyTakeaways: ['Always iterate to √n for divisors. O(√N) beats O(N).'] },
        { id: 'pow-x-n-bits', slug: 'pow-x-n-bits', title: 'Pow(x, n) — Iterative Fast Power', type: 'problem', difficulty: 'easy', pattern: 'Fast Exponentiation',
          problemStatement: 'Implement x^n iteratively using binary exponentiation (no recursion).',
          examples: [{ input: 'x=2, n=10', output: '1024' }],
          approaches: [{ name: 'Iterative binary exponentiation', intuition: 'Process bits of n from right. If bit is set, multiply result by current power of x. Square x for next bit.', steps: ['While n > 0: if n&1: result *= x', 'Square x, right-shift n'], complexity: { time: 'O(log N)', space: 'O(1)' }, code: `double fastPow(double x, long long n) {\n    if (n < 0) { x = 1.0 / x; n = -n; }\n    double result = 1.0;\n    while (n > 0) {\n        if (n & 1) result *= x;\n        x *= x;\n        n >>= 1;\n    }\n    return result;\n}` }],
          hints: ['Process binary representation of n bit by bit.', 'If current bit is 1, multiply result by current x.', 'Square x at each step for next power.'],
          solution: `double fastPow(double x,long long n){if(n<0){x=1.0/x;n=-n;}double r=1;while(n>0){if(n&1)r*=x;x*=x;n>>=1;}return r;}`, keyTakeaways: ['Iterative fast power: O(log N), O(1) space. More practical than recursive version.'] },
      ],
    },
  ],
};
