import type { DSASection } from '@/types/dsa';

export const slidingWindowSection: DSASection = {
  id: 'sliding-window', slug: 'sliding-window',
  title: 'Sliding Window & Two Pointer [Patterns]',
  description: 'Efficient O(N) solutions for subarray/substring problems using sliding window and two-pointer technique.',
  icon: '🪟', color: 'from-cyan-500 to-sky-600',
  subsections: [
    {
      id: 'sliding-window-theory', title: 'Theory',
      topics: [
        { id:'sliding-window-theory-lesson', slug:'sliding-window-theory-lesson', title:'Sliding Window & Two Pointer — Theory (Read This First)', type:'lesson', difficulty:'easy',
          introduction: `A **window** is a contiguous slice \`[left, right]\` of an array/string. "Sliding" it means moving \`left\`/\`right\` forward to expand or shrink the range, instead of recomputing everything from scratch for every possible window. It is a specialised **Two Pointer** technique where both pointers only ever move forward together, describing one contiguous range at all times. Why it exists: brute-forcing every (start, end) pair for a "longest/shortest contiguous subarray/substring satisfying X" question costs O(n^2) or worse; sliding window notices you don't need to recompute the whole window's sum/count from scratch each step — just remove what leaves and add what enters — turning it into O(n). Two Pointer more broadly (opposite-ends, not just windows) turns O(n^2) pair-search on sorted data into O(n). Real-world usage: rate limiters (requests in the last N seconds), streaming analytics (moving averages), and text search over a bounded window all use this exact idea.`,
          theory: `**Two Pointer — opposite ends (sorted array, pair-sum, palindrome):**\n\`\`\`cpp\nint left = 0, right = arr.size() - 1;\nwhile (left < right) {\n    if (/* sum too small */) left++;   // only moving left can increase the sum (array is sorted)\n    else right--;                       // only moving right can decrease it\n}\n\`\`\`\nThis only works because the array is sorted: moving \`left\` forward can only increase \`arr[left]\`, and moving \`right\` backward can only decrease \`arr[right]\` — that guarantee is what lets you skip checking every pair, turning O(n^2) into O(n).\n\n**Sliding Window — variable-size (the workhorse pattern):**\n\`\`\`cpp\nint left = 0, runningState = 0, best = 0;\nfor (int right = 0; right < arr.size(); right++) {\n    runningState += arr[right];                 // 1. expand: bring arr[right] INTO the window\n    while (/* window now invalid */) {\n        runningState -= arr[left];                // 2. shrink: remove arr[left] to fix it\n        left++;\n    }\n    best = max(best, right - left + 1);          // 3. window [left, right] is valid — record it\n}\n\`\`\`\n**Why is this O(n) and not O(n^2)** despite the nested while-inside-for? Because \`left\` only ever moves forward and can move at most n times **total across the entire run**, not per outer iteration — so total work across both loops combined is O(n) + O(n) = O(n). This "amortized" analysis is the key insight; don't be fooled by the nested-loop shape.\n\n**Syntax notes:**\n- \`right - left + 1\` is the window length ([left,right] inclusive) — the single most common off-by-one spot; verify against a 1-element window (left==right should give 1).\n- \`unordered_map<char,int> freq;\` / \`unordered_set<char> st;\` — track window contents; \`freq[s[left]]--; if (freq[s[left]]==0) freq.erase(s[left]);\` keeps the map exactly matching what's currently inside the window.\n- Use \`while\`, not \`if\`, for the shrink step whenever more than one shrink might be needed to restore validity.\n\n**Fixed-size window** (size k given directly): build the first window's sum, then for each new right, add the entering element and subtract the one leaving exactly k positions back — no inner while loop needed.\n\n**Requirement:** sliding window generally assumes non-negative values, so adding an element never decreases the running sum and removing one never increases it. With negative numbers present, sliding window usually does not directly apply — reach for prefix sum + hash map instead.`,
          codeExamples: [
            { title: 'Simple: fixed-size window sum', language: 'cpp', code: `int maxSumWindowK(vector<int>& arr, int k) {\n    int windowSum = 0;\n    for (int i = 0; i < k; i++) windowSum += arr[i];\n    int best = windowSum;\n    for (int right = k; right < arr.size(); right++) {\n        windowSum += arr[right];          // element entering\n        windowSum -= arr[right - k];       // element leaving\n        best = max(best, windowSum);\n    }\n    return best;\n}`, explanation: 'O(1) per step to slide the window instead of re-summing k elements each time.' },
            { title: 'Practical: longest substring without repeating characters', language: 'cpp', code: `int lengthOfLongestSubstring(string s) {\n    unordered_set<char> st;\n    int left = 0, ans = 0;\n    for (int right = 0; right < s.size(); right++) {\n        while (st.count(s[right])) { st.erase(s[left]); left++; }   // shrink until duplicate is gone\n        st.insert(s[right]);\n        ans = max(ans, right - left + 1);\n    }\n    return ans;\n}`, explanation: 'Variable-size window: expand right always, shrink left only when the window becomes invalid (a duplicate appears).', dryRun: 's="abba": r=0 "a" ans=1; r=1 "ab" ans=2; r=2 dup b -> erase a,l=1 still has b -> erase b,l=2, insert b, ans stays 2; r=3 "ba" ans stays 2 -> final 2' },
            { title: 'Industry-style: sliding rate limiter (requests per time window)', language: 'cpp', code: `// Same expand/shrink skeleton powers "max N requests per rolling W-second window" rate limiters\nbool allowRequest(deque<long long>& timestamps, long long now, int windowMs, int maxRequests) {\n    timestamps.push_back(now);\n    while (timestamps.front() <= now - windowMs) timestamps.pop_front();   // shrink: drop expired timestamps\n    return timestamps.size() <= maxRequests;\n}`, explanation: 'A production rate limiter is a sliding window over time instead of over array indices — expand by pushing the new request, shrink by dropping anything older than the window.' },
          ],
          commonMistakes: [
            'Using sliding window when the subsequence does not need to be contiguous — that is a DP or two-pointer-on-sorted-data problem instead.',
            'Off-by-one on window length: always right - left + 1, not right - left.',
            'Recording the answer before shrinking back to a valid window — the window must be valid first.',
            'Using if instead of while for the shrink step when multiple shrinks might be needed to restore validity.',
            'Applying standard sliding window to arrays with negative numbers, where adding an element does not guarantee the running sum only increases.',
          ],
          revisionNotes: [
            'Two pointer opposite-ends: sorted array, O(n), moving one pointer based on a comparison.',
            'Sliding window: expand right always; shrink left only while invalid; both pointers only move forward — O(n) amortized.',
            'right - left + 1 = window length. Use while for shrinking, not if.',
            'Needs non-negative values (or a monotone running state) to work correctly.',
          ],
          interviewQuestions: [
            { question: 'Why is a sliding-window solution with a while loop inside a for loop still O(n) and not O(n^2)?', answer: 'The inner while loop only advances the left pointer, and left can only move forward — it never resets backward. Across the entire outer loop\'s execution, left can therefore move at most n times in total (not n times per outer iteration), so the combined work of both loops is O(n) + O(n) = O(n), an amortized analysis rather than a per-iteration worst case.', difficulty: 'medium' },
            { question: 'When does sliding window NOT apply to a subarray-sum problem?', answer: 'When the array contains negative numbers, because adding an element to the window no longer guarantees the running sum increases (and removing one no longer guarantees it decreases) — the "shrink when too big" logic breaks down. In that case, a prefix-sum-plus-hashmap approach (counting how many times each prefix sum has occurred) is the correct O(n) technique instead.', difficulty: 'medium' },
          ],
          keyTakeaways: ['Sliding window = two pointers that only move forward, describing one contiguous range — expand right, shrink left, record when valid.', 'The amortized O(n) argument is the reason this beats brute force, not just "fewer loops".'],
        },
      ],
    },
    {
      id: 'medium-problems-sw', title: 'Medium Problems',
      topics: [
        { id:'longest-subarray-sum-k-pos', slug:'longest-subarray-sum-k-pos', title:'Longest Subarray with Sum K (Positives only)', type:'problem', difficulty:'easy', pattern:'Sliding Window',
          problemStatement:'Given a positive-integer array, find the length of the longest subarray with sum exactly K.',
          examples:[{input:'[1,2,3,1,1,1], K=3', output:'3', explanation:'[1,2] or [3] or [1,1,1]'}],
          approaches:[{name:'Sliding Window',intuition:'Maintain a window [l,r]. Expand r. If sum>K, shrink from l.',steps:['l=0, sum=0, maxLen=0','For r from 0 to n-1: sum+=arr[r]','While sum>K: sum-=arr[l]; l++','maxLen = max(maxLen, r-l+1)'],complexity:{time:'O(N)',space:'O(1)'},code:`int longestSubarrayK(vector<int>& a, int k) {\n    int l=0,sum=0,maxL=0;\n    for(int r=0;r<a.size();r++){\n        sum+=a[r];\n        while(sum>k) sum-=a[l++];\n        if(sum==k) maxL=max(maxL,r-l+1);\n    }\n    return maxL;\n}`}],
          hints:['Sliding window works because all values are positive (sum is monotone).','Expand right, shrink left when sum > K.','For negative values, use prefix sum + hashmap instead.'],
          solution:`int f(vector<int>&a,int k){int l=0,s=0,m=0;for(int r=0;r<a.size();r++){s+=a[r];while(s>k)s-=a[l++];if(s==k)m=max(m,r-l+1);}return m;}`,
          keyTakeaways:['Sliding window for positive-only arrays. Use prefix sum + map for arrays with negatives.'] },
        { id:'count-subarrays-sum-k', slug:'count-subarrays-sum-k', title:'Count Subarrays with Sum K', type:'problem', difficulty:'medium', pattern:'Prefix Sum + HashMap',
          problemStatement:'Count the number of subarrays with sum exactly equal to K. Array can have negatives.',
          examples:[{input:'[1,1,1], K=2', output:'2'}],
          approaches:[{name:'Prefix Sum + HashMap',intuition:'prefixSum[r] - prefixSum[l] = K means subarray [l+1..r] has sum K. Store prefix sum counts.',steps:['map[0]=1 (empty prefix)','For each r: prefixSum+=a[r]','count += map[prefixSum - K]','map[prefixSum]++'],complexity:{time:'O(N)',space:'O(N)'},code:`int subarraySum(vector<int>& a, int k) {\n    unordered_map<int,int> cnt; cnt[0]=1;\n    int sum=0, res=0;\n    for(int x:a){sum+=x;res+=cnt[sum-k];cnt[sum]++;}\n    return res;\n}`}],
          hints:['prefix[r] - prefix[l-1] = K → prefix[l-1] = prefix[r] - K.','Initialize map with {0:1} for subarrays starting at index 0.','Works with negative numbers too.'],
          solution:`int f(vector<int>&a,int k){unordered_map<int,int>m;m[0]=1;int s=0,r=0;for(int x:a){s+=x;r+=m[s-k];m[s]++;}return r;}`,
          leetcodeUrl:'https://leetcode.com/problems/subarray-sum-equals-k/',
          keyTakeaways:['Prefix sum + hashmap: count subarrays with sum K in O(N). Classic pattern.'] },
        { id:'max-consecutive-ones-3', slug:'max-consecutive-ones-3', title:'Max Consecutive Ones III (at most K zeros)', type:'problem', difficulty:'medium', pattern:'Sliding Window',
          problemStatement:'Given binary array, find maximum length subarray with at most K zeros (you can flip K zeros to ones).',
          examples:[{input:'[1,1,1,0,0,0,1,1,1,1,0], K=2', output:'6'}],
          approaches:[{name:'Sliding Window',intuition:'Window [l,r] is valid while zeros count <= K. Expand r. If zeros > K, shrink l.',steps:['zeros=0, l=0, maxLen=0','r from 0 to n: if arr[r]==0: zeros++','While zeros>K: if arr[l]==0: zeros--; l++','maxLen=max(maxLen,r-l+1)'],complexity:{time:'O(N)',space:'O(1)'},code:`int longestOnes(vector<int>& a, int k) {\n    int l=0,zeros=0,res=0;\n    for(int r=0;r<a.size();r++){\n        if(a[r]==0) zeros++;\n        while(zeros>k){if(a[l++]==0)zeros--;}\n        res=max(res,r-l+1);\n    }\n    return res;\n}`}],
          hints:['Count zeros in window. Shrink when zeros > K.','Equivalent to: find longest window with at most K zeros.','Generalizes to "at most K of something" pattern.'],
          solution:`int f(vector<int>&a,int k){int l=0,z=0,r=0;for(int i=0;i<a.size();i++){if(!a[i])z++;while(z>k)if(!a[l++])z--;r=max(r,i-l+1);}return r;}`,
          leetcodeUrl:'https://leetcode.com/problems/max-consecutive-ones-iii/',
          keyTakeaways:['Sliding window "at most K violations" pattern — appears in many forms.'] },
        { id:'fruits-into-baskets', slug:'fruits-into-baskets', title:'Fruits into Baskets', type:'problem', difficulty:'medium', pattern:'Sliding Window',
          problemStatement:'You have two baskets (each holds one fruit type). Find max fruits you can collect consecutively (longest subarray with at most 2 distinct values).',
          examples:[{input:'[1,2,1,2,3]', output:'4', explanation:'[1,2,1,2]'}],
          approaches:[{name:'Sliding Window + map',intuition:'Maintain window with at most 2 distinct fruits. Shrink when 3rd type enters.',steps:['map of fruit→count, l=0','For r: add arr[r] to map','While map.size()>2: remove arr[l] from map; l++','res=max(res,r-l+1)'],complexity:{time:'O(N)',space:'O(1)'},code:`int totalFruit(vector<int>& a) {\n    unordered_map<int,int> cnt;\n    int l=0, res=0;\n    for(int r=0;r<a.size();r++){\n        cnt[a[r]]++;\n        while(cnt.size()>2){\n            if(--cnt[a[l]]==0) cnt.erase(a[l]);\n            l++;\n        }\n        res=max(res,r-l+1);\n    }\n    return res;\n}`}],
          hints:['Two baskets = at most 2 distinct values in window.','Use a map to track counts. Shrink when distinct > 2.','Remove key from map when count reaches 0.'],
          solution:`int f(vector<int>&a){unordered_map<int,int>c;int l=0,r=0;for(int i=0;i<a.size();i++){c[a[i]]++;while(c.size()>2){if(--c[a[l]]==0)c.erase(a[l]);l++;}r=max(r,i-l+1);}return r;}`,
          leetcodeUrl:'https://leetcode.com/problems/fruit-into-baskets/',
          keyTakeaways:['At most K distinct values in window — sliding window with map.'] },
        { id:'longest-substring-no-repeat', slug:'longest-substring-no-repeat', title:'Longest Substring Without Repeating Characters', type:'problem', difficulty:'medium', pattern:'Sliding Window',
          problemStatement:'Find the length of the longest substring without repeating characters.',
          examples:[{input:'"abcabcbb"', output:'3', explanation:'"abc"'}],
          approaches:[{name:'Sliding Window + HashSet',intuition:'Window [l,r] has all unique chars. Expand r. If repeat found, shrink l until no repeat.',steps:['set for window chars, l=0','For r: while arr[r] in set: remove arr[l], l++','Add arr[r] to set','res=max(res,r-l+1)'],complexity:{time:'O(N)',space:'O(min(N,charset))'},code:`int lengthOfLongestSubstring(string s) {\n    unordered_set<char> st;\n    int l=0, res=0;\n    for(int r=0;r<s.size();r++){\n        while(st.count(s[r])) st.erase(s[l++]);\n        st.insert(s[r]);\n        res=max(res,r-l+1);\n    }\n    return res;\n}`}],
          hints:['Use a set to track chars in current window.','When duplicate found, remove from left until no duplicate.','Alternatively, use map<char,lastIndex> for O(1) left jump.'],
          solution:`int f(string s){unordered_set<char>st;int l=0,r=0;for(int i=0;i<s.size();i++){while(st.count(s[i]))st.erase(s[l++]);st.insert(s[i]);r=max(r,i-l+1);}return r;}`,
          leetcodeUrl:'https://leetcode.com/problems/longest-substring-without-repeating-characters/',
          keyTakeaways:['Classic sliding window. Use set for uniqueness. O(N) overall.'] },
        { id:'min-window-substring', slug:'min-window-substring', title:'Minimum Window Substring', type:'problem', difficulty:'hard', pattern:'Sliding Window',
          problemStatement:'Find the minimum window in string s that contains all characters of string t.',
          examples:[{input:'s="ADOBECODEBANC", t="ABC"', output:'"BANC"'}],
          approaches:[{name:'Sliding Window with two maps',intuition:'Expand window until all chars of t are included. Then shrink from left to minimize.',steps:['Count chars needed (tMap)','Expand r: decrement need count','When all chars present: shrink l, update min window','Expand again'],complexity:{time:'O(S+T)',space:'O(S+T)'},code:`string minWindow(string s, string t) {\n    unordered_map<char,int> need;\n    for(char c:t) need[c]++;\n    int have=0, total=need.size(), l=0, minLen=INT_MAX, start=0;\n    unordered_map<char,int> window;\n    for(int r=0;r<s.size();r++){\n        char c=s[r]; window[c]++;\n        if(need.count(c)&&window[c]==need[c]) have++;\n        while(have==total){\n            if(r-l+1<minLen){minLen=r-l+1;start=l;}\n            window[s[l]]--;\n            if(need.count(s[l])&&window[s[l]]<need[s[l]]) have--;\n            l++;\n        }\n    }\n    return minLen==INT_MAX?\"\":s.substr(start,minLen);\n}`}],
          hints:['Track "have" (chars satisfied) vs "need" (distinct chars in t).','Shrink only when all chars of t are in window.','Update answer at each valid window.'],
          solution:`// See above — two maps, have/need counters`,
          leetcodeUrl:'https://leetcode.com/problems/minimum-window-substring/',
          keyTakeaways:['Minimum window: expand until valid, shrink while valid, track minimum.'] },
      ],
    },
    {
      id: 'hard-problems-sw', title: 'Hard Problems',
      topics: [
        { id:'count-distinct-subarrays-k', slug:'count-distinct-subarrays-k', title:'Count Subarrays with exactly K Distinct', type:'problem', difficulty:'hard', pattern:'Sliding Window',
          problemStatement:'Count subarrays with exactly K distinct elements. Array [1,2,1,2,3], K=2 → 7.',
          examples:[{input:'[1,2,1,2,3], K=2', output:'7'}],
          approaches:[{name:'atMost(K) - atMost(K-1)',intuition:'Exactly K = atMost(K) - atMost(K-1). AtMost is a standard sliding window.',steps:['Write atMostK(arr,k): count subarrays with <=k distinct','Answer = atMostK(arr,k) - atMostK(arr,k-1)'],complexity:{time:'O(N)',space:'O(N)'},code:`int atMost(vector<int>&a, int k){\n    unordered_map<int,int> cnt;\n    int l=0,res=0;\n    for(int r=0;r<a.size();r++){\n        cnt[a[r]]++;\n        while(cnt.size()>k){if(--cnt[a[l]]==0)cnt.erase(a[l]);l++;}\n        res+=r-l+1; // all subarrays ending at r with <=k distinct\n    }\n    return res;\n}\nint exactlyK(vector<int>&a,int k){return atMost(a,k)-atMost(a,k-1);}`}],
          hints:['"Exactly K" = "at most K" - "at most K-1".','atMost(K): for each r, add r-l+1 (subarrays ending at r).','This trick converts hard "exactly" to easy "at most".'],
          solution:`int atMost(vector<int>&a,int k){unordered_map<int,int>c;int l=0,r=0;for(int i=0;i<a.size();i++){c[a[i]]++;while(c.size()>k){if(--c[a[l]]==0)c.erase(a[l]);l++;}r+=i-l+1;}return r;}\nint f(vector<int>&a,int k){return atMost(a,k)-atMost(a,k-1);}`,
          leetcodeUrl:'https://leetcode.com/problems/subarrays-with-k-different-integers/',
          keyTakeaways:['Exactly K = atMost(K) - atMost(K-1). Key trick for window problems.'] },
        { id:'longest-repeating-char-replacement', slug:'longest-repeating-char-replacement', title:'Longest Repeating Character Replacement', type:'problem', difficulty:'medium', pattern:'Sliding Window',
          problemStatement:'Replace at most K chars. Find the longest substring with all same characters.',
          examples:[{input:'s="AABABBA", K=1', output:'4'}],
          approaches:[{name:'Sliding Window with maxFreq',intuition:'Window is valid if (windowLen - maxFreqChar) <= K. Maintain max frequency.',steps:['Track char frequencies in window','if (r-l+1 - maxFreq > k): shrink window','Track maxFreq (never decrease for optimization)'],complexity:{time:'O(N)',space:'O(26)'},code:`int characterReplacement(string s, int k) {\n    int cnt[26]={}, maxFreq=0, l=0, res=0;\n    for(int r=0;r<s.size();r++){\n        maxFreq=max(maxFreq,++cnt[s[r]-'A']);\n        if(r-l+1-maxFreq>k){cnt[s[l++]-'A']--;}\n        res=max(res,r-l+1);\n    }\n    return res;\n}`}],
          hints:['Window valid when: length - max_frequency <= K.','Never shrink maxFreq — only care about max valid window found so far.','26-char frequency array.'],
          solution:`int f(string s,int k){int c[26]={},mf=0,l=0,r=0;for(int i=0;i<s.size();i++){mf=max(mf,++c[s[i]-'A']);if(i-l+1-mf>k)c[s[l++]-'A']--;r=max(r,i-l+1);}return r;}`,
          leetcodeUrl:'https://leetcode.com/problems/longest-repeating-character-replacement/',
          keyTakeaways:['Key insight: windowSize - maxFreq <= K means window is valid.'] },
        { id:'number-of-substrings-3chars', slug:'number-of-substrings-3chars', title:'Number of Substrings Containing All Three Characters', type:'problem', difficulty:'hard', pattern:'Sliding Window',
          problemStatement:'Count substrings containing at least one of each a, b, c.',
          examples:[{input:'"abcabc"', output:'10'}],
          approaches:[{name:'Sliding Window from right',intuition:'For each r, find the minimum l such that window has all 3. All strings from l to end (n-r more) are valid.',steps:['Track last occurrence of a, b, c','For each r: l = min of last[a], last[b], last[c]','Add l+1 to result (all substrings ending at r that include at least one of each)'],complexity:{time:'O(N)',space:'O(1)'},code:`int numberOfSubstrings(string s) {\n    int last[3]={-1,-1,-1}, res=0;\n    for(int r=0;r<s.size();r++){\n        last[s[r]-'a']=r;\n        res+=1+min({last[0],last[1],last[2]});\n    }\n    return res;\n}`}],
          hints:['Track last index where each of a, b, c was seen.','min(last[a], last[b], last[c])+1 = number of valid left ends.','All substrings ending at r with left <= min_last are valid.'],
          solution:`int f(string s){int l[3]={-1,-1,-1},r=0;for(int i=0;i<s.size();i++){l[s[i]-'a']=i;r+=1+min({l[0],l[1],l[2]});}return r;}`,
          leetcodeUrl:'https://leetcode.com/problems/number-of-substrings-containing-all-three-characters/',
          keyTakeaways:['Track last occurrence of required chars. min+1 gives count of valid starting points.'] },
      ],
    },
  ],
};
