import type { DSASection } from '@/types/dsa';

export const heapsSection: DSASection = {
  id: 'heaps', slug: 'heaps',
  title: 'Heaps [Learning, Medium, Hard Problems]',
  description: 'Priority queues, K-th element problems, merge K sorted, median, and running order statistics.',
  icon: '⛰️', color: 'from-orange-500 to-amber-600',
  subsections: [
    {
      id: 'heaps-learn', title: 'Learning',
      topics: [
        { id:'heap-intro', slug:'heap-intro', title:'Introduction to Heaps', type:'lesson', difficulty:'easy',
          introduction:'A heap is a complete binary tree satisfying the heap property. Min-heap: parent <= children. Max-heap: parent >= children. Implemented as an array.',
          theory:`**Array representation:** Parent at i → children at 2i+1 and 2i+2. Child at j → parent at (j-1)/2.\n\n**Operations:**\n- Insert: add at end, heapify up. O(log N)\n- Extract min/max: remove root, replace with last, heapify down. O(log N)\n- Build heap: O(N) using heapify from N/2-1 to 0\n- Peek: O(1)\n\n**STL in C++:**\n- Max-heap: priority_queue<int> pq\n- Min-heap: priority_queue<int, vector<int>, greater<int>> pq`,
          codeExamples:[{title:'Heap operations in C++',language:'cpp',code:`// Max heap (default)\npriority_queue<int> maxH;\nmaxH.push(3); maxH.push(1); maxH.push(5);\ncout << maxH.top() << "\\n"; // 5\nmaxH.pop();\n\n// Min heap\npriority_queue<int,vector<int>,greater<int>> minH;\nminH.push(3); minH.push(1); minH.push(5);\ncout << minH.top() << "\\n"; // 1\n\n// Custom comparator (e.g., pair sorted by second)\npriority_queue<pair<int,int>,vector<pair<int,int>>,greater<>> pq;\npq.push({3,1}); pq.push({1,5});\ncout << pq.top().first; // 1`}],
          keyTakeaways:['Heap = array-based binary tree. O(log N) push/pop. O(1) peek.','Max-heap: pq<int>. Min-heap: pq<int,vector<int>,greater<int>>.'] },
        { id:'heap-sort', slug:'heap-sort', title:'Heap Sort Algorithm', type:'lesson', difficulty:'medium',
          introduction:'Heap sort uses a max-heap to sort in O(N log N) with O(1) extra space. In-place and not stable.',
          theory:`**Steps:**\n1. Build max-heap from array: O(N)\n2. Repeatedly extract max (swap root with last, heapify): O(N log N)\n\n**Why O(N) build?** Heapify from N/2-1 to 0. Work at level h is O(h). Sum = O(N).\n\n**Vs merge sort:** Same O(N log N) but not stable. Better space: O(1) vs O(N).\n**Vs quicksort:** Quicksort faster in practice due to cache-friendliness.`,
          codeExamples:[{title:'Heap Sort',language:'cpp',code:`void heapify(vector<int>& a, int n, int i) {\n    int largest=i, l=2*i+1, r=2*i+2;\n    if(l<n&&a[l]>a[largest]) largest=l;\n    if(r<n&&a[r]>a[largest]) largest=r;\n    if(largest!=i){swap(a[i],a[largest]);heapify(a,n,largest);}\n}\nvoid heapSort(vector<int>& a){\n    int n=a.size();\n    for(int i=n/2-1;i>=0;i--) heapify(a,n,i); // build max heap\n    for(int i=n-1;i>0;i--){swap(a[0],a[i]);heapify(a,i,0);} // extract\n}`}],
          keyTakeaways:['Heap sort: O(N log N) always, O(1) space. Not stable.','Build heap: start from N/2-1, heapify each node downward.'] },
      ],
    },
    {
      id: 'heaps-medium', title: 'Medium Problems',
      topics: [
        { id:'kth-largest-element', slug:'kth-largest-element', title:'Kth Largest Element in an Array', type:'problem', difficulty:'easy', pattern:'Heap',
          problemStatement:'Find the Kth largest element in an unsorted array.',
          examples:[{input:'[3,2,1,5,6,4], K=2', output:'5'}],
          approaches:[{name:'Min-Heap of size K',intuition:'Maintain a min-heap of K elements. After processing all, top is Kth largest.',steps:['Min-heap of size K','For each element: push','If heap size > K: pop','Top of heap is Kth largest'],complexity:{time:'O(N log K)',space:'O(K)'},code:`int findKthLargest(vector<int>& a, int k) {\n    priority_queue<int,vector<int>,greater<int>> minH;\n    for(int x:a){\n        minH.push(x);\n        if(minH.size()>k) minH.pop();\n    }\n    return minH.top();\n}`}],
          hints:['Min-heap of size K keeps the K largest elements.','When heap exceeds K, pop the smallest — so only K largest remain.','Heap top is the smallest of K largest = Kth largest overall.'],
          solution:`int f(vector<int>&a,int k){priority_queue<int,vector<int>,greater<int>>h;for(int x:a){h.push(x);if(h.size()>k)h.pop();}return h.top();}`,
          leetcodeUrl:'https://leetcode.com/problems/kth-largest-element-in-an-array/',
          keyTakeaways:['K-th largest with min-heap size K: O(N log K). A go-to interview pattern.'] },
        { id:'kth-smallest-element', slug:'kth-smallest-element', title:'Kth Smallest Element', type:'problem', difficulty:'easy', pattern:'Heap',
          problemStatement:'Find Kth smallest element.',
          examples:[{input:'[7,10,4,3,20,15], K=3', output:'7'}],
          approaches:[{name:'Max-Heap of size K',intuition:'Max-heap of K elements. Pop when size exceeds K. Top is Kth smallest.',steps:['Max-heap size K','For each element: push; if size>K: pop','Top is Kth smallest'],complexity:{time:'O(N log K)',space:'O(K)'},code:`int kthSmallest(vector<int>&a,int k){\n    priority_queue<int> maxH;\n    for(int x:a){maxH.push(x);if(maxH.size()>k)maxH.pop();}\n    return maxH.top();\n}`}],
          hints:['Max-heap of K elements keeps the K smallest.','Pop largest when size exceeds K.','Top is the largest of K smallest = Kth smallest.'],
          solution:`int f(vector<int>&a,int k){priority_queue<int>h;for(int x:a){h.push(x);if(h.size()>k)h.pop();}return h.top();}`,
          keyTakeaways:['Kth smallest: max-heap size K. Symmetric to kth largest.'] },
        { id:'sort-k-sorted-array', slug:'sort-k-sorted-array', title:'Sort a K Sorted Array', type:'problem', difficulty:'medium', pattern:'Heap',
          problemStatement:'An array where every element is at most K positions away from its sorted position. Sort it efficiently.',
          examples:[{input:'[6,5,3,2,8,10,9], K=3', output:'[2,3,5,6,8,9,10]'}],
          approaches:[{name:'Min-heap of size K+1',intuition:'Maintain min-heap of K+1 elements. Smallest in window is definitely at current position.',steps:['Push first K+1 elements to min-heap','For each remaining: push to heap, pop minimum to output','Pop remaining from heap'],complexity:{time:'O(N log K)',space:'O(K)'},code:`vector<int> sortKSorted(vector<int>& a, int k) {\n    priority_queue<int,vector<int>,greater<int>> h(a.begin(),a.begin()+min(k+1,(int)a.size()));\n    vector<int> res;\n    for(int i=k+1;i<a.size();i++){res.push_back(h.top());h.pop();h.push(a[i]);}\n    while(!h.empty()){res.push_back(h.top());h.pop();}\n    return res;\n}`}],
          hints:['Window of K+1 always contains the next sorted element.','Min-heap of size K+1: top is always the minimum in the window.'],
          solution:`// Min-heap sliding window as above`,
          keyTakeaways:['K-sorted: window of K+1, min-heap finds the minimum. O(N log K).'] },
        { id:'merge-k-sorted-arrays', slug:'merge-k-sorted-arrays', title:'Merge K Sorted Arrays', type:'problem', difficulty:'hard', pattern:'Heap',
          problemStatement:'Given K sorted arrays, merge them into one sorted array.',
          examples:[{input:'[[1,3],[2,4],[5,6]]', output:'[1,2,3,4,5,6]'}],
          approaches:[{name:'Min-heap with (val, array_idx, element_idx)',intuition:'Start with first element of each array in heap. Extract min, push next element from same array.',steps:['Push (arr[i][0], i, 0) for each array i','Extract min (v, ai, ei): push to result','Push (arr[ai][ei+1], ai, ei+1) if exists'],complexity:{time:'O(N K log K)',space:'O(K)'},code:`vector<int> mergeK(vector<vector<int>>& arrays) {\n    using T = tuple<int,int,int>; // val, array, index\n    priority_queue<T,vector<T>,greater<T>> h;\n    for(int i=0;i<arrays.size();i++) h.push({arrays[i][0],i,0});\n    vector<int> res;\n    while(!h.empty()){\n        auto [v,ai,ei]=h.top(); h.pop();\n        res.push_back(v);\n        if(ei+1<arrays[ai].size()) h.push({arrays[ai][ei+1],ai,ei+1});\n    }\n    return res;\n}`}],
          hints:['Push first element of each array with its array and index.','Pop minimum, add next element from same array.','Uses structured bindings (C++17): auto [val, ai, ei] = h.top().'],
          solution:`// Tuple heap approach as above`,
          keyTakeaways:['Merge K sorted: O(NK log K) with min-heap. Template for many heap problems.'] },
        { id:'replace-elements-rank', slug:'replace-elements-rank', title:'Replace Elements by Rank', type:'problem', difficulty:'medium', pattern:'Heap',
          problemStatement:'Replace each element with its rank (1=smallest). Equal elements get same rank.',
          examples:[{input:'[20,15,26,2,98,6]', output:'[4,3,5,1,6,2]'}],
          approaches:[{name:'Sort + HashMap',intuition:'Sort unique values, assign ranks. Replace each element via map.',steps:['Copy and sort unique values','Assign rank 1,2,3... to each unique sorted value','Replace original array elements using the rank map'],complexity:{time:'O(N log N)',space:'O(N)'},code:`vector<int> replaceByRank(vector<int>& a){\n    vector<int> sorted=a;\n    sort(sorted.begin(),sorted.end());\n    sorted.erase(unique(sorted.begin(),sorted.end()),sorted.end());\n    unordered_map<int,int> rank;\n    for(int i=0;i<sorted.size();i++) rank[sorted[i]]=i+1;\n    for(int&x:a) x=rank[x];\n    return a;\n}`}],
          hints:['Sort unique values, assign rank by position.','Use map to look up rank in O(1).'],
          solution:`// Sort+unique+map as above`,
          keyTakeaways:['Rank assignment: sort unique, map to 1-indexed positions.'] },
        { id:'task-scheduler', slug:'task-scheduler', title:'Task Scheduler', type:'problem', difficulty:'medium', pattern:'Heap + Greedy',
          problemStatement:'Given tasks with frequencies and cooldown n, find minimum time to execute all tasks.',
          examples:[{input:'tasks=["A","A","A","B","B","B"], n=2', output:'8'}],
          approaches:[{name:'Max-heap + queue',intuition:'Always execute the most frequent available task. Use max-heap and a cooldown queue.',steps:['Count frequencies, push to max-heap','At each time unit: pop max-freq task, add to cooldown queue (time+n)','When cooldown done, push back to heap'],complexity:{time:'O(N log N)',space:'O(N)'},code:`int leastInterval(vector<char>& tasks, int n){\n    unordered_map<char,int> cnt;\n    for(char c:tasks) cnt[c]++;\n    priority_queue<int> maxH;\n    for(auto&[c,f]:cnt) maxH.push(f);\n    queue<pair<int,int>> cooldown; // {freq, available_time}\n    int time=0;\n    while(!maxH.empty()||!cooldown.empty()){\n        time++;\n        if(!maxH.empty()){int f=maxH.top()-1;maxH.pop();if(f>0) cooldown.push({f,time+n});}\n        if(!cooldown.empty()&&cooldown.front().second==time){maxH.push(cooldown.front().first);cooldown.pop();}\n    }\n    return time;\n}`}],
          hints:['Greedy: always pick most frequent available task.','Max-heap for frequencies. Queue for cooldown tracking.','Idle time = max(0, n - (second_max_tasks))'],
          solution:`// See above — max-heap + cooldown queue`,
          leetcodeUrl:'https://leetcode.com/problems/task-scheduler/',
          keyTakeaways:['Task scheduling: max-heap for greedy selection + cooldown queue.'] },
      ],
    },
    {
      id: 'heaps-hard', title: 'Hard Problems',
      topics: [
        { id:'design-twitter', slug:'design-twitter', title:'Design Twitter (Follow/Tweet/NewsFeed)', type:'problem', difficulty:'hard', pattern:'Heap + HashMap',
          problemStatement:'Implement Twitter: postTweet, follow, unfollow, getNewsFeed (10 most recent tweets from user + followees).',
          examples:[{input:'postTweet(1,5), follow(1,2), postTweet(2,6), getNewsFeed(1)', output:'[6,5]'}],
          approaches:[{name:'HashMap + Min-heap',intuition:'Store tweets per user with timestamps. getNewsFeed: merge tweets from all followees using max-heap on timestamp.',steps:['userTweets: map<int,vector<{time,tweetId}>>','followees: map<int,set<int>>','getNewsFeed: push most recent tweet of each followee to max-heap, extract top 10'],complexity:{time:'O(F log F + 10 log F) per feed',space:'O(N)'},code:`class Twitter {\n    int ts=0;\n    unordered_map<int,vector<pair<int,int>>> tweets;\n    unordered_map<int,set<int>> follows;\npublic:\n    void postTweet(int u,int t){tweets[u].push_back({ts++,t});}\n    void follow(int u,int f){follows[u].insert(f);}\n    void unfollow(int u,int f){follows[u].erase(f);}\n    vector<int> getNewsFeed(int u){\n        priority_queue<tuple<int,int,int,int>> pq;\n        follows[u].insert(u);\n        for(int f:follows[u]){\n            auto&tw=tweets[f];\n            if(!tw.empty()) pq.push({tw.back().first,tw.back().second,f,(int)tw.size()-1});\n        }\n        vector<int> res;\n        while(!pq.empty()&&res.size()<10){\n            auto[t,id,f,idx]=pq.top();pq.pop();\n            res.push_back(id);\n            if(idx>0) pq.push({tweets[f][idx-1].first,tweets[f][idx-1].second,f,idx-1});\n        }\n        return res;\n    }\n};`}],
          hints:['Global timestamp for ordering.','GetNewsFeed = merge sorted lists (per-user tweet lists) using max-heap.','Add user to own followee set for feed.'],
          solution:`// See class above`,
          leetcodeUrl:'https://leetcode.com/problems/design-twitter/',
          keyTakeaways:['Design problems: identify data structures (map + heap). News feed = merge sorted lists.'] },
        { id:'median-data-stream', slug:'median-data-stream', title:'Find Median from Data Stream', type:'problem', difficulty:'hard', pattern:'Two Heaps',
          problemStatement:'Design data structure supporting addNum(num) and findMedian(). Numbers are added dynamically.',
          examples:[{input:'addNum(1), addNum(2), findMedian() → 1.5, addNum(3), findMedian() → 2', output:'1.5, 2.0'}],
          approaches:[{name:'Two Heaps (Max + Min)',intuition:'Max-heap for lower half, min-heap for upper half. Balance sizes. Median = tops.',steps:['maxH (lower half), minH (upper half)','On add: push to maxH, move max to minH','If minH.size() > maxH.size(): move min back to maxH','Median: if equal sizes: avg of tops, else maxH.top()'],complexity:{time:'O(log N) add, O(1) findMedian',space:'O(N)'},code:`class MedianFinder {\n    priority_queue<int> maxH;\n    priority_queue<int,vector<int>,greater<int>> minH;\npublic:\n    void addNum(int n){\n        maxH.push(n);\n        minH.push(maxH.top()); maxH.pop();\n        if(minH.size()>maxH.size()){maxH.push(minH.top());minH.pop();}\n    }\n    double findMedian(){\n        if(maxH.size()>minH.size()) return maxH.top();\n        return (maxH.top()+minH.top())/2.0;\n    }\n};`}],
          hints:['Two heaps: maxH for lower half, minH for upper half.','Always keep them balanced (differ by at most 1).','Median: if same size → average; else → larger heap\'s top.'],
          solution:`// Two-heap class as above`,
          leetcodeUrl:'https://leetcode.com/problems/find-median-from-data-stream/',
          keyTakeaways:['Median stream: two balanced heaps. O(log N) add, O(1) median.'] },
        { id:'k-most-frequent-elements', slug:'k-most-frequent-elements', title:'K Most Frequent Elements', type:'problem', difficulty:'easy', pattern:'Heap',
          problemStatement:'Return the K most frequent elements from an array.',
          examples:[{input:'[1,1,1,2,2,3], K=2', output:'[1,2]'}],
          approaches:[{name:'Min-heap of size K with frequencies',intuition:'Count frequencies. Min-heap of size K on frequencies keeps K most frequent.',steps:['Count frequencies with map','Min-heap of (freq, val)','If heap size > K: pop (removes least frequent)','Collect heap elements'],complexity:{time:'O(N log K)',space:'O(N)'},code:`vector<int> topKFrequent(vector<int>& a, int k) {\n    unordered_map<int,int> freq;\n    for(int x:a) freq[x]++;\n    priority_queue<pair<int,int>,vector<pair<int,int>>,greater<>> h;\n    for(auto&[v,f]:freq){\n        h.push({f,v});\n        if(h.size()>k) h.pop();\n    }\n    vector<int> res;\n    while(!h.empty()){res.push_back(h.top().second);h.pop();}\n    return res;\n}`}],
          hints:['Frequency map first.','Min-heap of size K on (freq, val).','When size exceeds K, pop — removes least frequent.'],
          solution:`// See above`,
          leetcodeUrl:'https://leetcode.com/problems/top-k-frequent-elements/',
          keyTakeaways:['Top K frequent: min-heap size K on frequencies. O(N log K).'] },
      ],
    },
  ],
};
