import type { DSASection } from '@/types/dsa';

export const greedySection: DSASection = {
  id: 'greedy', slug: 'greedy',
  title: 'Greedy Algorithms [Easy and Medium/Hard]',
  description: 'Solve optimization problems by making locally optimal choices at each step. Includes interval scheduling, activity selection, and jump games.',
  icon: '💰', color: 'from-lime-500 to-green-600',
  subsections: [
    {
      id: 'greedy-theory', title: 'Theory',
      topics: [
        { id:'greedy-theory-lesson', slug:'greedy-theory-lesson', title:'Greedy Algorithms — Theory (Read This First)', type:'lesson', difficulty:'easy',
          introduction: `A greedy algorithm builds a solution step by step, at each step making the choice that looks **locally best right now**, and never reconsidering it. Why it exists: for some problems, making the locally optimal choice at every step provably leads to a globally optimal answer, which is far cheaper than exploring every possible combination (which DP or brute force would require). Real-world usage: OS task scheduling (shortest job first), coin change with standard currency denominations, Huffman coding for compression, and network routing (shortest-edge-first / Prim's/Kruskal's MST) are all classic greedy applications.`,
          theory: `**The greedy recipe:**\n1. Sort or order the input by some criterion that makes the "obviously best next choice" visible (e.g., earliest finish time, smallest size, highest ratio).\n2. Walk through the sorted input once, greedily taking/skipping each item according to a simple local rule.\n3. Never backtrack or reconsider a previous choice.\n\n\`\`\`cpp\n// Generic greedy skeleton\nsort(items.begin(), items.end(), comparator);   // step 1: order by the right criterion\nfor (auto& item : items) {                        // step 2: single pass\n    if (/* locally optimal to take it */) {\n        take(item);\n    }\n}\n\`\`\`\n\n**How do you know greedy is even valid for a given problem?** You must be able to argue (formally, an "exchange argument") that swapping any optimal solution's choice for the greedy choice never makes it worse. If you cannot construct such an argument, and the problem instead needs you to weigh trade-offs between many choices simultaneously, it is probably a Dynamic Programming problem, not a greedy one. A classic contrast: **Fractional Knapsack** (take a fraction of any item — greedy on value/weight ratio works, provably optimal) vs. **0/1 Knapsack** (each item is all-or-nothing — greedy fails; you need DP because the best choice for the current item depends on what capacity remains for the rest).\n\n**Common greedy criteria (memorize these, they cover most problems):**\n- Interval scheduling / activity selection: sort by **earliest end time**, greedily take any interval that doesn't overlap the last taken one.\n- Assigning limited resources to demands (e.g. cookies to children): sort **both** lists, use two pointers, satisfy the least-demanding need with the smallest sufficient resource.\n- Jump Game / reachability: track the **farthest index reachable so far** while scanning left to right.\n- Huffman-style/priority problems: repeatedly take the **two smallest** items using a min-heap.`,
          codeExamples: [
            { title: 'Simple: assign cookies (two sorted lists, two pointers)', language: 'cpp', code: `int findContentChildren(vector<int>& g, vector<int>& s) {\n    sort(g.begin(), g.end()); sort(s.begin(), s.end());\n    int i = 0, j = 0;\n    while (i < g.size() && j < s.size()) {\n        if (s[j] >= g[i]) i++;   // this cookie satisfies this child -> move to next child\n        j++;                      // always move to the next cookie\n    }\n    return i;                    // number of satisfied children\n}`, explanation: 'Sorting both makes the greedy rule ("use the smallest sufficient cookie for the least greedy child") directly checkable with two pointers.' },
            { title: 'Practical: activity selection / non-overlapping intervals', language: 'cpp', code: `int maxNonOverlapping(vector<pair<int,int>>& intervals) {\n    sort(intervals.begin(), intervals.end(), [](auto& a, auto& b) { return a.second < b.second; });  // sort by END time\n    int count = 0, lastEnd = INT_MIN;\n    for (auto& [start, end] : intervals) {\n        if (start >= lastEnd) { count++; lastEnd = end; }   // doesn't overlap the last chosen interval\n    }\n    return count;\n}`, explanation: 'Sorting by end time (not start time) is the crucial insight — always greedily keep the interval that frees up time earliest for future choices.', dryRun: 'intervals=[(1,3),(2,4),(3,5)] sorted by end -> (1,3) take, lastEnd=3; (2,4) start2<3 skip; (3,5) start3>=3 take, lastEnd=5 -> count=2' },
            { title: 'Industry-style: CPU/job scheduler (shortest job first)', language: 'cpp', code: `// Minimizing average wait time: greedily run the shortest job available next\ndouble minAverageWaitTime(vector<int>& jobDurations) {\n    sort(jobDurations.begin(), jobDurations.end());   // shortest first\n    long long totalWait = 0, elapsed = 0;\n    for (int d : jobDurations) { totalWait += elapsed; elapsed += d; }\n    return (double)totalWait / jobDurations.size();\n}`, explanation: 'Real OS schedulers (and print queues, task runners) use exactly this greedy "shortest job first" rule to minimize average wait time — a provably optimal greedy strategy.' },
          ],
          commonMistakes: [
            'Applying greedy to a problem that actually requires weighing trade-offs across choices (e.g. 0/1 Knapsack) — greedy silently gives a suboptimal answer without any error.',
            'Sorting by the wrong criterion (e.g. start time instead of end time for interval scheduling) — produces a plausible-looking but wrong answer.',
            'Forgetting to prove (even informally) that the greedy choice is safe — "it seemed to work on my examples" is not a substitute for an exchange-argument.',
            'Not handling ties in the sort comparator consistently, which can flip the answer on edge cases.',
          ],
          revisionNotes: [
            'Greedy = sort by the right criterion, then one pass making locally optimal, non-reconsidered choices.',
            'Validity requires an exchange argument: swapping toward the greedy choice never makes an optimal solution worse.',
            'Fractional Knapsack: greedy works. 0/1 Knapsack: greedy fails, needs DP.',
            'Interval scheduling: sort by end time, not start time.',
          ],
          interviewQuestions: [
            { question: 'How do you know a greedy approach is actually valid for a given problem, rather than just "seems to work" on examples?', answer: 'You need an exchange argument: show that in any hypothetical optimal solution, you can swap its choice at each step for the greedy algorithm\'s choice without making the solution any worse. If you can construct that argument (or it matches a known-optimal greedy pattern like interval scheduling by end time), greedy is safe; if the problem requires weighing how an early choice affects the feasibility of later choices, that\'s a signal you actually need DP instead.', difficulty: 'hard' },
            { question: 'Why does sorting by end time (not start time) work for maximizing non-overlapping intervals?', answer: 'Picking the interval that finishes earliest always leaves the maximum possible remaining time for future intervals, so it never restricts your future options more than any other valid choice would — this is the exchange argument that makes "sort by end time, greedily take non-overlapping intervals" provably optimal.', difficulty: 'medium' },
          ],
          keyTakeaways: ['Greedy = sort by the right criterion + single pass of locally optimal choices, never reconsidered.', 'Always sanity-check greedy validity with an exchange argument — when in doubt, it is probably DP instead.'],
        },
      ],
    },
    {
      id: 'greedy-easy', title: 'Easy Problems',
      topics: [
        { id:'assign-cookies', slug:'assign-cookies', title:'Assign Cookies', type:'problem', difficulty:'easy', pattern:'Greedy + Two Pointer',
          problemStatement:'Assign cookies (size s[j]) to children (greed g[i]). Cookie satisfies child if s[j]>=g[i]. Maximize satisfied children.',
          examples:[{input:'g=[1,2,3], s=[1,1]', output:'1'}],
          approaches:[{name:'Sort + Two Pointer',intuition:'Sort both. Try to satisfy least greedy child with smallest cookie.',steps:['Sort g and s','Two pointers i (children), j (cookies)','If s[j]>=g[i]: satisfied, i++','Always j++','Return i (satisfied count)'],complexity:{time:'O(N log N)',space:'O(1)'},code:`int findContentChildren(vector<int>&g,vector<int>&s){\n    sort(g.begin(),g.end()); sort(s.begin(),s.end());\n    int i=0,j=0;\n    while(i<g.size()&&j<s.size()){\n        if(s[j]>=g[i]) i++;\n        j++;\n    }\n    return i;\n}`}],
          hints:['Sort both arrays.','Match smallest sufficient cookie to least greedy child.','Two pointers: i for children, j for cookies.'],
          solution:`int f(vector<int>&g,vector<int>&s){sort(g.begin(),g.end());sort(s.begin(),s.end());int i=0,j=0;while(i<g.size()&&j<s.size()){if(s[j]>=g[i])i++;j++;}return i;}`,
          leetcodeUrl:'https://leetcode.com/problems/assign-cookies/', keyTakeaways:['Sort both, match smallest cookie to least greedy child — greedy works here.'] },
        { id:'fractional-knapsack', slug:'fractional-knapsack', title:'Fractional Knapsack', type:'problem', difficulty:'medium', pattern:'Greedy',
          problemStatement:'Items have weight and value. Maximize value in knapsack of capacity W. Can take fractions.',
          examples:[{input:'items=[(60,10),(100,20),(120,30)], W=50', output:'240'}],
          approaches:[{name:'Sort by value/weight ratio',intuition:'Sort items by value per weight descending. Take as much of most valuable as possible.',steps:['Sort by val/wt descending','Take whole items while capacity allows','Take fraction of next item to fill remaining'],complexity:{time:'O(N log N)',space:'O(1)'},code:`double fractionalKnapsack(int W, vector<pair<int,int>>& items){\n    sort(items.begin(),items.end(),[](auto&a,auto&b){\n        return (double)a.first/a.second > (double)b.first/b.second;\n    });\n    double val=0;\n    for(auto&[v,w]:items){\n        if(W>=w){val+=v;W-=w;}\n        else{val+=(double)v/w*W;break;}\n    }\n    return val;\n}`}],
          hints:['Sort by value density (value/weight) descending.','Take greedily: whole item if fits, fraction otherwise.','Works because fractions are allowed (unlike 0-1 knapsack).'],
          solution:`// Sort by ratio, take greedily`, keyTakeaways:['Fractional knapsack: sort by value/weight. Greedy works, 0/1 needs DP.'] },
        { id:'jump-game-1', slug:'jump-game-1', title:'Jump Game I — Can You Reach the End?', type:'problem', difficulty:'medium', pattern:'Greedy',
          problemStatement:'Each element is max jump length from that position. Can you reach the last index?',
          examples:[{input:'[2,3,1,1,4]', output:'true'},{input:'[3,2,1,0,4]', output:'false'}],
          approaches:[{name:'Track max reachable index',intuition:'Track the farthest index reachable so far. If current > maxReach, stuck.',steps:['maxReach=0','For i from 0 to n: if i > maxReach → return false','maxReach = max(maxReach, i+nums[i])','Return true'],complexity:{time:'O(N)',space:'O(1)'},code:`bool canJump(vector<int>& nums){\n    int maxReach=0;\n    for(int i=0;i<nums.size();i++){\n        if(i>maxReach) return false;\n        maxReach=max(maxReach,i+nums[i]);\n    }\n    return true;\n}`}],
          hints:['Track maximum reachable index.','If i > maxReach at any point, you\'re stuck.','Update maxReach at each step.'],
          solution:`bool f(vector<int>&n){int m=0;for(int i=0;i<n.size();i++){if(i>m)return false;m=max(m,i+n[i]);}return true;}`,
          leetcodeUrl:'https://leetcode.com/problems/jump-game/', keyTakeaways:['Track max reachable. If stuck before reaching end → false.'] },
        { id:'jump-game-2', slug:'jump-game-2', title:'Jump Game II — Minimum Jumps', type:'problem', difficulty:'medium', pattern:'Greedy (BFS-like)',
          problemStatement:'Minimum number of jumps to reach last index (always reachable).',
          examples:[{input:'[2,3,1,1,4]', output:'2'}],
          approaches:[{name:'Greedy layer by layer',intuition:'Count jumps like BFS levels. At each jump, find the farthest reachable in current range.',steps:['jumps=0, curEnd=0, farthest=0','For i from 0 to n-2: farthest=max(farthest, i+nums[i])','If i==curEnd: jumps++, curEnd=farthest'],complexity:{time:'O(N)',space:'O(1)'},code:`int jump(vector<int>& nums){\n    int jumps=0,curEnd=0,farthest=0;\n    for(int i=0;i<nums.size()-1;i++){\n        farthest=max(farthest,i+nums[i]);\n        if(i==curEnd){jumps++;curEnd=farthest;}\n    }\n    return jumps;\n}`}],
          hints:['Think of it as BFS: each jump is a level.','curEnd = end of current jump range.','At curEnd: make one more jump, update curEnd to farthest.'],
          solution:`int f(vector<int>&n){int j=0,e=0,f=0;for(int i=0;i<n.size()-1;i++){f=max(f,i+n[i]);if(i==e){j++;e=f;}}return j;}`,
          leetcodeUrl:'https://leetcode.com/problems/jump-game-ii/', keyTakeaways:['Min jumps: greedy BFS levels. curEnd marks level boundary.'] },
        { id:'platform-trains', slug:'platform-trains', title:'Minimum Platforms for Railway Station', type:'problem', difficulty:'medium', pattern:'Greedy + Sort',
          problemStatement:'Given arrival and departure times of trains, find minimum platforms needed.',
          examples:[{input:'arr=[9,9,9,11], dep=[10,10,12,11]', output:'3'}],
          approaches:[{name:'Sort + sweep',intuition:'Sort arrivals and departures separately. Two-pointer sweep: if next arrival before next departure, need one more platform.',steps:['Sort arr and dep separately','Two pointers i,j; platforms=1, maxPlat=1','If arr[i]<=dep[j]: platforms++, i++; else platforms--, j++','maxPlat=max(maxPlat,platforms)'],complexity:{time:'O(N log N)',space:'O(1)'},code:`int minPlatforms(vector<int>&a,vector<int>&d){\n    sort(a.begin(),a.end()); sort(d.begin(),d.end());\n    int plat=1,maxP=1,i=1,j=0;\n    while(i<a.size()&&j<d.size()){\n        if(a[i]<=d[j]){plat++;i++;}\n        else{plat--;j++;}\n        maxP=max(maxP,plat);\n    }\n    return maxP;\n}`}],
          hints:['Sort arrivals and departures separately (not together).','Two-pointer sweep counts concurrent trains.','Increment on arrival, decrement on departure.'],
          solution:`// Sort sweep as above`, keyTakeaways:['Sweep line: sort events, track active count. O(N log N).'] },
        { id:'activity-selection', slug:'activity-selection', title:'N Meetings in One Room (Activity Selection)', type:'problem', difficulty:'easy', pattern:'Greedy',
          problemStatement:'Given n meetings with start and end times, find max non-overlapping meetings.',
          examples:[{input:'start=[1,3,0,5,8,5], end=[2,4,6,7,9,9]', output:'4'}],
          approaches:[{name:'Sort by end time',intuition:'Greedily pick meeting ending earliest. This leaves maximum room for future meetings.',steps:['Sort by end time','Pick first meeting','For each subsequent: if start >= last_end → pick it, update last_end'],complexity:{time:'O(N log N)',space:'O(1)'},code:`int maxMeetings(vector<int>&s,vector<int>&e){\n    vector<pair<int,int>> meet;\n    for(int i=0;i<s.size();i++) meet.push_back({e[i],s[i]});\n    sort(meet.begin(),meet.end());\n    int cnt=1,lastEnd=meet[0].first;\n    for(int i=1;i<meet.size();i++){\n        if(meet[i].second>lastEnd){cnt++;lastEnd=meet[i].first;}\n    }\n    return cnt;\n}`}],
          hints:['Sort by end time.','Always pick the meeting that ends earliest (greedy choice).','This maximizes time available for remaining meetings.'],
          solution:`// Sort by end time, greedily pick`, keyTakeaways:['Activity selection: sort by end time, greedily pick earliest-ending non-overlapping.'] },
      ],
    },
    {
      id: 'greedy-medium-hard', title: 'Medium/Hard Problems',
      topics: [
        { id:'non-overlapping-intervals', slug:'non-overlapping-intervals', title:'Non-Overlapping Intervals (Min Removals)', type:'problem', difficulty:'medium', pattern:'Greedy',
          problemStatement:'Find minimum intervals to remove so remaining are non-overlapping.',
          examples:[{input:'[[1,2],[2,3],[3,4],[1,3]]', output:'1', explanation:'Remove [1,3]'}],
          approaches:[{name:'Sort by end + greedy count',intuition:'Count max non-overlapping (activity selection). Answer = N - max non-overlapping.',steps:['Sort by end time','Count max non-overlapping meetings','Answer = N - count'],complexity:{time:'O(N log N)',space:'O(1)'},code:`int eraseOverlapIntervals(vector<vector<int>>& intervals){\n    sort(intervals.begin(),intervals.end(),[](auto&a,auto&b){return a[1]<b[1];});\n    int cnt=1,lastEnd=intervals[0][1];\n    for(int i=1;i<intervals.size();i++){\n        if(intervals[i][0]>=lastEnd){cnt++;lastEnd=intervals[i][1];}\n    }\n    return intervals.size()-cnt;\n}`}],
          hints:['Min removals = N - max non-overlapping.','Max non-overlapping = activity selection (sort by end).','Sort by end time, greedily keep.'],
          solution:`// Sort by end, count max non-overlapping, return N-count`,
          leetcodeUrl:'https://leetcode.com/problems/non-overlapping-intervals/', keyTakeaways:['Min removal = N - max kept. Activity selection is the foundation.'] },
        { id:'candy', slug:'candy', title:'Candy Distribution', type:'problem', difficulty:'hard', pattern:'Greedy',
          problemStatement:'N children in a row. Give each at least 1 candy. Children with higher rating than neighbor get more. Minimize total candies.',
          examples:[{input:'[1,0,2]', output:'5', explanation:'[2,1,2]'}],
          approaches:[{name:'Two-pass greedy',intuition:'Pass 1 (left→right): if rating[i] > rating[i-1], candy[i] = candy[i-1]+1. Pass 2 (right→left): same for right neighbor.',steps:['Init candy[i]=1 for all i','Left-right pass: if rating[i]>rating[i-1]: candy[i]=candy[i-1]+1','Right-left pass: if rating[i]>rating[i+1]: candy[i]=max(candy[i],candy[i+1]+1)','Sum all candies'],complexity:{time:'O(N)',space:'O(N)'},code:`int candy(vector<int>& r){\n    int n=r.size();\n    vector<int> c(n,1);\n    for(int i=1;i<n;i++) if(r[i]>r[i-1]) c[i]=c[i-1]+1;\n    for(int i=n-2;i>=0;i--) if(r[i]>r[i+1]) c[i]=max(c[i],c[i+1]+1);\n    return accumulate(c.begin(),c.end(),0);\n}`}],
          hints:['Two passes: left-to-right then right-to-left.','Each pass enforces one direction constraint.','Take max from both passes to satisfy both.'],
          solution:`// Two-pass as above`,
          leetcodeUrl:'https://leetcode.com/problems/candy/', keyTakeaways:['Two-pass greedy: L→R enforces left constraint, R→L enforces right constraint. Take max.'] },
        { id:'shortest-job-first', slug:'shortest-job-first', title:'Shortest Job First (Average Waiting Time)', type:'problem', difficulty:'easy', pattern:'Greedy',
          problemStatement:'Given burst times of CPU processes, find minimum average waiting time using Shortest Job First scheduling.',
          examples:[{input:'[4,1,3,2]', output:'2.5', explanation:'SJF order: [1,2,3,4], wait=[0,1,3,6], avg=10/4=2.5'}],
          approaches:[{name:'Sort burst times',intuition:'Process shortest job first minimizes waiting time (provable by exchange argument).',steps:['Sort burst times ascending','Compute prefix sum of burst times (= completion times)','Waiting time[i] = completion[i] - burst[i]','Average waiting time = sum / n'],complexity:{time:'O(N log N)',space:'O(1)'},code:`double shortestJobFirst(vector<int>& bt){\n    sort(bt.begin(),bt.end());\n    double wait=0;\n    int cum=0;\n    for(int i=0;i<bt.size();i++){wait+=cum;cum+=bt[i];}\n    return wait/bt.size();\n}`}],
          hints:['Sort burst times.','Waiting time for job i = sum of all previous burst times.','Accumulate waiting times.'],
          solution:`double f(vector<int>&b){sort(b.begin(),b.end());double w=0;int c=0;for(int x:b){w+=c;c+=x;}return w/b.size();}`,
          keyTakeaways:['SJF minimizes average waiting time. Sort burst times ascending.'] },
        { id:'merge-intervals', slug:'merge-intervals', title:'Insert Intervals / Merge Intervals', type:'problem', difficulty:'medium', pattern:'Greedy + Sort',
          problemStatement:'Given list of non-overlapping intervals sorted by start, insert a new interval and merge overlaps.',
          examples:[{input:'intervals=[[1,3],[6,9]], newInterval=[2,5]', output:'[[1,5],[6,9]]'}],
          approaches:[{name:'Linear scan and merge',intuition:'Add all intervals before new one. Merge overlapping. Add all after.',steps:['Add all intervals that end before new starts','Merge all overlapping: new.start=min(starts), new.end=max(ends)','Add merged interval','Add remaining'],complexity:{time:'O(N)',space:'O(N)'},code:`vector<vector<int>> insert(vector<vector<int>>& iv, vector<int>& nv){\n    vector<vector<int>> res;\n    int i=0,n=iv.size();\n    while(i<n&&iv[i][1]<nv[0]) res.push_back(iv[i++]);\n    while(i<n&&iv[i][0]<=nv[1]){nv[0]=min(nv[0],iv[i][0]);nv[1]=max(nv[1],iv[i][1]);i++;}\n    res.push_back(nv);\n    while(i<n) res.push_back(iv[i++]);\n    return res;\n}`}],
          hints:['Three phases: before, overlapping, after.','Overlap condition: existing.start <= new.end AND existing.end >= new.start.','Merge: take min of starts, max of ends.'],
          solution:`// Three-phase scan as above`,
          leetcodeUrl:'https://leetcode.com/problems/insert-interval/', keyTakeaways:['Insert interval: 3 phases. Overlap when intervals intersect.'] },
        { id:'valid-parenthesis-string', slug:'valid-parenthesis-string', title:'Valid Parenthesis String', type:'problem', difficulty:'hard', pattern:'Greedy',
          problemStatement:'"*" can be (, ), or empty. Check if string is valid.',
          examples:[{input:'"(*)"', output:'true'}],
          approaches:[{name:'Track open range',intuition:'Track range [minOpen, maxOpen] of possible open bracket counts. * can be (, ), or empty.',steps:['minOpen=0, maxOpen=0','For each char: if (: both++; if ): both--; if *: minOpen--, maxOpen++','If maxOpen<0: invalid (too many closing)','minOpen=max(0,minOpen) (can\'t have negative open)','Valid if minOpen==0 at end'],complexity:{time:'O(N)',space:'O(1)'},code:`bool checkValidString(string s){\n    int minO=0,maxO=0;\n    for(char c:s){\n        if(c=='('){minO++;maxO++;}\n        else if(c==')'){minO--;maxO--;}\n        else{minO--;maxO++;}\n        if(maxO<0) return false;\n        minO=max(0,minO);\n    }\n    return minO==0;\n}`}],
          hints:['Track possible range of open bracket counts.','* expands range by 1 in both directions.','If maxOpen < 0: too many ), invalid.'],
          solution:`bool f(string s){int mn=0,mx=0;for(char c:s){if(c=='('){mn++;mx++;}else if(c==')'){mn--;mx--;}else{mn--;mx++;}if(mx<0)return false;mn=max(0,mn);}return mn==0;}`,
          leetcodeUrl:'https://leetcode.com/problems/valid-parenthesis-string/', keyTakeaways:['Track min/max possible open count. * expands range. Valid if min reaches 0.'] },
      ],
    },
  ],
};
