import type { DSASection } from '@/types/dsa';

const leaf = (id: string, title: string, diff: 'easy'|'medium'|'hard', hint1: string, code: string, lc?: string) => ({
  id, slug: id, title, type: 'problem' as const, difficulty: diff,
  approaches: [{ name: 'Optimal', intuition: hint1, steps: [], complexity: { time: 'O(N)', space: 'O(H)' }, code }],
  hints: [hint1, 'Use recursion on left and right subtrees.', 'Base case: null node.'],
  solution: code,
  ...(lc ? { leetcodeUrl: lc } : {}),
  keyTakeaways: [],
});

export const treesSection: DSASection = {
  id: 'trees', slug: 'trees',
  title: 'Trees [Traversals, Medium, Hard Problems]',
  description: 'Binary trees: traversals, construction, path problems, LCA, and advanced tree manipulations.',
  icon: '🌳', color: 'from-green-600 to-emerald-700',
  subsections: [
    {
      id: 'trees-traversals', title: 'Traversals',
      topics: [
        { id:'tree-intro', slug:'tree-intro', title:'Introduction to Trees', type:'lesson', difficulty:'easy',
          introduction:'A tree is a hierarchical data structure with a root node, where each node has at most N children. Binary trees have at most 2 children.',
          theory:`**Terminology:** Root, Parent, Child, Leaf, Height, Depth, Level, Subtree.\n\n**Binary Tree Node:**\n\`\`\`cpp\nstruct TreeNode { int val; TreeNode *left, *right; };\n\`\`\`\n\n**Types:** Full (0 or 2 children), Complete (all levels full except last), Perfect (all leaves at same level), Balanced (height difference ≤ 1).\n\n**Height:** max depth of any leaf. Empty tree = -1. Single node = 0.\n\n**Traversals:**\n- Inorder (LNR): Left → Node → Right\n- Preorder (NLR): Node → Left → Right\n- Postorder (LRN): Left → Right → Node\n- Level order (BFS): Level by level`,
          codeExamples:[{title:'Binary Tree traversals',language:'cpp',code:`void inorder(TreeNode* r, vector<int>& v) {\n    if(!r) return;\n    inorder(r->left, v);\n    v.push_back(r->val);\n    inorder(r->right, v);\n}\nvoid preorder(TreeNode* r, vector<int>& v) {\n    if(!r) return;\n    v.push_back(r->val);\n    preorder(r->left, v);\n    preorder(r->right, v);\n}\nvoid postorder(TreeNode* r, vector<int>& v) {\n    if(!r) return;\n    postorder(r->left, v);\n    postorder(r->right, v);\n    v.push_back(r->val);\n}`}],
          keyTakeaways:['TreeNode struct. Inorder=LNR, Preorder=NLR, Postorder=LRN.','Binary tree ops are O(N) time, O(H) space (H=height, worst N).'] },
        leaf('inorder-traversal','Binary Tree Inorder Traversal (Iterative)','easy','Use a stack. Push left until null, then process node, move right.', `vector<int> inorder(TreeNode* r){\n    stack<TreeNode*> st; vector<int> res;\n    TreeNode* cur=r;\n    while(cur||!st.empty()){\n        while(cur){st.push(cur);cur=cur->left;}\n        cur=st.top();st.pop();\n        res.push_back(cur->val);\n        cur=cur->right;\n    }\n    return res;\n}`, 'https://leetcode.com/problems/binary-tree-inorder-traversal/'),
        leaf('preorder-traversal','Binary Tree Preorder Traversal (Iterative)','easy','Stack. Pop node, push right then left.', `vector<int> preorder(TreeNode* r){\n    if(!r) return {};\n    stack<TreeNode*> st; st.push(r); vector<int> res;\n    while(!st.empty()){\n        auto n=st.top();st.pop();\n        res.push_back(n->val);\n        if(n->right) st.push(n->right);\n        if(n->left) st.push(n->left);\n    }\n    return res;\n}`, 'https://leetcode.com/problems/binary-tree-preorder-traversal/'),
        leaf('postorder-traversal','Binary Tree Postorder Traversal (Iterative)','easy','Modified preorder (Node,Right,Left) then reverse.', `vector<int> postorder(TreeNode* r){\n    if(!r) return {};\n    stack<TreeNode*> st; st.push(r); vector<int> res;\n    while(!st.empty()){\n        auto n=st.top();st.pop();\n        res.push_back(n->val);\n        if(n->left) st.push(n->left);\n        if(n->right) st.push(n->right);\n    }\n    reverse(res.begin(),res.end());\n    return res;\n}`, 'https://leetcode.com/problems/binary-tree-postorder-traversal/'),
        { id:'level-order', slug:'level-order', title:'Level Order Traversal (BFS)', type:'problem', difficulty:'easy',
          problemStatement:'Return values level by level in a 2D vector.',
          examples:[{input:'Tree: 3→[9,20], 20→[15,7]', output:'[[3],[9,20],[15,7]]'}],
          approaches:[{name:'BFS with queue',intuition:'Use queue. For each level, process all current queue nodes, push their children.',steps:['Queue with root','For each level: size=queue.size(), process all, push children'],complexity:{time:'O(N)',space:'O(N)'},code:`vector<vector<int>> levelOrder(TreeNode* r){\n    if(!r) return {};\n    queue<TreeNode*> q; q.push(r);\n    vector<vector<int>> res;\n    while(!q.empty()){\n        int sz=q.size();\n        vector<int> level;\n        while(sz--){auto n=q.front();q.pop();level.push_back(n->val);if(n->left)q.push(n->left);if(n->right)q.push(n->right);}\n        res.push_back(level);\n    }\n    return res;\n}`}],
          hints:['BFS with queue.','Process fixed number of nodes per level (queue.size() at start of level).','Push children for next level.'],
          solution:`// BFS as above`, leetcodeUrl:'https://leetcode.com/problems/binary-tree-level-order-traversal/', keyTakeaways:['Level order = BFS. Capture queue size at start of each level.'] },
        leaf('height-tree','Height of a Binary Tree','easy','Height = 1 + max(height(left), height(right)). Base: null → -1.',
          `int height(TreeNode* r){\n    if(!r) return -1;\n    return 1+max(height(r->left),height(r->right));\n}`),
        leaf('diameter-tree','Diameter of Binary Tree','easy','At each node: diameter = leftHeight + rightHeight + 2. Track max.',
          `int ans=0;\nint h(TreeNode* r){\n    if(!r) return -1;\n    int l=h(r->left),ri=h(r->right);\n    ans=max(ans,l+ri+2);\n    return 1+max(l,ri);\n}`, 'https://leetcode.com/problems/diameter-of-binary-tree/'),
        leaf('max-depth-tree','Maximum Depth of Binary Tree','easy','Depth = 1 + max(depth(left), depth(right)).',
          `int maxDepth(TreeNode* r){\n    if(!r) return 0;\n    return 1+max(maxDepth(r->left),maxDepth(r->right));\n}`, 'https://leetcode.com/problems/maximum-depth-of-binary-tree/'),
        leaf('check-balanced','Check if Tree is Balanced','easy','At each node: if |height(left)-height(right)| > 1, return -1 (unbalanced).',
          `int check(TreeNode* r){\n    if(!r) return 0;\n    int l=check(r->left);\n    if(l==-1) return -1;\n    int ri=check(r->right);\n    if(ri==-1) return -1;\n    if(abs(l-ri)>1) return -1;\n    return 1+max(l,ri);\n}\nbool isBalanced(TreeNode* r){return check(r)!=-1;}`, 'https://leetcode.com/problems/balanced-binary-tree/'),
      ],
    },
    {
      id: 'trees-medium', title: 'Medium Problems',
      topics: [
        leaf('boundary-traversal','Boundary Traversal of Binary Tree','medium','Left boundary (excl leaves) + All leaves (L→R) + Right boundary (excl leaves, reversed).',
          `void leftBound(TreeNode*r,vector<int>&v){if(!r||(!r->left&&!r->right))return;v.push_back(r->val);if(r->left)leftBound(r->left,v);else leftBound(r->right,v);}\nvoid leaves(TreeNode*r,vector<int>&v){if(!r)return;if(!r->left&&!r->right){v.push_back(r->val);return;}leaves(r->left,v);leaves(r->right,v);}\nvoid rightBound(TreeNode*r,vector<int>&v){if(!r||(!r->left&&!r->right))return;if(r->right)rightBound(r->right,v);else rightBound(r->left,v);v.push_back(r->val);}`),
        leaf('vertical-order','Vertical Order Traversal','medium','BFS with (col, row) tracking. Sort by (col, row, val). Group by col.',
          `vector<vector<int>> verticalTraversal(TreeNode* r){\n    map<int,map<int,multiset<int>>> m;\n    queue<tuple<TreeNode*,int,int>> q;\n    q.push({r,0,0});\n    while(!q.empty()){\n        auto[n,row,col]=q.front();q.pop();\n        m[col][row].insert(n->val);\n        if(n->left)q.push({n->left,row+1,col-1});\n        if(n->right)q.push({n->right,row+1,col+1});\n    }\n    vector<vector<int>> res;\n    for(auto&[c,rm]:m){vector<int>col;for(auto&[r,s]:rm)for(int v:s)col.push_back(v);res.push_back(col);}\n    return res;\n}`, 'https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/'),
        leaf('top-view','Top View of Binary Tree','medium','BFS with horizontal distance (hd). Keep first (topmost) node at each hd.',
          `map<int,int> top; // hd -> first node val\nvoid bfs(TreeNode*r){queue<pair<TreeNode*,int>>q;q.push({r,0});while(!q.empty()){auto[n,hd]=q.front();q.pop();if(!top.count(hd))top[hd]=n->val;if(n->left)q.push({n->left,hd-1});if(n->right)q.push({n->right,hd+1});}}`),
        leaf('bottom-view','Bottom View of Binary Tree','medium','BFS with hd. Update (overwrite) node at each hd — last (bottommost) wins.',
          `map<int,int> bot;\nvoid bfs(TreeNode*r){queue<pair<TreeNode*,int>>q;q.push({r,0});while(!q.empty()){auto[n,hd]=q.front();q.pop();bot[hd]=n->val;if(n->left)q.push({n->left,hd-1});if(n->right)q.push({n->right,hd+1});}}`),
        leaf('right-side-view','Right Side View of Binary Tree','easy','Level order BFS. For each level, take the last element.',
          `vector<int> rightSideView(TreeNode*r){\n    if(!r) return {};\n    queue<TreeNode*>q;q.push(r);vector<int>res;\n    while(!q.empty()){int sz=q.size();for(int i=0;i<sz;i++){auto n=q.front();q.pop();if(i==sz-1)res.push_back(n->val);if(n->left)q.push(n->left);if(n->right)q.push(n->right);}}\n    return res;\n}`, 'https://leetcode.com/problems/binary-tree-right-side-view/'),
        leaf('zigzag-traversal','Zigzag Level Order Traversal','medium','Level order. Reverse alternate levels before adding to result.',
          `vector<vector<int>> zigzag(TreeNode*r){\n    if(!r)return {};\n    queue<TreeNode*>q;q.push(r);vector<vector<int>>res;bool lr=true;\n    while(!q.empty()){int sz=q.size();vector<int>lev;\n        for(int i=0;i<sz;i++){auto n=q.front();q.pop();lev.push_back(n->val);if(n->left)q.push(n->left);if(n->right)q.push(n->right);}\n        if(!lr)reverse(lev.begin(),lev.end());res.push_back(lev);lr=!lr;}\n    return res;\n}`, 'https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/'),
        leaf('path-sum','Path Sum II (Root to Leaf Paths with Target)', 'medium','DFS, carry current path and remaining sum. At leaf, check if sum==target.',
          `void dfs(TreeNode*r,int t,vector<int>&cur,vector<vector<int>>&res){\n    if(!r) return;\n    cur.push_back(r->val);\n    if(!r->left&&!r->right&&r->val==t){res.push_back(cur);}\n    dfs(r->left,t-r->val,cur,res);\n    dfs(r->right,t-r->val,cur,res);\n    cur.pop_back();\n}`, 'https://leetcode.com/problems/path-sum-ii/'),
        leaf('max-path-sum','Binary Tree Maximum Path Sum','hard','At each node: gain = max(0, maxGain(left)) + max(0, maxGain(right)) + val. Track global max.',
          `int ans=INT_MIN;\nint f(TreeNode*r){if(!r)return 0;int l=max(0,f(r->left)),ri=max(0,f(r->right));ans=max(ans,l+ri+r->val);return max(l,ri)+r->val;}\nint maxPathSum(TreeNode*r){f(r);return ans;}`, 'https://leetcode.com/problems/binary-tree-maximum-path-sum/'),
        leaf('lca-binary-tree','Lowest Common Ancestor of Binary Tree','medium','If root==p or root==q, return root. Recurse left and right. If both non-null, root is LCA.',
          `TreeNode* lca(TreeNode*r,TreeNode*p,TreeNode*q){\n    if(!r||r==p||r==q) return r;\n    auto l=lca(r->left,p,q),ri=lca(r->right,p,q);\n    if(l&&ri) return r;\n    return l?l:ri;\n}`, 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/'),
        leaf('construct-inorder-preorder','Construct Tree from Preorder and Inorder','medium','Root = preorder[0]. Find root in inorder. Left size = root index in inorder. Recurse.',
          `TreeNode* build(vector<int>&pre,int ps,int pe,vector<int>&in,int is,int ie,unordered_map<int,int>&m){\n    if(ps>pe||is>ie) return nullptr;\n    int rootVal=pre[ps];\n    TreeNode* root=new TreeNode(rootVal);\n    int ri=m[rootVal]-is;\n    root->left=build(pre,ps+1,ps+ri,in,is,m[rootVal]-1,m);\n    root->right=build(pre,ps+ri+1,pe,in,m[rootVal]+1,ie,m);\n    return root;\n}`, 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/'),
        leaf('flatten-tree-ll','Flatten Binary Tree to Linked List','medium','Morris traversal or reverse postorder: right = right subtree or right node. Left = null.',
          `void flatten(TreeNode* r){\n    while(r){\n        if(r->left){\n            TreeNode*pre=r->left;\n            while(pre->right) pre=pre->right;\n            pre->right=r->right;\n            r->right=r->left;\n            r->left=nullptr;\n        }\n        r=r->right;\n    }\n}`, 'https://leetcode.com/problems/flatten-binary-tree-to-linked-list/'),
        leaf('symmetric-tree','Symmetric Tree (Mirror Check)','easy','Check if left subtree is mirror of right subtree recursively.',
          `bool mirror(TreeNode*l,TreeNode*r){\n    if(!l&&!r) return true;\n    if(!l||!r) return false;\n    return l->val==r->val&&mirror(l->left,r->right)&&mirror(l->right,r->left);\n}\nbool isSymmetric(TreeNode*r){return mirror(r->left,r->right);}`, 'https://leetcode.com/problems/symmetric-tree/'),
      ],
    },
    {
      id: 'trees-hard', title: 'Hard Problems',
      topics: [
        leaf('root-to-node-path','Root to Node Path in Binary Tree','medium','DFS carrying current path. Add to result when node found.',
          `bool getPath(TreeNode*r,int t,vector<int>&path){\n    if(!r) return false;\n    path.push_back(r->val);\n    if(r->val==t) return true;\n    if(getPath(r->left,t,path)||getPath(r->right,t,path)) return true;\n    path.pop_back();\n    return false;\n}`),
        leaf('nodes-at-k-distance','Nodes at Distance K from Target','hard','Find target, then BFS in all 3 directions (left, right, parent). Build parent map via DFS.',
          `// Build parent map, BFS from target with distance k\nunordered_map<TreeNode*,TreeNode*> parent;\nvoid findParents(TreeNode*r,TreeNode*p){if(!r)return;parent[r]=p;findParents(r->left,r);findParents(r->right,r);}`, 'https://leetcode.com/problems/all-nodes-distance-k-in-binary-tree/'),
        leaf('time-to-burn-tree','Time to Burn a Tree from a Node','hard','Same as nodes-at-distance-K but return max distance instead of collecting nodes.',
          `// BFS from burning node, track max distance = time to burn`),
        leaf('count-nodes-complete','Count Nodes in a Complete Binary Tree','medium','Use height property. If left height == right height, left subtree is perfect: 2^h-1. Else recurse.',
          `int h(TreeNode*r,bool left){if(!r)return 0;if(left) return 1+h(r->left,true);return 1+h(r->right,false);}\nint countNodes(TreeNode*r){if(!r)return 0;int l=h(r,true),ri=h(r,false);if(l==ri) return (1<<l)-1;return 1+countNodes(r->left)+countNodes(r->right);}`, 'https://leetcode.com/problems/count-complete-tree-nodes/'),
        leaf('unique-bst-count','Count Unique BSTs (Catalan Number)','hard','dp[n] = sum of dp[i-1]*dp[n-i] for i=1 to n. Catalan number.',
          `int numTrees(int n){\n    vector<int> dp(n+1,0);dp[0]=dp[1]=1;\n    for(int i=2;i<=n;i++) for(int j=1;j<=i;j++) dp[i]+=dp[j-1]*dp[i-j];\n    return dp[n];\n}`, 'https://leetcode.com/problems/unique-binary-search-trees/'),
        leaf('serialize-deserialize','Serialize and Deserialize Binary Tree','hard','Preorder traversal to string. Use # for null. Deserialize by reading tokens.',
          `string serialize(TreeNode* r){\n    if(!r) return "#,";\n    return to_string(r->val)+","+serialize(r->left)+serialize(r->right);\n}\nTreeNode* deserialize(queue<string>& q){\n    string s=q.front();q.pop();\n    if(s=="#") return nullptr;\n    TreeNode* r=new TreeNode(stoi(s));\n    r->left=deserialize(q);\n    r->right=deserialize(q);\n    return r;\n}`, 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/'),
        leaf('morris-traversal','Morris Inorder Traversal (O(1) Space)','hard','Threaded binary tree: connect rightmost node of left subtree to current node.',
          `void morris(TreeNode* r){\n    while(r){\n        if(!r->left){cout<<r->val<<" ";r=r->right;}\n        else{\n            TreeNode*pre=r->left;\n            while(pre->right&&pre->right!=r) pre=pre->right;\n            if(!pre->right){pre->right=r;r=r->left;}\n            else{pre->right=nullptr;cout<<r->val<<" ";r=r->right;}\n        }\n    }\n}`),
      ],
    },
  ],
};
