import type { DSASection } from '@/types/dsa';

export const bstSection: DSASection = {
  id: 'bst', slug: 'bst',
  title: 'Binary Search Trees [Concept and Problems]',
  description: 'BST property, search/insert/delete, validation, and advanced BST problems like recovering corrupted BSTs.',
  icon: '🔍', color: 'from-teal-500 to-green-600',
  subsections: [
    {
      id: 'bst-concepts', title: 'Concepts',
      topics: [
        { id:'bst-intro', slug:'bst-intro', title:'Introduction to BST', type:'lesson', difficulty:'easy',
          introduction:'A Binary Search Tree (BST) has the property: all nodes in left subtree < current < all nodes in right subtree. Enables O(log N) search, insert, delete for balanced BSTs.',
          theory:`**BST Property:** For any node N: left subtree values < N.val < right subtree values.\n\n**Inorder of BST = sorted array.** This is the key insight.\n\n**Operations:**\n- Search: compare and go left/right. O(H)\n- Insert: search to find position, insert. O(H)\n- Delete: 3 cases — leaf, one child, two children (replace with inorder successor)\n- Min/Max: go left/right till null\n\n**Height H:** O(log N) for balanced BST, O(N) worst case for degenerate (sorted input).\n\n**Self-balancing BSTs:** AVL tree (|balance|≤1), Red-Black tree (used in std::map). Both guarantee O(log N).`,
          codeExamples:[{title:'BST operations',language:'cpp',code:`struct TreeNode{int val;TreeNode*left,*right;};\n\nTreeNode* search(TreeNode*r,int x){\n    if(!r||r->val==x) return r;\n    if(x<r->val) return search(r->left,x);\n    return search(r->right,x);\n}\n\nTreeNode* insert(TreeNode*r,int x){\n    if(!r) return new TreeNode{x,nullptr,nullptr};\n    if(x<r->val) r->left=insert(r->left,x);\n    else r->right=insert(r->right,x);\n    return r;\n}\n\nTreeNode* findMin(TreeNode*r){\n    while(r->left) r=r->left; return r;\n}\n\nTreeNode* deleteNode(TreeNode*r,int x){\n    if(!r) return nullptr;\n    if(x<r->val) r->left=deleteNode(r->left,x);\n    else if(x>r->val) r->right=deleteNode(r->right,x);\n    else{\n        if(!r->left) return r->right;\n        if(!r->right) return r->left;\n        TreeNode*succ=findMin(r->right);\n        r->val=succ->val;\n        r->right=deleteNode(r->right,succ->val);\n    }\n    return r;\n}`}],
          keyTakeaways:['BST inorder = sorted sequence.','BST ops: O(log N) balanced, O(N) skewed.','Delete: replace with inorder successor (smallest in right subtree).'] },
        { id:'bst-search', slug:'bst-search', title:'Search in a BST', type:'problem', difficulty:'easy', pattern:'BST',
          problemStatement:'Search for a value in a BST and return the node.',
          examples:[{input:'BST=[4,2,7,1,3], val=2', output:'TreeNode with val=2'}],
          approaches:[{name:'Recursive compare',intuition:'Compare val with node. Go left if smaller, right if larger.',steps:['Base: null → return null','If root.val == val: return root','if val < root.val: search left; else search right'],complexity:{time:'O(H)',space:'O(H)'},code:`TreeNode* searchBST(TreeNode*r,int v){\n    if(!r||r->val==v) return r;\n    return v<r->val?searchBST(r->left,v):searchBST(r->right,v);\n}`}],
          hints:['Compare target with current node.','Go left if target < current, right if target > current.','Return node if found, nullptr if not.'],
          solution:`TreeNode* f(TreeNode*r,int v){if(!r||r->val==v)return r;return v<r->val?f(r->left,v):f(r->right,v);}`,
          leetcodeUrl:'https://leetcode.com/problems/search-in-a-binary-search-tree/', keyTakeaways:['BST search: O(H). Compare and go left/right.'] },
        { id:'ceil-floor-bst', slug:'ceil-floor-bst', title:'Ceil and Floor in BST', type:'problem', difficulty:'medium', pattern:'BST',
          problemStatement:'Find floor (largest value ≤ key) and ceil (smallest value ≥ key) in a BST.',
          examples:[{input:'BST=[8,4,12,2,6,10,14], key=11', output:'floor=10, ceil=12'}],
          approaches:[{name:'BST traversal',intuition:'For ceil: if root.val>=key, candidate=root.val, go left to find smaller valid. Else go right. For floor: symmetric.',steps:['For ceil: traverse BST, update ceil when root.val>=key, go left; else go right','For floor: update floor when root.val<=key, go right; else go left'],complexity:{time:'O(H)',space:'O(1)'},code:`int ceil(TreeNode*r,int key){\n    int c=-1;\n    while(r){if(r->val>=key){c=r->val;r=r->left;}else r=r->right;}\n    return c;\n}\nint floor(TreeNode*r,int key){\n    int f=-1;\n    while(r){if(r->val<=key){f=r->val;r=r->right;}else r=r->left;}\n    return f;\n}`}],
          hints:['Ceil: smallest value >= key. Go left when found candidate.','Floor: largest value <= key. Go right when found candidate.','Iterative O(H), O(1) space.'],
          solution:`// See above`, keyTakeaways:['BST ceil/floor: traverse and update candidate. O(H).'] },
        { id:'insert-into-bst', slug:'insert-into-bst', title:'Insert into a BST', type:'problem', difficulty:'easy', pattern:'BST',
          problemStatement:'Insert a value into a BST maintaining BST property.',
          examples:[{input:'BST=[4,2,7], val=5', output:'BST=[4,2,7,null,null,5]'}],
          approaches:[{name:'Recursive',intuition:'If null, insert here. If val < root, insert in left subtree. Else insert in right.',steps:['Base: null → return new node','Recurse left/right based on comparison'],complexity:{time:'O(H)',space:'O(H)'},code:`TreeNode* insertIntoBST(TreeNode*r,int v){\n    if(!r) return new TreeNode(v);\n    if(v<r->val) r->left=insertIntoBST(r->left,v);\n    else r->right=insertIntoBST(r->right,v);\n    return r;\n}`}],
          hints:['Recursively go left/right.','Base case: null → create new node.','Return root after modification.'],
          solution:`TreeNode* f(TreeNode*r,int v){if(!r)return new TreeNode(v);if(v<r->val)r->left=f(r->left,v);else r->right=f(r->right,v);return r;}`,
          leetcodeUrl:'https://leetcode.com/problems/insert-into-a-binary-search-tree/', keyTakeaways:['BST insert: O(H). Go left/right until null, insert.'] },
        { id:'delete-node-bst', slug:'delete-node-bst', title:'Delete Node in a BST', type:'problem', difficulty:'medium', pattern:'BST',
          problemStatement:'Delete a node with given key from BST. Return modified BST root.',
          examples:[{input:'BST=[5,3,6,2,4,null,7], key=3', output:'BST without node 3'}],
          approaches:[{name:'3-case delete',intuition:'Case 1: leaf (no children) → just remove. Case 2: one child → replace with child. Case 3: two children → replace val with inorder successor, delete successor.',steps:['Find node (recurse left/right)','Case 1: both children null → return null','Case 2: one null → return other','Case 3: find min in right subtree (inorder successor), copy val, delete successor'],complexity:{time:'O(H)',space:'O(H)'},code:`TreeNode* deleteNode(TreeNode*r,int k){\n    if(!r) return nullptr;\n    if(k<r->val) r->left=deleteNode(r->left,k);\n    else if(k>r->val) r->right=deleteNode(r->right,k);\n    else{\n        if(!r->left) return r->right;\n        if(!r->right) return r->left;\n        TreeNode*succ=r->right;\n        while(succ->left) succ=succ->left;\n        r->val=succ->val;\n        r->right=deleteNode(r->right,succ->val);\n    }\n    return r;\n}`}],
          hints:['3 cases: leaf, 1 child, 2 children.','2 children: replace with inorder successor (min of right subtree).','Then delete the successor (which now has at most 1 child).'],
          solution:`// 3-case delete as above`,
          leetcodeUrl:'https://leetcode.com/problems/delete-node-in-a-bst/', keyTakeaways:['BST delete 3 cases. 2-children: swap with inorder successor, delete successor.'] },
        { id:'validate-bst', slug:'validate-bst', title:'Validate Binary Search Tree', type:'problem', difficulty:'medium', pattern:'BST',
          problemStatement:'Check if a binary tree is a valid BST.',
          examples:[{input:'Tree=[2,1,3]', output:'true'},{input:'Tree=[5,1,4,null,null,3,6]', output:'false'}],
          approaches:[{name:'Range validation',intuition:'Each node must be within (min, max) range. Pass updated range down recursively.',steps:['validate(root, -INF, +INF)','Left child: validate(left, min, root.val)','Right child: validate(right, root.val, max)','Base: null → true'],complexity:{time:'O(N)',space:'O(H)'},code:`bool validate(TreeNode*r,long mn,long mx){\n    if(!r) return true;\n    if(r->val<=mn||r->val>=mx) return false;\n    return validate(r->left,mn,r->val)&&validate(r->right,r->val,mx);\n}\nbool isValidBST(TreeNode*r){return validate(r,LLONG_MIN,LLONG_MAX);}`}],
          hints:['Each node has a valid range (min, max).','Left subtree: max = current node val.','Right subtree: min = current node val.'],
          solution:`bool v(TreeNode*r,long mn,long mx){if(!r)return true;if(r->val<=mn||r->val>=mx)return false;return v(r->left,mn,r->val)&&v(r->right,r->val,mx);}`,
          leetcodeUrl:'https://leetcode.com/problems/validate-binary-search-tree/', keyTakeaways:['Validate BST: range check. Each node must be in (min, max).'] },
      ],
    },
    {
      id: 'bst-problems', title: 'Problems on BSTs',
      topics: [
        { id:'lca-bst', slug:'lca-bst', title:'LCA in Binary Search Tree', type:'problem', difficulty:'easy', pattern:'BST',
          problemStatement:'Find LCA of two nodes p and q in a BST.',
          examples:[{input:'BST=[6,2,8,0,4,7,9], p=2,q=4', output:'2'}],
          approaches:[{name:'BST property',intuition:'LCA is the node where p and q split. If both smaller than root, go left. If both larger, go right. Else root is LCA.',steps:['While root: if p.val < root.val AND q.val < root.val → go left','Else if both > root.val → go right','Else root is LCA'],complexity:{time:'O(H)',space:'O(1)'},code:`TreeNode* lcaBST(TreeNode*r,TreeNode*p,TreeNode*q){\n    while(r){\n        if(p->val<r->val&&q->val<r->val) r=r->left;\n        else if(p->val>r->val&&q->val>r->val) r=r->right;\n        else return r;\n    }\n    return nullptr;\n}`}],
          hints:['Both smaller: go left. Both larger: go right. Otherwise: LCA.','Exploit BST property — no need to search both subtrees.'],
          solution:`TreeNode* f(TreeNode*r,TreeNode*p,TreeNode*q){while(r){if(p->val<r->val&&q->val<r->val)r=r->left;else if(p->val>r->val&&q->val>r->val)r=r->right;else return r;}return nullptr;}`,
          leetcodeUrl:'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/', keyTakeaways:['BST LCA is O(H) — both go same direction until split point.'] },
        { id:'construct-bst-preorder', slug:'construct-bst-preorder', title:'Construct BST from Preorder Traversal', type:'problem', difficulty:'medium', pattern:'BST',
          problemStatement:'Given preorder traversal of a BST, reconstruct it.',
          examples:[{input:'[8,5,1,7,10,12]', output:'BST with those values'}],
          approaches:[{name:'Range-based insert',intuition:'Use upper bound to know which preorder elements belong to left subtree.',steps:['First element is root','Elements in (min, root.val) go to left subtree','Elements in (root.val, max) go to right subtree','Track index with pointer'],complexity:{time:'O(N)',space:'O(N)'},code:`TreeNode* build(vector<int>&p,int&i,int mn,int mx){\n    if(i>=p.size()||p[i]<=mn||p[i]>=mx) return nullptr;\n    TreeNode*r=new TreeNode(p[i++]);\n    r->left=build(p,i,mn,r->val);\n    r->right=build(p,i,r->val,mx);\n    return r;\n}\nTreeNode* bstFromPreorder(vector<int>& p){\n    int i=0; return build(p,i,INT_MIN,INT_MAX);\n}`}],
          hints:['First element is always root in preorder.','Use range (mn, mx) to determine left vs right subtree.','Pass index by reference to track position across calls.'],
          solution:`// Range-based build as above`, leetcodeUrl:'https://leetcode.com/problems/construct-binary-search-tree-from-preorder-traversal/', keyTakeaways:['Construct BST from preorder: use valid range to route elements left or right.'] },
        { id:'bst-to-greater-sum','slug':'bst-to-greater-sum', title:'BST to Greater Sum Tree', type:'problem', difficulty:'medium', pattern:'BST',
          problemStatement:'Convert BST such that each node contains sum of all values greater than it.',
          examples:[{input:'BST=[4,1,6,0,2,5,7]', output:'Each node replaced by cumulative sum from right'}],
          approaches:[{name:'Reverse inorder (RNL)',intuition:'Inorder of BST is sorted. Reverse inorder (R→N→L) processes in descending order. Accumulate sum.',steps:['Traverse right → node → left','Maintain running sum','Update each node.val = runningSum'],complexity:{time:'O(N)',space:'O(H)'},code:`int runSum=0;\nvoid convert(TreeNode*r){\n    if(!r) return;\n    convert(r->right);\n    runSum+=r->val;\n    r->val=runSum;\n    convert(r->left);\n}`}],
          hints:['Reverse inorder (right-node-left) = descending order for BST.','Accumulate sum as you traverse.','Update each node\'s value to accumulated sum.'],
          solution:`int s=0;void f(TreeNode*r){if(!r)return;f(r->right);s+=r->val;r->val=s;f(r->left);}`,
          leetcodeUrl:'https://leetcode.com/problems/binary-search-tree-to-greater-sum-tree/', keyTakeaways:['Greater sum tree: reverse inorder + running sum.'] },
        { id:'recover-bst', slug:'recover-bst', title:'Recover BST (Two Nodes Swapped)', type:'problem', difficulty:'hard', pattern:'BST',
          problemStatement:'Exactly two nodes of a BST were swapped. Recover the BST.',
          examples:[{input:'Corrupted BST with 2 swapped nodes', output:'Correct BST'}],
          approaches:[{name:'Inorder with prev tracking',intuition:'Inorder of valid BST is sorted. Find where prev > curr — those are the swapped nodes.',steps:['Inorder traversal tracking prev','First violation: first=prev, second=curr','Second violation (if exists): update second=curr','Swap first and second values'],complexity:{time:'O(N)',space:'O(H)'},code:`TreeNode *first=nullptr,*second=nullptr,*prev=nullptr;\nvoid inorder(TreeNode*r){\n    if(!r) return;\n    inorder(r->left);\n    if(prev&&prev->val>r->val){\n        if(!first) first=prev;\n        second=r;\n    }\n    prev=r;\n    inorder(r->right);\n}\nvoid recoverTree(TreeNode*r){\n    inorder(r);\n    swap(first->val,second->val);\n}`}],
          hints:['Inorder should be sorted. Find violations.','First violation: first=prev, second=curr.','Second violation: update second only.'],
          solution:`// Inorder violation tracking as above`,
          leetcodeUrl:'https://leetcode.com/problems/recover-binary-search-tree/', keyTakeaways:['Recover BST: find inorder violations. First violation gives first node, second gives other node.'] },
        { id:'kth-smallest-bst', slug:'kth-smallest-bst', title:'Kth Smallest Element in BST', type:'problem', difficulty:'easy', pattern:'BST',
          problemStatement:'Find the Kth smallest element in a BST.',
          examples:[{input:'BST=[3,1,4,null,2], K=1', output:'1'}],
          approaches:[{name:'Inorder traversal count',intuition:'Inorder of BST is sorted. Return the Kth element encountered.',steps:['Inorder traversal','Decrement K at each node','Return val when K==0'],complexity:{time:'O(K)',space:'O(H)'},code:`int cnt,res;\nvoid inorder(TreeNode*r,int k){\n    if(!r) return;\n    inorder(r->left,k);\n    if(++cnt==k){res=r->val;return;}\n    inorder(r->right,k);\n}\nint kthSmallest(TreeNode*r,int k){cnt=0;inorder(r,k);return res;}`}],
          hints:['BST inorder = sorted. Kth element in inorder = Kth smallest.','Counter increments at each visited node.','Return when counter reaches K.'],
          solution:`int c=0,r=0;void f(TreeNode*n,int k){if(!n)return;f(n->left,k);if(++c==k){r=n->val;return;}f(n->right,k);}\nint kthSmallest(TreeNode*r,int k){f(r,k);return r;}`,
          leetcodeUrl:'https://leetcode.com/problems/kth-smallest-element-in-a-bst/', keyTakeaways:['Kth smallest in BST = Kth element in inorder traversal.'] },
        { id:'merge-two-bsts', slug:'merge-two-bsts', title:'Merge Two BSTs into Sorted List', type:'problem', difficulty:'hard', pattern:'BST',
          problemStatement:'Merge two BSTs into a single sorted sequence without using extra space.',
          examples:[{input:'BST1=[3,1,2], BST2=[5,4,6]', output:'[1,2,3,4,5,6]'}],
          approaches:[{name:'Inorder iterative two-pointer',intuition:'Convert both BSTs to sorted doubly linked lists (in-place Morris or iterative inorder). Merge two sorted lists.',steps:['Get inorder iterator for each BST (using stack)','Two-pointer merge like merge sort\'s merge step'],complexity:{time:'O(M+N)',space:'O(H1+H2)'},code:`// Use two stacks for iterative inorder of both BSTs\n// At each step: compare tops, take smaller, advance that iterator`}],
          hints:['Inorder of BST = sorted. Two sorted sequences = merge step.','Use two stacks for iterative inorder traversal.','Merge like the merge step of merge sort.'],
          solution:`// Two stacks + merge step`, keyTakeaways:['Merge BSTs: inorder (sorted) + merge step = O(M+N).'] },
      ],
    },
  ],
};
