import type { DSASection } from '@/types/dsa';

const gp = (id: string, title: string, diff: 'easy'|'medium'|'hard', pattern: string, intuition: string, code: string, lc?: string) => ({
  id, slug: id, title, type: 'problem' as const, difficulty: diff, pattern,
  approaches: [{ name: 'Optimal', intuition, steps: [], complexity: { time: 'O(V+E)', space: 'O(V+E)' }, code }],
  hints: [intuition, 'Build adjacency list first.', 'Handle visited array to avoid cycles.'],
  solution: code, ...(lc ? { leetcodeUrl: lc } : {}), keyTakeaways: [],
});

export const graphsSection: DSASection = {
  id: 'graphs', slug: 'graphs',
  title: 'Graphs [Concepts, BFS, DFS, Topo Sort, Shortest Path, MST]',
  description: 'Complete graph mastery: BFS/DFS patterns, topological sort, shortest paths (Dijkstra, Bellman-Ford), and MST (Prim, Kruskal).',
  icon: '🕸️', color: 'from-indigo-500 to-violet-600',
  subsections: [
    {
      id: 'graph-learning', title: 'Graph Concepts',
      topics: [
        { id:'graph-intro', slug:'graph-intro', title:'Graph Representation and BFS', type:'lesson', difficulty:'easy',
          introduction:'A graph is a set of vertices (nodes) connected by edges. Directed or undirected, weighted or unweighted.',
          theory:`**Representations:**\n1. Adjacency Matrix: O(V²) space, O(1) edge check\n2. Adjacency List: O(V+E) space, O(degree) edge check — preferred\n\n**BFS (Breadth-First Search):** Level by level. Uses queue. Finds shortest path in unweighted graph.\n**DFS (Depth-First Search):** Goes deep first. Uses stack (or recursion). Detects cycles, finds paths.\n\n**Graph terms:** Degree, path, cycle, connected, bipartite, weighted, DAG (directed acyclic graph).`,
          codeExamples:[{title:'BFS and DFS',language:'cpp',code:`// Build adjacency list\nvector<vector<int>> adj(V);\nfor(auto [u,v] : edges) { adj[u].push_back(v); adj[v].push_back(u); }\n\n// BFS from src\nvoid bfs(int src, vector<bool>& vis) {\n    queue<int> q; q.push(src); vis[src]=true;\n    while(!q.empty()){\n        int u=q.front(); q.pop();\n        for(int v:adj[u]) if(!vis[v]){vis[v]=true;q.push(v);}\n    }\n}\n\n// DFS from src\nvoid dfs(int u, vector<bool>& vis) {\n    vis[u]=true;\n    for(int v:adj[u]) if(!vis[v]) dfs(v,vis);\n}`}],
          keyTakeaways:['Adjacency list O(V+E). BFS with queue (shortest path). DFS with recursion (cycle detection, paths).'] },
        gp('bfs-disconnected','BFS of Graph (including disconnected)','easy','BFS','For each unvisited vertex, start BFS. Handles disconnected components.',`void bfsAll(int V,vector<vector<int>>&adj){\n    vector<bool>vis(V,false);\n    for(int i=0;i<V;i++) if(!vis[i]){\n        queue<int>q;q.push(i);vis[i]=true;\n        while(!q.empty()){int u=q.front();q.pop();for(int v:adj[u])if(!vis[v]){vis[v]=true;q.push(v);}}\n    }\n}`),
        gp('dfs-graph','DFS of Graph','easy','DFS','Mark visited, recurse neighbors. Run for all components.',`void dfs(int u,vector<bool>&vis,vector<vector<int>>&adj){\n    vis[u]=true;\n    for(int v:adj[u]) if(!vis[v]) dfs(v,vis,adj);\n}`),
      ],
    },
    {
      id: 'graph-bfs-dfs', title: 'BFS/DFS Problems',
      topics: [
        gp('number-of-provinces','Number of Provinces','medium','Union-Find / DFS','Count connected components. Province = group of directly/indirectly connected cities.',`int findProvinces(vector<vector<int>>&isConn){\n    int n=isConn.size(),cnt=0;\n    vector<bool>vis(n,false);\n    function<void(int)>dfs=[&](int u){vis[u]=true;for(int v=0;v<n;v++)if(!vis[v]&&isConn[u][v])dfs(v);};\n    for(int i=0;i<n;i++) if(!vis[i]){dfs(i);cnt++;}\n    return cnt;\n}`,'https://leetcode.com/problems/number-of-provinces/'),
        gp('number-of-islands','Number of Islands','medium','DFS/BFS on Grid','Mark visited islands (change 1→0 or use visited array). Count DFS calls from unvisited 1-cells.',`int numIslands(vector<vector<char>>&g){\n    int r=g.size(),c=g[0].size(),cnt=0;\n    function<void(int,int)>dfs=[&](int i,int j){\n        if(i<0||i>=r||j<0||j>=c||g[i][j]!='1') return;\n        g[i][j]='0';\n        dfs(i+1,j);dfs(i-1,j);dfs(i,j+1);dfs(i,j-1);\n    };\n    for(int i=0;i<r;i++) for(int j=0;j<c;j++) if(g[i][j]=='1'){dfs(i,j);cnt++;}\n    return cnt;\n}`,'https://leetcode.com/problems/number-of-islands/'),
        gp('flood-fill','Flood Fill','easy','DFS on Grid','Change starting pixel and all connected same-color pixels to new color.',`void dfs(vector<vector<int>>&img,int i,int j,int oc,int nc){\n    if(i<0||i>=img.size()||j<0||j>=img[0].size()||img[i][j]!=oc) return;\n    img[i][j]=nc;\n    dfs(img,i+1,j,oc,nc);dfs(img,i-1,j,oc,nc);dfs(img,i,j+1,oc,nc);dfs(img,i,j-1,oc,nc);\n}\nvector<vector<int>> floodFill(vector<vector<int>>&img,int r,int c,int nc){\n    int oc=img[r][c];\n    if(oc!=nc) dfs(img,r,c,oc,nc);\n    return img;\n}`,'https://leetcode.com/problems/flood-fill/'),
        gp('01-matrix','01 Matrix (Distance to Nearest 0)','medium','Multi-source BFS','Start BFS from all 0-cells simultaneously. Distance of each 1 = BFS level when first visited.',`vector<vector<int>> updateMatrix(vector<vector<int>>&mat){\n    int m=mat.size(),n=mat[0].size();\n    vector<vector<int>>dist(m,vector<int>(n,INT_MAX));\n    queue<pair<int,int>>q;\n    for(int i=0;i<m;i++) for(int j=0;j<n;j++) if(mat[i][j]==0){dist[i][j]=0;q.push({i,j});}\n    int dr[]={1,-1,0,0},dc[]={0,0,1,-1};\n    while(!q.empty()){auto[r,c]=q.front();q.pop();for(int d=0;d<4;d++){int nr=r+dr[d],nc=c+dc[d];if(nr>=0&&nr<m&&nc>=0&&nc<n&&dist[nr][nc]>dist[r][c]+1){dist[nr][nc]=dist[r][c]+1;q.push({nr,nc});}}}\n    return dist;\n}`,'https://leetcode.com/problems/01-matrix/'),
        gp('rotten-oranges','Rotten Oranges','medium','Multi-source BFS','All rotten oranges rot neighbors simultaneously. Multi-source BFS. Time = BFS levels.',`int orangesRotting(vector<vector<int>>&g){\n    int m=g.size(),n=g[0].size(),fresh=0,mins=0;\n    queue<pair<int,int>>q;\n    for(int i=0;i<m;i++) for(int j=0;j<n;j++){if(g[i][j]==2)q.push({i,j});if(g[i][j]==1)fresh++;}\n    int dr[]={1,-1,0,0},dc[]={0,0,1,-1};\n    while(!q.empty()&&fresh){\n        int sz=q.size();mins++;\n        while(sz--){auto[r,c]=q.front();q.pop();for(int d=0;d<4;d++){int nr=r+dr[d],nc=c+dc[d];if(nr>=0&&nr<m&&nc>=0&&nc<n&&g[nr][nc]==1){g[nr][nc]=2;fresh--;q.push({nr,nc});}}}\n    }\n    return fresh?-1:mins;\n}`,'https://leetcode.com/problems/rotting-oranges/'),
        gp('detect-cycle-undirected','Detect Cycle in Undirected Graph','medium','BFS/DFS with parent tracking','In BFS: if neighbor is visited and not parent → cycle. In DFS: same.',`bool hasCycle(int V,vector<vector<int>>&adj){\n    vector<bool>vis(V,false);\n    function<bool(int,int)>dfs=[&](int u,int p)->bool{\n        vis[u]=true;\n        for(int v:adj[u]){\n            if(!vis[v]){if(dfs(v,u))return true;}\n            else if(v!=p) return true;\n        }\n        return false;\n    };\n    for(int i=0;i<V;i++) if(!vis[i]&&dfs(i,-1)) return true;\n    return false;\n}`),
        gp('detect-cycle-directed','Detect Cycle in Directed Graph','medium','DFS with path tracking (dfsVis)','Use two visited arrays: visited and inStack. Cycle if neighbor is in current DFS path.',`bool dfs(int u,vector<bool>&vis,vector<bool>&stack,vector<vector<int>>&adj){\n    vis[u]=stack[u]=true;\n    for(int v:adj[u]){\n        if(!vis[v]&&dfs(v,vis,stack,adj)) return true;\n        if(stack[v]) return true;\n    }\n    stack[u]=false; return false;\n}`),
        gp('bipartite-check','Is Graph Bipartite? (2-Colorable)','medium','BFS 2-Coloring','Try to 2-color graph. If adjacent nodes have same color → not bipartite.',`bool isBipartite(vector<vector<int>>&adj,int V){\n    vector<int>color(V,-1);\n    for(int s=0;s<V;s++){\n        if(color[s]!=-1) continue;\n        queue<int>q;q.push(s);color[s]=0;\n        while(!q.empty()){int u=q.front();q.pop();for(int v:adj[u]){if(color[v]==-1){color[v]=1-color[u];q.push(v);}else if(color[v]==color[u])return false;}}\n    }\n    return true;\n}`,'https://leetcode.com/problems/is-graph-bipartite/'),
        gp('word-ladder','Word Ladder','hard','BFS (shortest path in word graph)','BFS from beginWord. Each step: change one char, if in wordList add to queue. Count levels.',`int ladderLength(string b,string e,vector<string>&wl){\n    unordered_set<string>ws(wl.begin(),wl.end());\n    queue<pair<string,int>>q;q.push({b,1});\n    while(!q.empty()){auto[w,d]=q.front();q.pop();if(w==e)return d;for(int i=0;i<w.size();i++){string tmp=w;for(char c='a';c<='z';c++){tmp[i]=c;if(ws.count(tmp)){ws.erase(tmp);q.push({tmp,d+1});}}}}\n    return 0;\n}`,'https://leetcode.com/problems/word-ladder/'),
      ],
    },
    {
      id: 'topo-sort', title: 'Topological Sort and Problems',
      topics: [
        { id:'topo-sort-dfs', slug:'topo-sort-dfs', title:'Topological Sort (DFS)', type:'lesson', difficulty:'medium',
          introduction:'Topological sort of a DAG is a linear ordering where for every edge u→v, u appears before v. Only possible for DAGs.',
          theory:`**DFS approach:** Do DFS. After finishing all neighbors of u, push u to stack. Pop stack for topological order.\n\n**Kahn's algorithm (BFS):** Track in-degrees. Start with all 0-indegree nodes. Process queue, reduce neighbor indegrees, add 0-indegree neighbors to queue.\n\n**Applications:** Task scheduling, course prerequisites, build systems.`,
          codeExamples:[{title:'Topo Sort DFS + Kahns',language:'cpp',code:`// DFS approach\nvoid dfs(int u,vector<bool>&vis,stack<int>&st,vector<vector<int>>&adj){\n    vis[u]=true;\n    for(int v:adj[u]) if(!vis[v]) dfs(v,vis,st,adj);\n    st.push(u);\n}\nvector<int> topoSort(int V,vector<vector<int>>&adj){\n    vector<bool>vis(V,false); stack<int>st;\n    for(int i=0;i<V;i++) if(!vis[i]) dfs(i,vis,st,adj);\n    vector<int>res;\n    while(!st.empty()){res.push_back(st.top());st.pop();}\n    return res;\n}\n\n// Kahn's (BFS)\nvector<int> kahnSort(int V,vector<vector<int>>&adj){\n    vector<int>indeg(V,0);\n    for(int u=0;u<V;u++) for(int v:adj[u]) indeg[v]++;\n    queue<int>q;\n    for(int i=0;i<V;i++) if(!indeg[i]) q.push(i);\n    vector<int>res;\n    while(!q.empty()){int u=q.front();q.pop();res.push_back(u);for(int v:adj[u])if(--indeg[v]==0)q.push(v);}\n    return res; // size<V means cycle exists\n}`}],
          keyTakeaways:['Topo sort: only for DAGs.','DFS: push to stack after all neighbors.','Kahn: in-degree BFS. If result size < V → cycle detected.'] },
        gp('course-schedule','Course Schedule (Can Finish All Courses?)','medium','Topological Sort / Cycle Detection','Detect cycle in directed graph using Kahn\'s. If topo sort includes all courses → no cycle → can finish.',`bool canFinish(int n,vector<vector<int>>&prereqs){\n    vector<vector<int>>adj(n); vector<int>indeg(n,0);\n    for(auto&e:prereqs){adj[e[1]].push_back(e[0]);indeg[e[0]]++;}\n    queue<int>q;\n    for(int i=0;i<n;i++) if(!indeg[i]) q.push(i);\n    int cnt=0;\n    while(!q.empty()){int u=q.front();q.pop();cnt++;for(int v:adj[u])if(--indeg[v]==0)q.push(v);}\n    return cnt==n;\n}`,'https://leetcode.com/problems/course-schedule/'),
        gp('course-schedule-2','Course Schedule II (Order of Courses)','medium','Topological Sort','Return topo sort order. If cycle → impossible (return []).',`vector<int> findOrder(int n,vector<vector<int>>&prereqs){\n    vector<vector<int>>adj(n); vector<int>indeg(n,0);\n    for(auto&e:prereqs){adj[e[1]].push_back(e[0]);indeg[e[0]]++;}\n    queue<int>q;\n    for(int i=0;i<n;i++) if(!indeg[i]) q.push(i);\n    vector<int>res;\n    while(!q.empty()){int u=q.front();q.pop();res.push_back(u);for(int v:adj[u])if(--indeg[v]==0)q.push(v);}\n    return res.size()==n?res:vector<int>{};\n}`,'https://leetcode.com/problems/course-schedule-ii/'),
        gp('alien-dictionary','Alien Dictionary (Order of Characters)','hard','Topological Sort on Characters','Compare adjacent words to derive character ordering edges. Topo sort edges = alien character order.',`string alienOrder(vector<string>&words){\n    unordered_map<char,set<char>>adj; unordered_map<char,int>indeg;\n    for(char c:words[0]) indeg[c]=0;\n    for(int i=1;i<words.size();i++){\n        for(char c:words[i]) if(!indeg.count(c)) indeg[c]=0;\n        int mn=min(words[i-1].size(),words[i].size()); bool found=false;\n        for(int j=0;j<mn;j++) if(words[i-1][j]!=words[i][j]){if(!adj[words[i-1][j]].count(words[i][j])){adj[words[i-1][j]].insert(words[i][j]);indeg[words[i][j]]++;}found=true;break;}\n        if(!found&&words[i-1].size()>words[i].size()) return \"\";\n    }\n    queue<char>q;\n    for(auto&[c,d]:indeg) if(!d) q.push(c);\n    string res;\n    while(!q.empty()){char c=q.front();q.pop();res+=c;for(char v:adj[c])if(--indeg[v]==0)q.push(v);}\n    return res.size()==indeg.size()?res:\"\";\n}`),
      ],
    },
    {
      id: 'shortest-path', title: 'Shortest Path Algorithms',
      topics: [
        { id:'dijkstra', slug:'dijkstra', title:'Dijkstra\'s Shortest Path Algorithm', type:'lesson', difficulty:'medium',
          introduction:'Dijkstra finds shortest paths from a source to all vertices in a weighted graph with non-negative edges. Uses a min-heap for efficiency.',
          theory:`**Algorithm:**\n1. Initialize dist[src]=0, all others=INF\n2. Min-heap with (distance, vertex)\n3. Pop minimum. For each neighbor: if dist[u]+weight < dist[v]: update dist[v], push to heap\n4. Repeat until heap empty\n\n**Why not negative edges?** Dijkstra is greedy — once a vertex is finalized, it won't be updated. Negative edges can violate this. Use Bellman-Ford for negative edges.\n\n**Complexity:** O((V+E) log V) with min-heap.`,
          codeExamples:[{title:'Dijkstra',language:'cpp',code:`vector<int> dijkstra(int V,vector<vector<pair<int,int>>>&adj,int src){\n    vector<int>dist(V,INT_MAX);\n    priority_queue<pair<int,int>,vector<pair<int,int>>,greater<>>pq;\n    dist[src]=0; pq.push({0,src});\n    while(!pq.empty()){\n        auto[d,u]=pq.top();pq.pop();\n        if(d>dist[u]) continue; // outdated entry\n        for(auto[v,w]:adj[u]){\n            if(dist[u]+w<dist[v]){\n                dist[v]=dist[u]+w;\n                pq.push({dist[v],v});\n            }\n        }\n    }\n    return dist;\n}`}],
          keyTakeaways:['Dijkstra: O((V+E) log V). Non-negative edges only. Min-heap greedy approach.','Skip if d > dist[u] (stale heap entry).'] },
        gp('bellman-ford','Bellman-Ford (Detect Negative Cycles)','medium','Bellman-Ford','Relax all edges V-1 times. If can still relax on Vth iteration → negative cycle.',`vector<int> bellmanFord(int V,vector<tuple<int,int,int>>&edges,int src){\n    vector<int>dist(V,INT_MAX); dist[src]=0;\n    for(int i=0;i<V-1;i++) for(auto&[u,v,w]:edges) if(dist[u]!=INT_MAX&&dist[u]+w<dist[v]) dist[v]=dist[u]+w;\n    for(auto&[u,v,w]:edges) if(dist[u]!=INT_MAX&&dist[u]+w<dist[v]) {/* negative cycle */}\n    return dist;\n}`),
        gp('floyd-warshall','Floyd-Warshall All Pairs Shortest Path','hard','DP on all vertex pairs','dp[i][j][k] = shortest path from i to j using vertices 0..k as intermediates.',`vector<vector<int>> floydWarshall(int V,vector<vector<int>>&dist){\n    for(int k=0;k<V;k++) for(int i=0;i<V;i++) for(int j=0;j<V;j++)\n        if(dist[i][k]!=INT_MAX&&dist[k][j]!=INT_MAX)\n            dist[i][j]=min(dist[i][j],dist[i][k]+dist[k][j]);\n    return dist;\n}`),
        gp('path-with-min-effort','Path With Minimum Effort','medium','Dijkstra on Grid','State = (effort, r, c). Effort = max abs diff along path. Minimize max diff.',`int minimumEffortPath(vector<vector<int>>&h){\n    int m=h.size(),n=h[0].size();\n    vector<vector<int>>dist(m,vector<int>(n,INT_MAX));\n    priority_queue<tuple<int,int,int>,vector<tuple<int,int,int>>,greater<>>pq;\n    dist[0][0]=0; pq.push({0,0,0});\n    int dr[]={1,-1,0,0},dc[]={0,0,1,-1};\n    while(!pq.empty()){auto[e,r,c]=pq.top();pq.pop();if(r==m-1&&c==n-1)return e;if(e>dist[r][c])continue;for(int d=0;d<4;d++){int nr=r+dr[d],nc=c+dc[d];if(nr>=0&&nr<m&&nc>=0&&nc<n){int ne=max(e,abs(h[nr][nc]-h[r][c]));if(ne<dist[nr][nc]){dist[nr][nc]=ne;pq.push({ne,nr,nc});}}}}\n    return 0;\n}`,'https://leetcode.com/problems/path-with-minimum-effort/'),
        gp('cheapest-flights-k-stops','Cheapest Flights Within K Stops','medium','Bellman-Ford K iterations','Relax edges K+1 times (at most K stops = K+1 edges).',`int findCheapestPrice(int n,vector<vector<int>>&f,int src,int dst,int k){\n    vector<int>dist(n,INT_MAX); dist[src]=0;\n    for(int i=0;i<=k;i++){\n        vector<int>tmp=dist;\n        for(auto&[u,v,w]:f) if(dist[u]!=INT_MAX&&dist[u]+w<tmp[v]) tmp[v]=dist[u]+w;\n        dist=tmp;\n    }\n    return dist[dst]==INT_MAX?-1:dist[dst];\n}`,'https://leetcode.com/problems/cheapest-flights-within-k-stops/'),
        gp('network-delay-time','Network Delay Time','medium','Dijkstra','Shortest path to all nodes from k. Answer = max of all shortest paths (if any unreachable, -1).',`int networkDelayTime(vector<vector<int>>&times,int n,int k){\n    vector<vector<pair<int,int>>>adj(n+1);\n    for(auto&[u,v,w]:times) adj[u].push_back({v,w});\n    vector<int>dist(n+1,INT_MAX); dist[k]=0;\n    priority_queue<pair<int,int>,vector<pair<int,int>>,greater<>>pq; pq.push({0,k});\n    while(!pq.empty()){auto[d,u]=pq.top();pq.pop();if(d>dist[u])continue;for(auto[v,w]:adj[u])if(dist[u]+w<dist[v]){dist[v]=dist[u]+w;pq.push({dist[v],v});}}\n    int mx=*max_element(dist.begin()+1,dist.end());\n    return mx==INT_MAX?-1:mx;\n}`,'https://leetcode.com/problems/network-delay-time/'),
      ],
    },
    {
      id: 'mst', title: 'Minimum Spanning Tree (Prim & Kruskal)',
      topics: [
        { id:'mst-intro', slug:'mst-intro', title:'Minimum Spanning Tree (Prim\'s and Kruskal\'s)', type:'lesson', difficulty:'medium',
          introduction:'A Minimum Spanning Tree (MST) of a connected weighted undirected graph is a spanning tree with minimum total edge weight.',
          theory:`**Prim's algorithm:** Greedy, like Dijkstra. Start from any vertex. Always add minimum weight edge connecting visited to unvisited vertex. Uses min-heap. O((V+E) log V).\n\n**Kruskal's algorithm:** Sort all edges by weight. Add edge if it doesn't form cycle (use Union-Find). O(E log E).\n\n**When to use:**\n- Prim: dense graphs (more edges)\n- Kruskal: sparse graphs (fewer edges)\n\n**Union-Find (Disjoint Set Union):** find(x) with path compression + union by rank = nearly O(1) per operation.`,
          codeExamples:[{title:'Prim and Kruskal',language:'cpp',code:`// Prim's\nint prims(int V, vector<vector<pair<int,int>>>& adj) {\n    vector<int> key(V, INT_MAX);\n    vector<bool> inMST(V, false);\n    priority_queue<pair<int,int>, vector<pair<int,int>>, greater<>> pq;\n    key[0] = 0; pq.push({0, 0});\n    int totalWeight = 0;\n    while (!pq.empty()) {\n        auto [w, u] = pq.top(); pq.pop();\n        if (inMST[u]) continue;\n        inMST[u] = true; totalWeight += w;\n        for (auto [v, wt] : adj[u])\n            if (!inMST[v] && wt < key[v]) { key[v] = wt; pq.push({wt, v}); }\n    }\n    return totalWeight;\n}\n\n// Union-Find for Kruskal\nstruct DSU {\n    vector<int> p, rank;\n    DSU(int n) : p(n), rank(n, 0) { iota(p.begin(), p.end(), 0); }\n    int find(int x) { return p[x] == x ? x : p[x] = find(p[x]); }\n    bool unite(int a, int b) {\n        a = find(a); b = find(b);\n        if (a == b) return false;\n        if (rank[a] < rank[b]) swap(a, b);\n        p[b] = a; if (rank[a] == rank[b]) rank[a]++;\n        return true;\n    }\n};`}],
          keyTakeaways:['Prim: greedy min-heap, add min edge from visited to unvisited.','Kruskal: sort edges, add if no cycle (DSU check).','DSU with path compression + union by rank: nearly O(1).'] },
        gp('accounts-merge','Accounts Merge','hard','Union-Find','Merge accounts sharing emails. Use Union-Find where each email maps to a component.',`vector<vector<string>> accountsMerge(vector<vector<string>>&accs){\n    unordered_map<string,int>emailId; unordered_map<string,string>emailName;\n    int id=0;\n    DSU dsu(accs.size()*100);\n    for(auto&acc:accs) for(int i=1;i<acc.size();i++){\n        if(!emailId.count(acc[i])){emailId[acc[i]]=id++;emailName[acc[i]]=acc[0];}\n        dsu.unite(emailId[acc[1]],emailId[acc[i]]);\n    }\n    unordered_map<int,vector<string>>comp;\n    for(auto&[e,i]:emailId) comp[dsu.find(i)].push_back(e);\n    vector<vector<string>>res;\n    for(auto&[root,emails]:comp){sort(emails.begin(),emails.end());emails.insert(emails.begin(),emailName[emails[0]]);res.push_back(emails);}\n    return res;\n}`,'https://leetcode.com/problems/accounts-merge/'),
        gp('connecting-cities-min-cost','Connecting Cities with Min Cost','medium','Kruskal (MST)','MST of city graph gives minimum cost to connect all cities.',`int minCostConnect(int n,vector<vector<int>>&conns){\n    sort(conns.begin(),conns.end(),[](auto&a,auto&b){return a[2]<b[2];});\n    DSU dsu(n+1); int cost=0,edges=0;\n    for(auto&c:conns) if(dsu.unite(c[0],c[1])){cost+=c[2];if(++edges==n-1)break;}\n    return edges==n-1?cost:-1;\n}`),
      ],
    },
    {
      id: 'graph-problems', title: 'Other Graph Problems',
      topics: [
        gp('strongly-connected-components','Strongly Connected Components (Kosaraju)', 'hard', 'Kosaraju\'s Algorithm', 'DFS on original → stack by finish time. Transpose graph. DFS on transpose in reverse finish order.',
          `void dfs1(int u,vector<bool>&vis,stack<int>&st,vector<vector<int>>&adj){\n    vis[u]=true;\n    for(int v:adj[u]) if(!vis[v]) dfs1(v,vis,st,adj);\n    st.push(u);\n}\nvoid dfs2(int u,vector<bool>&vis,vector<vector<int>>&radj){\n    vis[u]=true;\n    for(int v:radj[u]) if(!vis[v]) dfs2(v,vis,radj);\n}\nint kosaraju(int V,vector<vector<int>>&adj){\n    vector<bool>vis(V,false); stack<int>st;\n    for(int i=0;i<V;i++) if(!vis[i]) dfs1(i,vis,st,adj);\n    // build reverse graph\n    vector<vector<int>>radj(V);\n    for(int u=0;u<V;u++) for(int v:adj[u]) radj[v].push_back(u);\n    fill(vis.begin(),vis.end(),false); int scc=0;\n    while(!st.empty()){int u=st.top();st.pop();if(!vis[u]){dfs2(u,vis,radj);scc++;}}\n    return scc;\n}`),
        gp('bridges-in-graph','Bridges in Graph (Tarjan\'s Algorithm)', 'hard', 'Tarjan\'s Bridge Finding', 'Track discovery time and low value. Edge (u,v) is bridge if low[v] > disc[u].',
          `int timer=0;\nvoid dfs(int u,int p,vector<int>&disc,vector<int>&low,vector<bool>&vis,vector<vector<int>>&adj,vector<pair<int,int>>&bridges){\n    vis[u]=true; disc[u]=low[u]=timer++;\n    for(int v:adj[u]){\n        if(!vis[v]){dfs(v,u,disc,low,vis,adj,bridges);low[u]=min(low[u],low[v]);if(low[v]>disc[u])bridges.push_back({u,v});}\n        else if(v!=p) low[u]=min(low[u],disc[v]);\n    }\n}`),
      ],
    },
  ],
};
