import type { DSASection } from '@/types/dsa';

const dp = (id: string, title: string, diff: 'easy'|'medium'|'hard', pattern: string, intuition: string, code: string, lc?: string) => ({
  id, slug: id, title, type: 'problem' as const, difficulty: diff, pattern,
  approaches: [{ name: 'Optimal DP', intuition, steps: [], complexity: { time: 'O(N²)', space: 'O(N)' }, code }],
  hints: [intuition, 'Start with memoization, then convert to tabulation.', 'Base cases first.'],
  solution: code, ...(lc ? { leetcodeUrl: lc } : {}), keyTakeaways: [],
});

export const dpSection: DSASection = {
  id: 'dynamic-programming', slug: 'dynamic-programming',
  title: 'Dynamic Programming [Patterns and Problems]',
  description: 'Master DP from 1D to 2D patterns: Fibonacci, knapsack, LIS, LCS, partition, stocks, squares, and string DP.',
  icon: '📊', color: 'from-red-500 to-pink-600',
  subsections: [
    {
      id: 'dp-intro', title: '1D DP',
      topics: [
        { id:'dp-intro-lesson', slug:'dp-intro-lesson', title:'Introduction to Dynamic Programming', type:'lesson', difficulty:'easy',
          introduction:'DP solves problems with overlapping subproblems and optimal substructure. Memoization (top-down) or Tabulation (bottom-up).',
          theory:`**When to use DP:**\n1. Overlapping subproblems (same subproblems computed multiple times)\n2. Optimal substructure (solution built from optimal solutions of subproblems)\n\n**Two approaches:**\n- **Memoization (Top-Down):** Recursion + cache. Natural to write, same time complexity as tabulation.\n- **Tabulation (Bottom-Up):** Fill table iteratively. Avoids recursion overhead.\n\n**Steps to solve any DP:**\n1. Define state: what does dp[i] represent?\n2. Recurrence: how does dp[i] relate to smaller states?\n3. Base cases: dp[0], dp[1], etc.\n4. Order: ensure subproblems computed before main\n5. Answer: which dp value is the answer?`,
          codeExamples:[{title:'Fibonacci — 3 ways',language:'cpp',code:`// Naive recursion: O(2^N)\nint fib(int n){if(n<=1)return n;return fib(n-1)+fib(n-2);}\n\n// Memoization: O(N) time, O(N) space\nint memo[100];\nint fib(int n){if(n<=1)return n;if(memo[n]!=-1)return memo[n];return memo[n]=fib(n-1)+fib(n-2);}\n\n// Tabulation: O(N) time, O(N) space\nint fib(int n){if(n<=1)return n;vector<int>dp(n+1);dp[0]=0;dp[1]=1;for(int i=2;i<=n;i++)dp[i]=dp[i-1]+dp[i-2];return dp[n];}\n\n// Space optimization: O(1) space\nint fib(int n){if(n<=1)return n;int a=0,b=1;for(int i=2;i<=n;i++){int c=a+b;a=b;b=c;}return b;}`}],
          keyTakeaways:['DP = overlapping subproblems + optimal substructure.','Memoize recursion → tabulate → space optimize: the 4-step journey.'] },
        dp('climbing-stairs','Climbing Stairs','easy','Fibonacci DP','dp[i] = dp[i-1] + dp[i-2] (reach from i-1 or i-2).','int climbStairs(int n){int a=1,b=1;for(int i=2;i<=n;i++){int c=a+b;a=b;b=c;}return b;}','https://leetcode.com/problems/climbing-stairs/'),
        dp('frog-jump','Frog Jump (Min Cost / Geek Jump)','easy','1D DP','dp[i] = min(dp[i-1]+|h[i]-h[i-1]|, dp[i-2]+|h[i]-h[i-2]|)','vector<int>dp(n,INT_MAX);dp[0]=0;for(int i=1;i<n;i++){dp[i]=dp[i-1]+abs(h[i]-h[i-1]);if(i>1)dp[i]=min(dp[i],dp[i-2]+abs(h[i]-h[i-2]));}'),
        dp('max-sum-non-adjacent','Maximum Sum of Non-Adjacent Elements / House Robber','medium','1D DP','dp[i] = max(dp[i-1], dp[i-2]+nums[i]). Can\'t pick adjacent.','int rob(vector<int>&n){int prev2=0,prev1=0;for(int x:n){int cur=max(prev1,prev2+x);prev2=prev1;prev1=cur;}return prev1;}','https://leetcode.com/problems/house-robber/'),
        dp('house-robber-2','House Robber II (Circular)','medium','1D DP on Circular Array','Run House Robber on [0..n-2] and [1..n-1]. Take max.',`int rob2(vector<int>&n){\n    int m=n.size();\n    if(m==1) return n[0];\n    auto rob=[](vector<int>&a,int l,int r){int p2=0,p1=0;for(int i=l;i<=r;i++){int c=max(p1,p2+a[i]);p2=p1;p1=c;}return p1;};\n    return max(rob(n,0,m-2),rob(n,1,m-1));\n}`,'https://leetcode.com/problems/house-robber-ii/'),
        dp('minimum-path-sum','Minimum Path Sum in Grid','medium','2D DP','dp[i][j] = grid[i][j] + min(dp[i-1][j], dp[i][j-1]).',`int minPathSum(vector<vector<int>>&g){\n    int m=g.size(),n=g[0].size();\n    for(int i=0;i<m;i++) for(int j=0;j<n;j++){\n        if(i==0&&j==0) continue;\n        else if(i==0) g[i][j]+=g[i][j-1];\n        else if(j==0) g[i][j]+=g[i-1][j];\n        else g[i][j]+=min(g[i-1][j],g[i][j-1]);\n    }\n    return g[m-1][n-1];\n}`,'https://leetcode.com/problems/minimum-path-sum/'),
      ],
    },
    {
      id: 'dp-subsequences', title: 'DP on Subsequences',
      topics: [
        dp('subset-sum','Subset Sum Problem','medium','DP','dp[i][j] = true if subset of arr[0..i] has sum j. dp[i][j] = dp[i-1][j] || dp[i-1][j-arr[i]].',`bool subsetSum(vector<int>&a,int t){\n    int n=a.size();\n    vector<vector<bool>>dp(n+1,vector<bool>(t+1,false));\n    for(int i=0;i<=n;i++) dp[i][0]=true;\n    for(int i=1;i<=n;i++) for(int j=1;j<=t;j++){\n        dp[i][j]=dp[i-1][j];\n        if(a[i-1]<=j) dp[i][j]=dp[i][j]||dp[i-1][j-a[i-1]];\n    }\n    return dp[n][t];\n}`),
        dp('count-subsets-sum-k','Count Subsets with Sum K','medium','DP','dp[i][j] = count of subsets of a[0..i] with sum j. dp[i][j] = dp[i-1][j] + dp[i-1][j-a[i]].',`int countSubsets(vector<int>&a,int k){\n    int n=a.size();\n    vector<vector<int>>dp(n+1,vector<int>(k+1,0));\n    for(int i=0;i<=n;i++) dp[i][0]=1;\n    for(int i=1;i<=n;i++) for(int j=1;j<=k;j++){\n        dp[i][j]=dp[i-1][j];\n        if(a[i-1]<=j) dp[i][j]+=dp[i-1][j-a[i-1]];\n    }\n    return dp[n][k];\n}`),
        dp('0-1-knapsack','0/1 Knapsack Problem','medium','DP — Classic Knapsack','dp[i][w] = max value using items 0..i with weight limit w.',`int knapsack(vector<int>&wt,vector<int>&val,int W){\n    int n=wt.size();\n    vector<vector<int>>dp(n+1,vector<int>(W+1,0));\n    for(int i=1;i<=n;i++) for(int w=1;w<=W;w++){\n        dp[i][w]=dp[i-1][w]; // don't take\n        if(wt[i-1]<=w) dp[i][w]=max(dp[i][w],dp[i-1][w-wt[i-1]]+val[i-1]); // take\n    }\n    return dp[n][W];\n}`),
        dp('coin-change','Coin Change (Min Coins)','medium','DP — Unbounded Knapsack','dp[i] = min coins to make amount i. dp[i] = min(dp[i], 1+dp[i-coin]) for each coin.',`int coinChange(vector<int>&coins,int amount){\n    vector<int>dp(amount+1,amount+1);\n    dp[0]=0;\n    for(int i=1;i<=amount;i++) for(int c:coins) if(c<=i) dp[i]=min(dp[i],1+dp[i-c]);\n    return dp[amount]>amount?-1:dp[amount];\n}`,'https://leetcode.com/problems/coin-change/'),
        dp('coin-change-2','Coin Change II (Number of Ways)','medium','DP — Unbounded Knapsack (Count)','dp[i] = number of ways to make amount i. For each coin, dp[j] += dp[j-coin].',`int change(int amount,vector<int>&coins){\n    vector<long long>dp(amount+1,0); dp[0]=1;\n    for(int c:coins) for(int j=c;j<=amount;j++) dp[j]+=dp[j-c];\n    return dp[amount];\n}`,'https://leetcode.com/problems/coin-change-ii/'),
        dp('target-sum','Target Sum (Count Ways to Assign +/-)','medium','DP','Count subsets with sum = (total+target)/2. Uses count-subsets DP.',`int findTargetSumWays(vector<int>&a,int t){\n    int sum=accumulate(a.begin(),a.end(),0);\n    if((sum+t)%2!=0||(sum+t)<0) return 0;\n    int k=(sum+t)/2;\n    vector<int>dp(k+1,0); dp[0]=1;\n    for(int x:a) for(int j=k;j>=x;j--) dp[j]+=dp[j-x];\n    return dp[k];\n}`,'https://leetcode.com/problems/target-sum/'),
        dp('unbounded-knapsack','Unbounded Knapsack (Items Reusable)','medium','DP — Unbounded','Same as 0/1 but iterate items in inner loop without bound, or use 1D DP forward.',`int unboundedKnapsack(vector<int>&wt,vector<int>&val,int W){\n    vector<int>dp(W+1,0);\n    for(int w=1;w<=W;w++) for(int i=0;i<wt.size();i++) if(wt[i]<=w) dp[w]=max(dp[w],dp[w-wt[i]]+val[i]);\n    return dp[W];\n}`),
        dp('rod-cutting','Rod Cutting Problem','medium','DP — Unbounded Knapsack','Cut rod of length n to maximize value. Each piece length is weight, price is value.',`int rodCutting(vector<int>&price,int n){\n    vector<int>dp(n+1,0);\n    for(int i=1;i<=n;i++) for(int j=1;j<=i;j++) dp[i]=max(dp[i],price[j-1]+dp[i-j]);\n    return dp[n];\n}`),
      ],
    },
    {
      id: 'dp-strings', title: 'DP on Strings',
      topics: [
        dp('lcs','Longest Common Subsequence','medium','2D DP','dp[i][j] = LCS of s1[0..i] and s2[0..j]. If s1[i]==s2[j]: dp[i][j]=1+dp[i-1][j-1]. Else max(dp[i-1][j],dp[i][j-1]).',`int lcs(string s,string t){\n    int m=s.size(),n=t.size();\n    vector<vector<int>>dp(m+1,vector<int>(n+1,0));\n    for(int i=1;i<=m;i++) for(int j=1;j<=n;j++)\n        dp[i][j]=(s[i-1]==t[j-1])?1+dp[i-1][j-1]:max(dp[i-1][j],dp[i][j-1]);\n    return dp[m][n];\n}`,'https://leetcode.com/problems/longest-common-subsequence/'),
        dp('edit-distance','Edit Distance (Levenshtein)','hard','2D DP','dp[i][j] = min ops to convert s[0..i] to t[0..j]. Insert/Delete/Replace.',`int minDistance(string s,string t){\n    int m=s.size(),n=t.size();\n    vector<vector<int>>dp(m+1,vector<int>(n+1));\n    for(int i=0;i<=m;i++) dp[i][0]=i;\n    for(int j=0;j<=n;j++) dp[0][j]=j;\n    for(int i=1;i<=m;i++) for(int j=1;j<=n;j++){\n        if(s[i-1]==t[j-1]) dp[i][j]=dp[i-1][j-1];\n        else dp[i][j]=1+min({dp[i-1][j-1],dp[i-1][j],dp[i][j-1]});\n    }\n    return dp[m][n];\n}`,'https://leetcode.com/problems/edit-distance/'),
        dp('wildcard-matching','Wildcard Matching (? and *)','hard','2D DP','? matches any single char. * matches any sequence (including empty). dp[i][j] = pattern[0..i] matches string[0..j].',`bool isMatch(string s,string p){\n    int m=s.size(),n=p.size();\n    vector<vector<bool>>dp(n+1,vector<bool>(m+1,false));\n    dp[0][0]=true;\n    for(int i=1;i<=n;i++) if(p[i-1]=='*') dp[i][0]=dp[i-1][0];\n    for(int i=1;i<=n;i++) for(int j=1;j<=m;j++){\n        if(p[i-1]=='*') dp[i][j]=dp[i-1][j]||dp[i][j-1];\n        else dp[i][j]=(p[i-1]=='?'||p[i-1]==s[j-1])&&dp[i-1][j-1];\n    }\n    return dp[n][m];\n}`,'https://leetcode.com/problems/wildcard-matching/'),
        dp('distinct-subsequences','Distinct Subsequences','hard','2D DP','Count distinct ways s subsequence matches t. dp[i][j]: ways s[0..i-1] contains t[0..j-1] as subseq.',`int numDistinct(string s,string t){\n    int m=s.size(),n=t.size();\n    vector<vector<long long>>dp(m+1,vector<long long>(n+1,0));\n    for(int i=0;i<=m;i++) dp[i][0]=1;\n    for(int i=1;i<=m;i++) for(int j=1;j<=n;j++){\n        dp[i][j]=dp[i-1][j];\n        if(s[i-1]==t[j-1]) dp[i][j]+=dp[i-1][j-1];\n    }\n    return dp[m][n];\n}`,'https://leetcode.com/problems/distinct-subsequences/'),
        dp('longest-palindromic-subsequence','Longest Palindromic Subsequence','medium','LCS variant','LPS(s) = LCS(s, reverse(s)).',`int longestPalindromicSubseq(string s){\n    string t=s; reverse(t.begin(),t.end());\n    int n=s.size();\n    vector<vector<int>>dp(n+1,vector<int>(n+1,0));\n    for(int i=1;i<=n;i++) for(int j=1;j<=n;j++)\n        dp[i][j]=(s[i-1]==t[j-1])?1+dp[i-1][j-1]:max(dp[i-1][j],dp[i][j-1]);\n    return dp[n][n];\n}`,'https://leetcode.com/problems/longest-palindromic-subsequence/'),
        dp('minimum-insertions-palindrome','Minimum Insertions to Make String Palindrome','medium','LPS based','Min insertions = N - LPS(s). Remove chars not in LPS, insert same count to mirror.',`int minInsertions(string s){int n=s.size();string t=s;reverse(t.begin(),t.end());/* lcs of s and t = LPS */ return n-lcs(s,t);}`,'https://leetcode.com/problems/minimum-insertion-steps-to-make-a-string-palindrome/'),
      ],
    },
    {
      id: 'dp-stocks', title: 'DP on Stocks',
      topics: [
        dp('stocks-1','Best Time to Buy and Sell Stock I (One Transaction)','easy','Greedy','Track min price so far, update max profit.',`int maxProfit(vector<int>&p){int mn=p[0],mx=0;for(int x:p){mn=min(mn,x);mx=max(mx,x-mn);}return mx;}`,'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/'),
        dp('stocks-2','Best Time to Buy and Sell Stock II (Unlimited Transactions)','medium','Greedy','Add every positive day-over-day increase (buy at every valley, sell at every peak).',`int maxProfit2(vector<int>&p){int r=0;for(int i=1;i<p.size();i++)if(p[i]>p[i-1])r+=p[i]-p[i-1];return r;}`,'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/'),
        dp('stocks-3','Best Time to Buy and Sell Stock III (At most 2 Transactions)','hard','State DP','4 states: buy1, sell1, buy2, sell2. Each day update in reverse order.',`int maxProfit3(vector<int>&p){int b1=INT_MIN,s1=0,b2=INT_MIN,s2=0;for(int x:p){b1=max(b1,-x);s1=max(s1,b1+x);b2=max(b2,s1-x);s2=max(s2,b2+x);}return s2;}`,'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/'),
        dp('stocks-4','Best Time to Buy and Sell Stock IV (At most K Transactions)','hard','2D DP','dp[k][i] = max profit with at most k transactions up to day i.',`int maxProfitK(int k,vector<int>&p){int n=p.size();if(k>=n/2){int r=0;for(int i=1;i<n;i++)if(p[i]>p[i-1])r+=p[i]-p[i-1];return r;}vector<vector<int>>dp(k+1,vector<int>(n,0));for(int t=1;t<=k;t++){int maxSoFar=-p[0];for(int i=1;i<n;i++){dp[t][i]=max(dp[t][i-1],p[i]+maxSoFar);maxSoFar=max(maxSoFar,dp[t-1][i]-p[i]);}}return dp[k][n-1];}`,'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iv/'),
        dp('stocks-cooldown','Best Time to Buy and Sell Stock with Cooldown','medium','State DP','States: holding, cooldown, free. Transition each day.',`int maxProfitCooldown(vector<int>&p){int hold=INT_MIN,cool=0,free=0;for(int x:p){int nh=max(hold,free-x),nc=hold+x,nf=max(free,cool);hold=nh;cool=nc;free=nf;}return max(cool,free);}`,'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/'),
      ],
    },
    {
      id: 'dp-lis', title: 'DP on Longest Increasing Subsequence',
      topics: [
        dp('lis','Longest Increasing Subsequence','medium','DP O(N²) / Patience Sorting O(N log N)','dp[i] = length of LIS ending at i. dp[i] = max(dp[j]+1) for all j<i where a[j]<a[i].',`int lis(vector<int>&a){\n    int n=a.size();\n    vector<int>dp(n,1);\n    for(int i=1;i<n;i++) for(int j=0;j<i;j++) if(a[j]<a[i]) dp[i]=max(dp[i],dp[j]+1);\n    return *max_element(dp.begin(),dp.end());\n}\n// O(N log N) with patience sorting:\nint lisOptimal(vector<int>&a){vector<int>tails;for(int x:a){auto it=lower_bound(tails.begin(),tails.end(),x);if(it==tails.end())tails.push_back(x);else *it=x;}return tails.size();}`,'https://leetcode.com/problems/longest-increasing-subsequence/'),
        dp('largest-divisible-subset','Largest Divisible Subset','medium','DP — LIS variant','Sort. dp[i] = longest subset ending at i where subset[j] divides nums[i].',`vector<int> largestDivisibleSubset(vector<int>&n){sort(n.begin(),n.end());int sz=n.size();vector<int>dp(sz,1),par(sz,-1);int mxIdx=0;for(int i=1;i<sz;i++){for(int j=0;j<i;j++) if(n[i]%n[j]==0&&dp[j]+1>dp[i]){dp[i]=dp[j]+1;par[i]=j;}if(dp[i]>dp[mxIdx])mxIdx=i;}vector<int>res;for(int i=mxIdx;i!=-1;i=par[i])res.push_back(n[i]);return res;}`,'https://leetcode.com/problems/largest-divisible-subset/'),
        dp('number-of-lis','Number of Longest Increasing Subsequences','hard','DP with count array','dp[i]=LIS length ending at i. cnt[i]=count of LIS of that length ending at i.',`int findNumberOfLIS(vector<int>&n){int sz=n.size();vector<int>len(sz,1),cnt(sz,1);for(int i=1;i<sz;i++) for(int j=0;j<i;j++) if(n[j]<n[i]){if(len[j]+1>len[i]){len[i]=len[j]+1;cnt[i]=cnt[j];}else if(len[j]+1==len[i])cnt[i]+=cnt[j];}int mxL=*max_element(len.begin(),len.end()),res=0;for(int i=0;i<sz;i++)if(len[i]==mxL)res+=cnt[i];return res;}`,'https://leetcode.com/problems/number-of-longest-increasing-subsequence/'),
      ],
    },
    {
      id: 'dp-squares', title: 'DP on Squares and Rectangles',
      topics: [
        dp('maximal-square','Maximal Square of 1s','medium','2D DP','dp[i][j] = side length of largest square ending at (i,j). dp[i][j] = 1+min(dp[i-1][j],dp[i][j-1],dp[i-1][j-1]) when matrix[i][j]==1.',`int maximalSquare(vector<vector<char>>&m){int rows=m.size(),cols=m[0].size(),mx=0;vector<vector<int>>dp(rows+1,vector<int>(cols+1,0));for(int i=1;i<=rows;i++) for(int j=1;j<=cols;j++) if(m[i-1][j-1]=='1'){dp[i][j]=1+min({dp[i-1][j],dp[i][j-1],dp[i-1][j-1]});mx=max(mx,dp[i][j]);}return mx*mx;}`,'https://leetcode.com/problems/maximal-square/'),
        dp('count-square-submatrices','Count Square Submatrices with All 1s','medium','2D DP','dp[i][j] = number of squares with bottom-right at (i,j). Sum all dp values.',`int countSquares(vector<vector<int>>&m){int res=0;for(int i=0;i<m.size();i++) for(int j=0;j<m[0].size();j++){if(m[i][j]&&i&&j)m[i][j]=1+min({m[i-1][j],m[i][j-1],m[i-1][j-1]});res+=m[i][j];}return res;}`,'https://leetcode.com/problems/count-square-submatrices-with-all-ones/'),
      ],
    },
    {
      id: 'dp-partition', title: 'DP on Partition',
      topics: [
        dp('matrix-chain','Matrix Chain Multiplication','hard','DP — Interval','dp[i][j] = min cost to multiply matrices i..j. Try all splits k.',`int matrixChain(vector<int>&dims){int n=dims.size()-1;vector<vector<int>>dp(n,vector<int>(n,0));for(int len=2;len<=n;len++) for(int i=0;i<=n-len;i++){int j=i+len-1;dp[i][j]=INT_MAX;for(int k=i;k<j;k++) dp[i][j]=min(dp[i][j],dp[i][k]+dp[k+1][j]+dims[i]*dims[k+1]*dims[j+1]);}return dp[0][n-1];}`),
        dp('min-cost-tree','Minimum Cost Tree from Leaf Values','medium','DP — Interval / Monotonic Stack','Optimal BST variant. dp[i][j] = min sum of non-leaf nodes in optimal BST for leaves i..j.',`int mctFromLeafValues(vector<int>&a){int n=a.size();vector<vector<int>>dp(n,vector<int>(n,0)),mx(n,vector<int>(n,0));for(int i=0;i<n;i++) for(int j=i;j<n;j++) mx[i][j]=*max_element(a.begin()+i,a.begin()+j+1);for(int len=2;len<=n;len++) for(int i=0;i<=n-len;i++){int j=i+len-1;dp[i][j]=INT_MAX;for(int k=i;k<j;k++) dp[i][j]=min(dp[i][j],dp[i][k]+dp[k+1][j]+mx[i][k]*mx[k+1][j]);}return dp[0][n-1];}`,'https://leetcode.com/problems/minimum-cost-tree-from-leaf-values/'),
        dp('palindrome-partition-2','Palindrome Partitioning II (Minimum Cuts)','hard','DP','dp[i] = min cuts for s[0..i]. For each j<i: if s[j..i] is palindrome, dp[i]=min(dp[i],dp[j-1]+1).',`int minCut(string s){int n=s.size();vector<int>dp(n);iota(dp.begin(),dp.end(),0);vector<vector<bool>>pal(n,vector<bool>(n,false));for(int i=0;i<n;i++) for(int j=0;j<=i;j++) if(s[i]==s[j]&&(i-j<=2||pal[j+1][i-1])) pal[j][i]=true;for(int i=1;i<n;i++){if(pal[0][i]){dp[i]=0;continue;}for(int j=1;j<=i;j++) if(pal[j][i]) dp[i]=min(dp[i],dp[j-1]+1);}return dp[n-1];}`,'https://leetcode.com/problems/palindrome-partitioning-ii/'),
        dp('burst-balloons','Burst Balloons','hard','DP — Interval (Think Backwards)','Think of last balloon to burst. dp[l][r] = max coins from bursting all balloons between l and r.',`int maxCoins(vector<int>&b){b.insert(b.begin(),1);b.push_back(1);int n=b.size();vector<vector<int>>dp(n,vector<int>(n,0));for(int len=2;len<n;len++) for(int l=0;l<n-len;l++){int r=l+len;for(int k=l+1;k<r;k++) dp[l][r]=max(dp[l][r],dp[l][k]+dp[k][r]+b[l]*b[k]*b[r]);}return dp[0][n-1];}`,'https://leetcode.com/problems/burst-balloons/'),
        dp('egg-drop','Egg Drop Problem (K Eggs, N Floors)','hard','DP / Binary Search','dp[t][k] = max floors testable in t trials with k eggs.',`int superEggDrop(int k,int n){vector<vector<int>>dp(n+1,vector<int>(k+1,0));int t=0;while(dp[t][k]<n){t++;for(int e=1;e<=k;e++) dp[t][e]=dp[t-1][e-1]+dp[t-1][e]+1;}return t;}`,'https://leetcode.com/problems/super-egg-drop/'),
      ],
    },
  ],
};
