import type { DSASection } from '@/types/dsa';

export const stringsHardSection: DSASection = {
  id: 'strings-hard', slug: 'strings-hard',
  title: 'Strings [Hard Problems]',
  description: 'Advanced string algorithms: KMP pattern matching, Z-algorithm, Rabin-Karp, string hashing, and suffix structures.',
  icon: '🔡', color: 'from-rose-600 to-red-700',
  subsections: [
    {
      id: 'strings-hard-problems', title: 'Hard Problems',
      topics: [
        { id:'kmp-algorithm', slug:'kmp-algorithm', title:'KMP Algorithm for Pattern Matching', type:'lesson', difficulty:'hard',
          introduction:'Knuth-Morris-Pratt (KMP) finds all occurrences of pattern P in text T in O(N+M) time using a failure function (prefix function).',
          theory:`**Naive pattern matching:** O(N*M) — backtrack on mismatch.\n\n**KMP idea:** Build failure function (lps array) for pattern. lps[i] = length of longest proper prefix of pattern[0..i] that is also a suffix. On mismatch, don't reset text pointer — jump using lps.\n\n**LPS (Longest Proper Prefix Suffix):**\n- "aaaa" → [0,1,2,3]\n- "abcabc" → [0,0,0,1,2,3]\n- "abcabcd" → [0,0,0,1,2,3,0]\n\n**Uses:** String matching, cycle detection in strings, count occurrences.`,
          codeExamples:[{title:'KMP Algorithm',language:'cpp',code:`vector<int> buildLPS(string p) {\n    int m = p.size();\n    vector<int> lps(m, 0);\n    int len = 0, i = 1;\n    while (i < m) {\n        if (p[i] == p[len]) { lps[i++] = ++len; }\n        else if (len) len = lps[len-1];\n        else lps[i++] = 0;\n    }\n    return lps;\n}\n\nvector<int> kmpSearch(string text, string pattern) {\n    auto lps = buildLPS(pattern);\n    vector<int> matches;\n    int i = 0, j = 0;\n    while (i < text.size()) {\n        if (text[i] == pattern[j]) { i++; j++; }\n        if (j == pattern.size()) {\n            matches.push_back(i - j);\n            j = lps[j-1];\n        } else if (i < text.size() && text[i] != pattern[j]) {\n            if (j) j = lps[j-1]; else i++;\n        }\n    }\n    return matches;\n}`}],
          keyTakeaways:['KMP: O(N+M). Build LPS first O(M), then search O(N).','On mismatch: j=lps[j-1] (don\'t reset to 0).','LPS = longest proper prefix that is also suffix.'] },
        { id:'z-algorithm', slug:'z-algorithm', title:'Z-Algorithm for Pattern Matching', type:'lesson', difficulty:'hard',
          introduction:'Z-algorithm computes Z-array where Z[i] = length of longest string starting at position i that is also a prefix of the string. Used for O(N+M) pattern matching.',
          theory:`**Z-array:** Z[0] = length of string (by convention). Z[i] = length of longest substring starting at i that matches a prefix.\n\n**Pattern search:** Construct P+"$"+T. Positions in T where Z[i] == |P| are match positions.\n\n**Z-box:** Maintain [l,r] as the rightmost Z-box found. Use it to avoid recomputation.`,
          codeExamples:[{title:'Z-Algorithm',language:'cpp',code:`vector<int> zFunction(string s) {\n    int n = s.size();\n    vector<int> z(n, 0);\n    int l = 0, r = 0;\n    for (int i = 1; i < n; i++) {\n        if (i < r) z[i] = min(r-i, z[i-l]);\n        while (i+z[i] < n && s[z[i]] == s[i+z[i]]) z[i]++;\n        if (i+z[i] > r) { l = i; r = i+z[i]; }\n    }\n    return z;\n}\n\nvoid zSearch(string text, string pattern) {\n    string s = pattern + "$" + text;\n    auto z = zFunction(s);\n    int m = pattern.size();\n    for (int i = m+1; i < s.size(); i++)\n        if (z[i] == m) cout << i-m-1 << " "; // match at position i-m-1\n}`}],
          keyTakeaways:['Z-algorithm: O(N). Z[i]=length of prefix match at position i.','Pattern search: P+"$"+T. Z[i]==|P| → match at i-|P|-1.'] },
        { id:'rabin-karp', slug:'rabin-karp', title:'Rabin-Karp Algorithm (Rolling Hash)', type:'lesson', difficulty:'hard',
          introduction:'Rabin-Karp uses polynomial rolling hash for pattern matching. Average O(N+M), useful for multiple pattern search.',
          theory:`**Hash function:** hash(s[0..m-1]) = s[0]*b^(m-1) + s[1]*b^(m-2) + ... + s[m-1] (mod p)\n\n**Rolling hash:** When window slides by 1:\nhash_new = (hash_old - s[i]*b^(m-1)) * b + s[i+m]\n\n**Collisions:** If hashes match, verify string equality (spurious hits).\n\n**Advantage:** Multiple patterns: hash all patterns O(k*m), compare each window hash O(1) → O(N) for search part.`,
          codeExamples:[{title:'Rabin-Karp',language:'cpp',code:`int rabinKarp(string text, string pattern) {\n    int n=text.size(), m=pattern.size();\n    long long B=31, MOD=1e9+7, power=1;\n    long long pH=0, tH=0;\n    for(int i=0;i<m-1;i++) power=power*B%MOD;\n    for(int i=0;i<m;i++){\n        pH=(pH*B+pattern[i]-'a'+1)%MOD;\n        tH=(tH*B+text[i]-'a'+1)%MOD;\n    }\n    for(int i=0;i<=n-m;i++){\n        if(pH==tH && text.substr(i,m)==pattern) return i; // verify\n        if(i<n-m){\n            tH=(tH-(text[i]-'a'+1)*power%MOD+MOD)*B%MOD;\n            tH=(tH+text[i+m]-'a'+1)%MOD;\n        }\n    }\n    return -1;\n}`}],
          keyTakeaways:['Rolling hash: remove leftmost char, add rightmost. O(1) hash update.','Always verify on hash match (collision possible).','Best for: multiple pattern search, substring matching.'] },
        { id:'min-chars-to-add-palindrome', slug:'min-chars-to-add-palindrome', title:'Min Characters to Add at Front to Make Palindrome', type:'problem', difficulty:'hard', pattern:'KMP',
          problemStatement:'Find minimum characters to add at front of string to make it a palindrome.',
          examples:[{input:'"ABC"', output:'2', explanation:'"CBABC"'}],
          approaches:[{name:'KMP on s + "#" + reverse(s)',intuition:'Concatenate s + "#" + rev(s). Run KMP. lps of last char = longest suffix of s that is palindromic prefix. Answer = n - lps[last].',steps:['Compute lps of s+"#"+rev(s)','Answer = n - lps.back()'],complexity:{time:'O(N)',space:'O(N)'},code:`int minChars(string s){\n    string t=s+"#"+string(s.rbegin(),s.rend());\n    int n=t.size(); vector<int>lps(n,0);\n    for(int i=1,len=0;i<n;){\n        if(t[i]==t[len]){lps[i++]=++len;}\n        else if(len) len=lps[len-1];\n        else lps[i++]=0;\n    }\n    return s.size()-lps.back();\n}`}],
          hints:['Concatenate s + "#" + reverse(s).','Run KMP failure function.','Last lps value = length of longest palindromic prefix of s.'],
          solution:`int f(string s){string t=s+"#"+string(s.rbegin(),s.rend());int n=t.size();vector<int>l(n,0);for(int i=1,len=0;i<n;){if(t[i]==t[len])l[i++]=++len;else if(len)len=l[len-1];else l[i++]=0;}return s.size()-l.back();}`,
          keyTakeaways:['KMP failure function on s+"#"+reverse(s) gives longest palindromic prefix length.'] },
        { id:'count-palindromic-substrings', slug:'count-palindromic-substrings', title:'Count Palindromic Substrings (Manacher\'s Algorithm)', type:'lesson', difficulty:'hard',
          introduction:"Manacher's algorithm finds all palindromic substrings in O(N) time by extending palindromes using previously computed info.",
          theory:`**Key idea:** For each center (character or between characters), maintain rightmost palindrome boundary [center, right]. Use mirror of current position to avoid recomputation.\n\n**Transform:** Insert # between chars and at ends: "abc" → "#a#b#c#". All palindromes now have odd length.\n\n**P[i]:** radius of palindrome centered at i in transformed string.\n\n**Time:** O(N) — each character considered at most twice.`,
          codeExamples:[{title:"Manacher's Algorithm",language:'cpp',code:`vector<int> manacher(string s) {\n    string t = "#";\n    for (char c : s) { t += c; t += '#'; }\n    int n = t.size();\n    vector<int> p(n, 0);\n    int center = 0, right = 0;\n    for (int i = 0; i < n; i++) {\n        if (i < right) p[i] = min(right-i, p[2*center-i]);\n        while (i-p[i]-1>=0 && i+p[i]+1<n && t[i-p[i]-1]==t[i+p[i]+1]) p[i]++;\n        if (i+p[i] > right) { center=i; right=i+p[i]; }\n    }\n    return p;\n}\n// Count palindromic substrings: sum of (p[i]+1)/2 for each position`}],
          keyTakeaways:["Manacher's: O(N) all palindromic substrings.",'Transform with # to unify odd/even length cases.','P[i] = radius. Actual length = P[i] in original string.'] },
        { id:'minimum-window-string-v2', slug:'minimum-window-string-v2', title:'Shortest Superstring (Greedy + Bitmask DP)', type:'problem', difficulty:'hard', pattern:'DP + Bitmask',
          problemStatement:'Given array of strings, find the shortest string that contains each string as a substring.',
          examples:[{input:'["catg","ctaagt","gcta","ttca","atgcatc"]', output:'"gctaagttcatgcatc"'}],
          approaches:[{name:'Bitmask DP (TSP variant)',intuition:'State: (mask of included strings, last string). dp[mask][i] = min length to include all strings in mask ending with string i.',steps:['Compute overlap[i][j] = chars of j that can be appended after i','dp[mask][i] = shortest superstring using strings in mask, ending with i','O(2^N * N²) states'],complexity:{time:'O(2^N * N²)',space:'O(2^N * N)'},code:`// Overlap computation + bitmask DP like TSP\n// For n≤12: dp[1<<n][n] feasible`}],
          hints:['Precompute overlap between all pairs of strings.','This is essentially TSP on strings — use bitmask DP.','State: (set of strings used, last string). Fill with min superstring length.'],
          solution:`// Bitmask DP as described`, leetcodeUrl:'https://leetcode.com/problems/find-the-shortest-superstring/', keyTakeaways:['Shortest superstring = TSP on strings. Bitmask DP O(2^N * N²).'] },
      ],
    },
  ],
};
